//#;; DO NOT EDIT THIS FILE
/*ENCRYPT_ME*/
////////////////////////////////////////////////////////////////////////////////
//# Copyright (c) 2018 Secantec
//# No Permission to modify and distribute this program
//# even if this copyright message remains unaltered.
//#
//# Author: Secantec 27 April, 2018
//# $Id: $//#
//# Revision History
//#       MM      17  April, 2018    Initial release
//#
////////////////////////////////////////////////////////////////////////////////

// /bin/rm -rf *simv* *csrc* ; perl vpp.pl -perl sntc_berlekamp.1.sv > sntc_berlekamp.1.vpp.sv ; vcs -sverilog -R -debug_all sntc_berlekamp.1.vpp.sv -l sntc_berlekamp.1.vpp.sv.log

 /*ENCRYPT_ME*/


//final:MYSEED:600500
//final:PARAM_m:6
//final:PARAM_t:5

// pRev[0]:1
// pRev[1]:0
// pRev[2]:0
// pRev[3]:0
// pRev[4]:0
// pRev[5]:1
// POLY perl :0x3
// pRev[0]:1
// pRev[1]:0
// pRev[2]:0
// pRev[3]:0
// pRev[4]:0
// pRev[5]:1
// POLY perl :0x3



/* verilator lint_off DECLFILENAME */
(* keep_hierarchy = "yes" *) (* keep = "true" *) (* dont_touch = "true" *)  interface sntc_rs_encode_if(
         /* verilator lint_off UNUSED */
         input clk
         /* verilator lint_on UNUSED */
);
 parameter  PARAM_m = 6;
 parameter  PARAM_n = 63;
 parameter  PARAM_reduced_n = 63;
 parameter  PARAM_k = 53;
 parameter  PARAM_t = 5;
 parameter  PARAM_t2 = 10;
 parameter  PARAM_d = 11;
 parameter  PARAM_w = 6;
 parameter  PARAM_parNum = 58;

/* verilator lint_off UNDRIVEN */
(* keep = "true" *) logic [6-1:0] bb0;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00000;
(* keep = "true" *) logic data_valid_00000;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00001;
(* keep = "true" *) logic data_valid_00001;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00002;
(* keep = "true" *) logic data_valid_00002;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00003;
(* keep = "true" *) logic data_valid_00003;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00004;
(* keep = "true" *) logic data_valid_00004;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00005;
(* keep = "true" *) logic data_valid_00005;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00006;
(* keep = "true" *) logic data_valid_00006;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00007;
(* keep = "true" *) logic data_valid_00007;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00008;
(* keep = "true" *) logic data_valid_00008;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00009;
(* keep = "true" *) logic data_valid_00009;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00010;
(* keep = "true" *) logic data_valid_00010;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00011;
(* keep = "true" *) logic data_valid_00011;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00012;
(* keep = "true" *) logic data_valid_00012;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00013;
(* keep = "true" *) logic data_valid_00013;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00014;
(* keep = "true" *) logic data_valid_00014;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00015;
(* keep = "true" *) logic data_valid_00015;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00016;
(* keep = "true" *) logic data_valid_00016;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00017;
(* keep = "true" *) logic data_valid_00017;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00018;
(* keep = "true" *) logic data_valid_00018;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00019;
(* keep = "true" *) logic data_valid_00019;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00020;
(* keep = "true" *) logic data_valid_00020;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00021;
(* keep = "true" *) logic data_valid_00021;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00022;
(* keep = "true" *) logic data_valid_00022;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00023;
(* keep = "true" *) logic data_valid_00023;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00024;
(* keep = "true" *) logic data_valid_00024;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00025;
(* keep = "true" *) logic data_valid_00025;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00026;
(* keep = "true" *) logic data_valid_00026;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00027;
(* keep = "true" *) logic data_valid_00027;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00028;
(* keep = "true" *) logic data_valid_00028;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00029;
(* keep = "true" *) logic data_valid_00029;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00030;
(* keep = "true" *) logic data_valid_00030;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00031;
(* keep = "true" *) logic data_valid_00031;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00032;
(* keep = "true" *) logic data_valid_00032;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00033;
(* keep = "true" *) logic data_valid_00033;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00034;
(* keep = "true" *) logic data_valid_00034;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00035;
(* keep = "true" *) logic data_valid_00035;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00036;
(* keep = "true" *) logic data_valid_00036;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00037;
(* keep = "true" *) logic data_valid_00037;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00038;
(* keep = "true" *) logic data_valid_00038;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00039;
(* keep = "true" *) logic data_valid_00039;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00040;
(* keep = "true" *) logic data_valid_00040;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00041;
(* keep = "true" *) logic data_valid_00041;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00042;
(* keep = "true" *) logic data_valid_00042;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00043;
(* keep = "true" *) logic data_valid_00043;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00044;
(* keep = "true" *) logic data_valid_00044;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00045;
(* keep = "true" *) logic data_valid_00045;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00046;
(* keep = "true" *) logic data_valid_00046;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00047;
(* keep = "true" *) logic data_valid_00047;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00048;
(* keep = "true" *) logic data_valid_00048;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00049;
(* keep = "true" *) logic data_valid_00049;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00050;
(* keep = "true" *) logic data_valid_00050;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00051;
(* keep = "true" *) logic data_valid_00051;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00052;
(* keep = "true" *) logic data_valid_00052;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00053;
(* keep = "true" *) logic data_valid_00053;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00054;
(* keep = "true" *) logic data_valid_00054;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00055;
(* keep = "true" *) logic data_valid_00055;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00056;
(* keep = "true" *) logic data_valid_00056;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] rsData_00057;
(* keep = "true" *) logic data_valid_00057;

(* keep = "true" *)   logic [4-1:0] PARAM_t_lower;
(* keep = "true" *)   logic [5-1:0] PARAM_t2_lower;
(* keep = "true" *)   logic rs_encoder_start;


/* verilator lint_off UNUSED */
//BEGIN:
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] ecc_00000;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] ecc_00001;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] ecc_00002;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] ecc_00003;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] ecc_00004;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] ecc_00005;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] ecc_00006;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] ecc_00007;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] ecc_00008;
(* keep = "true" *) (* dont_touch = "true" *)  logic [PARAM_w-1:0] ecc_00009;
//END:
(* keep = "true" *) logic ecc_valid;
/* verilator lint_on UNUSED */

(* keep = "true" *) logic rstn;
(* keep = "true" *) logic clr;
/* verilator lint_on UNDRIVEN */



endinterface


(* keep_hierarchy = "yes" *) (* keep = "true" *) module  sntc_rs_encode_wrap #(
 parameter  PARAM_m = 6,
 parameter  PARAM_n = 63,
 parameter  PARAM_reduced_n = 63,
 parameter  PARAM_k = 53,
 parameter  PARAM_t = 5,
 parameter  PARAM_t2 = 10,
 parameter  PARAM_d = 11,
 parameter  PARAM_w = 6,
 parameter  PARAM_parNum = 58
) (

input wire in_clk
);




(* keep_hierarchy = "yes" *) (* keep = "true" *) sntc_rs_encode sntc_rs_encode_U
 (

.bb0(sntc_rs_encode_if_U.bb0),
.rsData_00000(sntc_rs_encode_if_U.rsData_00000),
.data_valid_00000(sntc_rs_encode_if_U.data_valid_00000),
.rsData_00001(sntc_rs_encode_if_U.rsData_00001),
.data_valid_00001(sntc_rs_encode_if_U.data_valid_00001),
.rsData_00002(sntc_rs_encode_if_U.rsData_00002),
.data_valid_00002(sntc_rs_encode_if_U.data_valid_00002),
.rsData_00003(sntc_rs_encode_if_U.rsData_00003),
.data_valid_00003(sntc_rs_encode_if_U.data_valid_00003),
.rsData_00004(sntc_rs_encode_if_U.rsData_00004),
.data_valid_00004(sntc_rs_encode_if_U.data_valid_00004),
.rsData_00005(sntc_rs_encode_if_U.rsData_00005),
.data_valid_00005(sntc_rs_encode_if_U.data_valid_00005),
.rsData_00006(sntc_rs_encode_if_U.rsData_00006),
.data_valid_00006(sntc_rs_encode_if_U.data_valid_00006),
.rsData_00007(sntc_rs_encode_if_U.rsData_00007),
.data_valid_00007(sntc_rs_encode_if_U.data_valid_00007),
.rsData_00008(sntc_rs_encode_if_U.rsData_00008),
.data_valid_00008(sntc_rs_encode_if_U.data_valid_00008),
.rsData_00009(sntc_rs_encode_if_U.rsData_00009),
.data_valid_00009(sntc_rs_encode_if_U.data_valid_00009),
.rsData_00010(sntc_rs_encode_if_U.rsData_00010),
.data_valid_00010(sntc_rs_encode_if_U.data_valid_00010),
.rsData_00011(sntc_rs_encode_if_U.rsData_00011),
.data_valid_00011(sntc_rs_encode_if_U.data_valid_00011),
.rsData_00012(sntc_rs_encode_if_U.rsData_00012),
.data_valid_00012(sntc_rs_encode_if_U.data_valid_00012),
.rsData_00013(sntc_rs_encode_if_U.rsData_00013),
.data_valid_00013(sntc_rs_encode_if_U.data_valid_00013),
.rsData_00014(sntc_rs_encode_if_U.rsData_00014),
.data_valid_00014(sntc_rs_encode_if_U.data_valid_00014),
.rsData_00015(sntc_rs_encode_if_U.rsData_00015),
.data_valid_00015(sntc_rs_encode_if_U.data_valid_00015),
.rsData_00016(sntc_rs_encode_if_U.rsData_00016),
.data_valid_00016(sntc_rs_encode_if_U.data_valid_00016),
.rsData_00017(sntc_rs_encode_if_U.rsData_00017),
.data_valid_00017(sntc_rs_encode_if_U.data_valid_00017),
.rsData_00018(sntc_rs_encode_if_U.rsData_00018),
.data_valid_00018(sntc_rs_encode_if_U.data_valid_00018),
.rsData_00019(sntc_rs_encode_if_U.rsData_00019),
.data_valid_00019(sntc_rs_encode_if_U.data_valid_00019),
.rsData_00020(sntc_rs_encode_if_U.rsData_00020),
.data_valid_00020(sntc_rs_encode_if_U.data_valid_00020),
.rsData_00021(sntc_rs_encode_if_U.rsData_00021),
.data_valid_00021(sntc_rs_encode_if_U.data_valid_00021),
.rsData_00022(sntc_rs_encode_if_U.rsData_00022),
.data_valid_00022(sntc_rs_encode_if_U.data_valid_00022),
.rsData_00023(sntc_rs_encode_if_U.rsData_00023),
.data_valid_00023(sntc_rs_encode_if_U.data_valid_00023),
.rsData_00024(sntc_rs_encode_if_U.rsData_00024),
.data_valid_00024(sntc_rs_encode_if_U.data_valid_00024),
.rsData_00025(sntc_rs_encode_if_U.rsData_00025),
.data_valid_00025(sntc_rs_encode_if_U.data_valid_00025),
.rsData_00026(sntc_rs_encode_if_U.rsData_00026),
.data_valid_00026(sntc_rs_encode_if_U.data_valid_00026),
.rsData_00027(sntc_rs_encode_if_U.rsData_00027),
.data_valid_00027(sntc_rs_encode_if_U.data_valid_00027),
.rsData_00028(sntc_rs_encode_if_U.rsData_00028),
.data_valid_00028(sntc_rs_encode_if_U.data_valid_00028),
.rsData_00029(sntc_rs_encode_if_U.rsData_00029),
.data_valid_00029(sntc_rs_encode_if_U.data_valid_00029),
.rsData_00030(sntc_rs_encode_if_U.rsData_00030),
.data_valid_00030(sntc_rs_encode_if_U.data_valid_00030),
.rsData_00031(sntc_rs_encode_if_U.rsData_00031),
.data_valid_00031(sntc_rs_encode_if_U.data_valid_00031),
.rsData_00032(sntc_rs_encode_if_U.rsData_00032),
.data_valid_00032(sntc_rs_encode_if_U.data_valid_00032),
.rsData_00033(sntc_rs_encode_if_U.rsData_00033),
.data_valid_00033(sntc_rs_encode_if_U.data_valid_00033),
.rsData_00034(sntc_rs_encode_if_U.rsData_00034),
.data_valid_00034(sntc_rs_encode_if_U.data_valid_00034),
.rsData_00035(sntc_rs_encode_if_U.rsData_00035),
.data_valid_00035(sntc_rs_encode_if_U.data_valid_00035),
.rsData_00036(sntc_rs_encode_if_U.rsData_00036),
.data_valid_00036(sntc_rs_encode_if_U.data_valid_00036),
.rsData_00037(sntc_rs_encode_if_U.rsData_00037),
.data_valid_00037(sntc_rs_encode_if_U.data_valid_00037),
.rsData_00038(sntc_rs_encode_if_U.rsData_00038),
.data_valid_00038(sntc_rs_encode_if_U.data_valid_00038),
.rsData_00039(sntc_rs_encode_if_U.rsData_00039),
.data_valid_00039(sntc_rs_encode_if_U.data_valid_00039),
.rsData_00040(sntc_rs_encode_if_U.rsData_00040),
.data_valid_00040(sntc_rs_encode_if_U.data_valid_00040),
.rsData_00041(sntc_rs_encode_if_U.rsData_00041),
.data_valid_00041(sntc_rs_encode_if_U.data_valid_00041),
.rsData_00042(sntc_rs_encode_if_U.rsData_00042),
.data_valid_00042(sntc_rs_encode_if_U.data_valid_00042),
.rsData_00043(sntc_rs_encode_if_U.rsData_00043),
.data_valid_00043(sntc_rs_encode_if_U.data_valid_00043),
.rsData_00044(sntc_rs_encode_if_U.rsData_00044),
.data_valid_00044(sntc_rs_encode_if_U.data_valid_00044),
.rsData_00045(sntc_rs_encode_if_U.rsData_00045),
.data_valid_00045(sntc_rs_encode_if_U.data_valid_00045),
.rsData_00046(sntc_rs_encode_if_U.rsData_00046),
.data_valid_00046(sntc_rs_encode_if_U.data_valid_00046),
.rsData_00047(sntc_rs_encode_if_U.rsData_00047),
.data_valid_00047(sntc_rs_encode_if_U.data_valid_00047),
.rsData_00048(sntc_rs_encode_if_U.rsData_00048),
.data_valid_00048(sntc_rs_encode_if_U.data_valid_00048),
.rsData_00049(sntc_rs_encode_if_U.rsData_00049),
.data_valid_00049(sntc_rs_encode_if_U.data_valid_00049),
.rsData_00050(sntc_rs_encode_if_U.rsData_00050),
.data_valid_00050(sntc_rs_encode_if_U.data_valid_00050),
.rsData_00051(sntc_rs_encode_if_U.rsData_00051),
.data_valid_00051(sntc_rs_encode_if_U.data_valid_00051),
.rsData_00052(sntc_rs_encode_if_U.rsData_00052),
.data_valid_00052(sntc_rs_encode_if_U.data_valid_00052),
.rsData_00053(sntc_rs_encode_if_U.rsData_00053),
.data_valid_00053(sntc_rs_encode_if_U.data_valid_00053),
.rsData_00054(sntc_rs_encode_if_U.rsData_00054),
.data_valid_00054(sntc_rs_encode_if_U.data_valid_00054),
.rsData_00055(sntc_rs_encode_if_U.rsData_00055),
.data_valid_00055(sntc_rs_encode_if_U.data_valid_00055),
.rsData_00056(sntc_rs_encode_if_U.rsData_00056),
.data_valid_00056(sntc_rs_encode_if_U.data_valid_00056),
.rsData_00057(sntc_rs_encode_if_U.rsData_00057),
.data_valid_00057(sntc_rs_encode_if_U.data_valid_00057),




.PARAM_t_lower(sntc_rs_encode_if_U.PARAM_t_lower),
.PARAM_t2_lower(sntc_rs_encode_if_U.PARAM_t2_lower),
//BEGIN:
.ecc_00000(sntc_rs_encode_if_U.ecc_00000),
.ecc_00001(sntc_rs_encode_if_U.ecc_00001),
.ecc_00002(sntc_rs_encode_if_U.ecc_00002),
.ecc_00003(sntc_rs_encode_if_U.ecc_00003),
.ecc_00004(sntc_rs_encode_if_U.ecc_00004),
.ecc_00005(sntc_rs_encode_if_U.ecc_00005),
.ecc_00006(sntc_rs_encode_if_U.ecc_00006),
.ecc_00007(sntc_rs_encode_if_U.ecc_00007),
.ecc_00008(sntc_rs_encode_if_U.ecc_00008),
.ecc_00009(sntc_rs_encode_if_U.ecc_00009),
//END:

.ecc_valid(sntc_rs_encode_if_U.ecc_valid),

.rstn(sntc_rs_encode_if_U.rstn),
.clr(sntc_rs_encode_if_U.clr),

.clk(in_clk)
);

sntc_rs_encode_if sntc_rs_encode_if_U(in_clk);





endmodule



// CCCC primitive_P(x) = 1100001// CCCC 
// CCCC Pass Enter code length:63 (31 < length <= 63): 
