//#;; DO NOT EDIT THIS FILE
/*ENCRYPT_ME*/
////////////////////////////////////////////////////////////////////////////////
//# Copyright (c) 2018 Secantec
//# No Permission to modify and distribute this program
//# even if this copyright message remains unaltered.
//#
//# Author: Secantec 27 April, 2018
//# $Id: $//#
//# Revision History
//#       MM      17  April, 2018    Initial release
//#
////////////////////////////////////////////////////////////////////////////////

// /bin/rm -rf *simv* *csrc* ; perl vpp.pl -perl sntc_berlekamp.1.sv > sntc_berlekamp.1.vpp.sv ; vcs -sverilog -R -debug_all sntc_berlekamp.1.vpp.sv -l sntc_berlekamp.1.vpp.sv.log

 /*ENCRYPT_ME*/

//final:MYSEED:600500
//final:PARAM_m:6
//final:PARAM_t:5

// pRev[0]:1
// pRev[1]:0
// pRev[2]:0
// pRev[3]:0
// pRev[4]:0
// pRev[5]:1
// POLY perl :0x3
// pRev[0]:1
// pRev[1]:0
// pRev[2]:0
// pRev[3]:0
// pRev[4]:0
// pRev[5]:1
// POLY perl :0x3
`define d_u_w 3
`define d_m 6
`define PARAM_par_w 6

/* verilator lint_off DECLFILENAME */

(* keep_hierarchy = "yes" *) (* keep = "true" *) (* dont_touch = "true" *)  interface sntc_rs_decoder_if(
/* verilator lint_off UNUSED */
                input wire clk
/* verilator lint_on UNUSED */
                );
 parameter  PARAM_m = 6;
 parameter  PARAM_nn1 = 63;
 parameter  PARAM_reduced_n = 63;
 parameter  PARAM_k = 53;
 parameter  PARAM_t = 5;
 parameter  PARAM_t2 = 10;
 parameter  PARAM_d = 11;
 parameter  PARAM_count_w = $clog2(63+1);
 parameter  PARAM_w = 6;

/* verilator lint_off UNDRIVEN */
(* keep = "true" *) logic [6-1:0] bb0;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00000;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00001;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00002;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00003;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00004;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00005;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00006;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00007;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00008;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00009;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00010;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00011;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00012;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00013;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00014;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00015;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00016;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00017;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00018;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00019;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00020;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00021;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00022;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00023;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00024;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00025;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00026;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00027;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00028;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00029;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00030;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00031;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00032;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00033;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00034;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00035;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00036;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00037;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00038;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00039;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00040;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00041;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00042;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00043;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00044;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00045;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00046;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00047;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00048;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00049;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00050;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00051;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00052;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00053;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00054;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00055;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00056;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] recd_data_00057;
/* verilator lint_on UNDRIVEN */


/* verilator lint_off UNUSED */
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00000;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00001;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00002;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00003;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00004;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00005;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00006;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00007;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00008;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00009;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00010;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00011;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00012;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00013;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00014;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00015;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00016;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00017;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00018;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00019;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00020;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00021;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00022;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00023;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00024;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00025;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00026;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00027;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00028;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00029;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00030;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00031;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00032;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00033;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00034;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00035;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00036;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00037;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00038;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00039;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00040;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00041;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00042;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00043;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00044;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00045;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00046;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00047;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00048;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00049;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00050;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00051;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00052;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00053;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00054;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00055;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00056;
(* keep = "true" *)  (* dont_touch = "true" *)   logic [PARAM_w-1:0] corrected_data_00057;
/* verilator lint_on UNUSED */

logic [PARAM_w-1:0] xor_error_loc_out_00000;
logic [PARAM_w-1:0] xor_error_loc_out_00001;
logic [PARAM_w-1:0] xor_error_loc_out_00002;
logic [PARAM_w-1:0] xor_error_loc_out_00003;
logic [PARAM_w-1:0] xor_error_loc_out_00004;

logic [31:0] token_i;
logic [31:0] token_o;

/* verilator lint_off UNDRIVEN */
(* keep = "true" *)   logic [4-1:0] PARAM_t_lower;
(* keep = "true" *)   logic [5-1:0] PARAM_t2_lower;
/* verilator lint_on UNDRIVEN */
/* verilator lint_off UNDRIVEN */
(* keep = "true" *)   logic rs_code_start;
(* keep = "true" *)   logic rs_decode_berk_start;
/* verilator lint_on UNDRIVEN */
/* verilator lint_off UNUSED */
(* keep = "true" *)   logic rs_code_valid;
/* verilator lint_on UNUSED */
/* verilator lint_off UNDRIVEN */
/* verilator lint_off UNUSED */
(* keep = "true" *)   logic rs_decoder_start;
(* keep = "true" *)   logic [1:0] uncorrectable;
(* keep = "true" *)   logic [1:0] uncorrectable_out;
(* keep = "true" *)   logic [PARAM_count_w-1:0] err_count;
(* keep = "true" *)   logic berk_valid;
(* keep = "true" *)   logic chien_valid;
(* keep = "true" *)   logic forney_valid;
(* keep = "true" *)   logic syn_error;
(* keep = "true" *)   logic [PARAM_w-1:0] ll_uuu_p1_out;
(* keep = "true" *)   logic rstn;
(* keep = "true" *)   logic clr;
/* verilator lint_on UNUSED */





endinterface

(* keep_hierarchy = "yes" *) (* keep = "true" *) module  sntc_rs_decoder_wrap #(
 parameter  PARAM_m = 6,
 parameter  PARAM_nn1 = 63,
 parameter  PARAM_reduced_n = 63,
 parameter  PARAM_k = 53,
 parameter  PARAM_t = 5,
 parameter  PARAM_t2 = 10,
 parameter  PARAM_d = 11,
 parameter  PARAM_count_w = $clog2(63+1),
 parameter  PARAM_w = 6
) (

 input wire in_clk
);


(* keep_hierarchy = "yes" *)  (* keep = "true" *) sntc_rs_decoder sntc_rs_decoder_U(
.bb0(sntc_rs_decoder_if_U.bb0),
.recd_data_00000(sntc_rs_decoder_if_U.recd_data_00000),
.recd_data_00001(sntc_rs_decoder_if_U.recd_data_00001),
.recd_data_00002(sntc_rs_decoder_if_U.recd_data_00002),
.recd_data_00003(sntc_rs_decoder_if_U.recd_data_00003),
.recd_data_00004(sntc_rs_decoder_if_U.recd_data_00004),
.recd_data_00005(sntc_rs_decoder_if_U.recd_data_00005),
.recd_data_00006(sntc_rs_decoder_if_U.recd_data_00006),
.recd_data_00007(sntc_rs_decoder_if_U.recd_data_00007),
.recd_data_00008(sntc_rs_decoder_if_U.recd_data_00008),
.recd_data_00009(sntc_rs_decoder_if_U.recd_data_00009),
.recd_data_00010(sntc_rs_decoder_if_U.recd_data_00010),
.recd_data_00011(sntc_rs_decoder_if_U.recd_data_00011),
.recd_data_00012(sntc_rs_decoder_if_U.recd_data_00012),
.recd_data_00013(sntc_rs_decoder_if_U.recd_data_00013),
.recd_data_00014(sntc_rs_decoder_if_U.recd_data_00014),
.recd_data_00015(sntc_rs_decoder_if_U.recd_data_00015),
.recd_data_00016(sntc_rs_decoder_if_U.recd_data_00016),
.recd_data_00017(sntc_rs_decoder_if_U.recd_data_00017),
.recd_data_00018(sntc_rs_decoder_if_U.recd_data_00018),
.recd_data_00019(sntc_rs_decoder_if_U.recd_data_00019),
.recd_data_00020(sntc_rs_decoder_if_U.recd_data_00020),
.recd_data_00021(sntc_rs_decoder_if_U.recd_data_00021),
.recd_data_00022(sntc_rs_decoder_if_U.recd_data_00022),
.recd_data_00023(sntc_rs_decoder_if_U.recd_data_00023),
.recd_data_00024(sntc_rs_decoder_if_U.recd_data_00024),
.recd_data_00025(sntc_rs_decoder_if_U.recd_data_00025),
.recd_data_00026(sntc_rs_decoder_if_U.recd_data_00026),
.recd_data_00027(sntc_rs_decoder_if_U.recd_data_00027),
.recd_data_00028(sntc_rs_decoder_if_U.recd_data_00028),
.recd_data_00029(sntc_rs_decoder_if_U.recd_data_00029),
.recd_data_00030(sntc_rs_decoder_if_U.recd_data_00030),
.recd_data_00031(sntc_rs_decoder_if_U.recd_data_00031),
.recd_data_00032(sntc_rs_decoder_if_U.recd_data_00032),
.recd_data_00033(sntc_rs_decoder_if_U.recd_data_00033),
.recd_data_00034(sntc_rs_decoder_if_U.recd_data_00034),
.recd_data_00035(sntc_rs_decoder_if_U.recd_data_00035),
.recd_data_00036(sntc_rs_decoder_if_U.recd_data_00036),
.recd_data_00037(sntc_rs_decoder_if_U.recd_data_00037),
.recd_data_00038(sntc_rs_decoder_if_U.recd_data_00038),
.recd_data_00039(sntc_rs_decoder_if_U.recd_data_00039),
.recd_data_00040(sntc_rs_decoder_if_U.recd_data_00040),
.recd_data_00041(sntc_rs_decoder_if_U.recd_data_00041),
.recd_data_00042(sntc_rs_decoder_if_U.recd_data_00042),
.recd_data_00043(sntc_rs_decoder_if_U.recd_data_00043),
.recd_data_00044(sntc_rs_decoder_if_U.recd_data_00044),
.recd_data_00045(sntc_rs_decoder_if_U.recd_data_00045),
.recd_data_00046(sntc_rs_decoder_if_U.recd_data_00046),
.recd_data_00047(sntc_rs_decoder_if_U.recd_data_00047),
.recd_data_00048(sntc_rs_decoder_if_U.recd_data_00048),
.recd_data_00049(sntc_rs_decoder_if_U.recd_data_00049),
.recd_data_00050(sntc_rs_decoder_if_U.recd_data_00050),
.recd_data_00051(sntc_rs_decoder_if_U.recd_data_00051),
.recd_data_00052(sntc_rs_decoder_if_U.recd_data_00052),
.recd_data_00053(sntc_rs_decoder_if_U.recd_data_00053),
.recd_data_00054(sntc_rs_decoder_if_U.recd_data_00054),
.recd_data_00055(sntc_rs_decoder_if_U.recd_data_00055),
.recd_data_00056(sntc_rs_decoder_if_U.recd_data_00056),
.recd_data_00057(sntc_rs_decoder_if_U.recd_data_00057),


.token_i(sntc_rs_decoder_if_U.token_i),
.token_o(sntc_rs_decoder_if_U.token_o),

.corrected_data_00000(sntc_rs_decoder_if_U.corrected_data_00000),
.corrected_data_00001(sntc_rs_decoder_if_U.corrected_data_00001),
.corrected_data_00002(sntc_rs_decoder_if_U.corrected_data_00002),
.corrected_data_00003(sntc_rs_decoder_if_U.corrected_data_00003),
.corrected_data_00004(sntc_rs_decoder_if_U.corrected_data_00004),
.corrected_data_00005(sntc_rs_decoder_if_U.corrected_data_00005),
.corrected_data_00006(sntc_rs_decoder_if_U.corrected_data_00006),
.corrected_data_00007(sntc_rs_decoder_if_U.corrected_data_00007),
.corrected_data_00008(sntc_rs_decoder_if_U.corrected_data_00008),
.corrected_data_00009(sntc_rs_decoder_if_U.corrected_data_00009),
.corrected_data_00010(sntc_rs_decoder_if_U.corrected_data_00010),
.corrected_data_00011(sntc_rs_decoder_if_U.corrected_data_00011),
.corrected_data_00012(sntc_rs_decoder_if_U.corrected_data_00012),
.corrected_data_00013(sntc_rs_decoder_if_U.corrected_data_00013),
.corrected_data_00014(sntc_rs_decoder_if_U.corrected_data_00014),
.corrected_data_00015(sntc_rs_decoder_if_U.corrected_data_00015),
.corrected_data_00016(sntc_rs_decoder_if_U.corrected_data_00016),
.corrected_data_00017(sntc_rs_decoder_if_U.corrected_data_00017),
.corrected_data_00018(sntc_rs_decoder_if_U.corrected_data_00018),
.corrected_data_00019(sntc_rs_decoder_if_U.corrected_data_00019),
.corrected_data_00020(sntc_rs_decoder_if_U.corrected_data_00020),
.corrected_data_00021(sntc_rs_decoder_if_U.corrected_data_00021),
.corrected_data_00022(sntc_rs_decoder_if_U.corrected_data_00022),
.corrected_data_00023(sntc_rs_decoder_if_U.corrected_data_00023),
.corrected_data_00024(sntc_rs_decoder_if_U.corrected_data_00024),
.corrected_data_00025(sntc_rs_decoder_if_U.corrected_data_00025),
.corrected_data_00026(sntc_rs_decoder_if_U.corrected_data_00026),
.corrected_data_00027(sntc_rs_decoder_if_U.corrected_data_00027),
.corrected_data_00028(sntc_rs_decoder_if_U.corrected_data_00028),
.corrected_data_00029(sntc_rs_decoder_if_U.corrected_data_00029),
.corrected_data_00030(sntc_rs_decoder_if_U.corrected_data_00030),
.corrected_data_00031(sntc_rs_decoder_if_U.corrected_data_00031),
.corrected_data_00032(sntc_rs_decoder_if_U.corrected_data_00032),
.corrected_data_00033(sntc_rs_decoder_if_U.corrected_data_00033),
.corrected_data_00034(sntc_rs_decoder_if_U.corrected_data_00034),
.corrected_data_00035(sntc_rs_decoder_if_U.corrected_data_00035),
.corrected_data_00036(sntc_rs_decoder_if_U.corrected_data_00036),
.corrected_data_00037(sntc_rs_decoder_if_U.corrected_data_00037),
.corrected_data_00038(sntc_rs_decoder_if_U.corrected_data_00038),
.corrected_data_00039(sntc_rs_decoder_if_U.corrected_data_00039),
.corrected_data_00040(sntc_rs_decoder_if_U.corrected_data_00040),
.corrected_data_00041(sntc_rs_decoder_if_U.corrected_data_00041),
.corrected_data_00042(sntc_rs_decoder_if_U.corrected_data_00042),
.corrected_data_00043(sntc_rs_decoder_if_U.corrected_data_00043),
.corrected_data_00044(sntc_rs_decoder_if_U.corrected_data_00044),
.corrected_data_00045(sntc_rs_decoder_if_U.corrected_data_00045),
.corrected_data_00046(sntc_rs_decoder_if_U.corrected_data_00046),
.corrected_data_00047(sntc_rs_decoder_if_U.corrected_data_00047),
.corrected_data_00048(sntc_rs_decoder_if_U.corrected_data_00048),
.corrected_data_00049(sntc_rs_decoder_if_U.corrected_data_00049),
.corrected_data_00050(sntc_rs_decoder_if_U.corrected_data_00050),
.corrected_data_00051(sntc_rs_decoder_if_U.corrected_data_00051),
.corrected_data_00052(sntc_rs_decoder_if_U.corrected_data_00052),
.corrected_data_00053(sntc_rs_decoder_if_U.corrected_data_00053),
.corrected_data_00054(sntc_rs_decoder_if_U.corrected_data_00054),
.corrected_data_00055(sntc_rs_decoder_if_U.corrected_data_00055),
.corrected_data_00056(sntc_rs_decoder_if_U.corrected_data_00056),
.corrected_data_00057(sntc_rs_decoder_if_U.corrected_data_00057),

.xor_error_loc_out_00000( sntc_rs_decoder_if_U.xor_error_loc_out_00000 ),
.xor_error_loc_out_00001( sntc_rs_decoder_if_U.xor_error_loc_out_00001 ),
.xor_error_loc_out_00002( sntc_rs_decoder_if_U.xor_error_loc_out_00002 ),
.xor_error_loc_out_00003( sntc_rs_decoder_if_U.xor_error_loc_out_00003 ),
.xor_error_loc_out_00004( sntc_rs_decoder_if_U.xor_error_loc_out_00004 ),

.PARAM_t_lower(sntc_rs_decoder_if_U.PARAM_t_lower),
.PARAM_t2_lower(sntc_rs_decoder_if_U.PARAM_t2_lower),
.rs_code_start(sntc_rs_decoder_if_U.rs_code_start),
.rs_code_valid(sntc_rs_decoder_if_U.rs_code_valid),
.rs_decode_berk_start(sntc_rs_decoder_if_U.rs_decode_berk_start),
.uncorrectable_out(sntc_rs_decoder_if_U.uncorrectable_out),
.uncorrectable(sntc_rs_decoder_if_U.uncorrectable),
.err_count(sntc_rs_decoder_if_U.err_count),
.rs_decoder_start(sntc_rs_decoder_if_U.rs_decoder_start),
.berk_valid(sntc_rs_decoder_if_U.berk_valid),
.chien_valid(sntc_rs_decoder_if_U.chien_valid),
.forney_valid(sntc_rs_decoder_if_U.forney_valid),
.syn_error(sntc_rs_decoder_if_U.syn_error),
.ll_uuu_p1_out(sntc_rs_decoder_if_U.ll_uuu_p1_out),

.rstn(sntc_rs_decoder_if_U.rstn),
.clr(sntc_rs_decoder_if_U.clr),
.clk(in_clk)
);

sntc_rs_decoder_if sntc_rs_decoder_if_U(in_clk);

endmodule

