//#;; DO NOT EDIT THIS FILE
/*ENCRYPT_ME*/
////////////////////////////////////////////////////////////////////////////////
//# Copyright (c) 2018 Secantec
//# No Permission to modify and distribute this program
//# even if this copyright message remains unaltered.
//#
//# Author: Secantec 27 April, 2018
//# $Id: $//#
//# Revision History
//#       MM      17  April, 2018    Initial release
//#
////////////////////////////////////////////////////////////////////////////////

 /*ENCRYPT_ME*/


//final:MYSEED:600500
//final:PARAM_m:6
//final:PARAM_t:5

// pRev[0]:1
// pRev[1]:0
// pRev[2]:0
// pRev[3]:0
// pRev[4]:0
// pRev[5]:1
// POLY perl :0x3
// pRev[0]:1
// pRev[1]:0
// pRev[2]:0
// pRev[3]:0
// pRev[4]:0
// pRev[5]:1
// POLY perl :0x3

//  PARAM_length 63
//  1



















(* keep_hierarchy = "yes" *) (* keep = "true" *) module ChiencrcMult__00000(
                   prdct_z,
                   fact_a
                  );


  parameter PARAM_POLY_WIDTH = 6;
  parameter PARAM_PRIMITIVE_POLY = 3;
    output [PARAM_POLY_WIDTH-1:0] prdct_z;
    input [PARAM_POLY_WIDTH-1:0] fact_a;
    wire [PARAM_POLY_WIDTH-1:0] fact_b = 6'd2;


//@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # 

endmodule
(* keep_hierarchy = "yes" *) (* keep = "true" *) module ChiencrcMult__00001(
                   prdct_z,
                   fact_a
                  );


  parameter PARAM_POLY_WIDTH = 6;
  parameter PARAM_PRIMITIVE_POLY = 3;
    output [PARAM_POLY_WIDTH-1:0] prdct_z;
    input [PARAM_POLY_WIDTH-1:0] fact_a;
    wire [PARAM_POLY_WIDTH-1:0] fact_b = 6'd4;


//@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # 

endmodule
(* keep_hierarchy = "yes" *) (* keep = "true" *) module ChiencrcMult__00002(
                   prdct_z,
                   fact_a
                  );


  parameter PARAM_POLY_WIDTH = 6;
  parameter PARAM_PRIMITIVE_POLY = 3;
    output [PARAM_POLY_WIDTH-1:0] prdct_z;
    input [PARAM_POLY_WIDTH-1:0] fact_a;
    wire [PARAM_POLY_WIDTH-1:0] fact_b = 6'd16;


//@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # 

endmodule
(* keep_hierarchy = "yes" *) (* keep = "true" *) module ChiencrcMult__00003(
                   prdct_z,
                   fact_a
                  );


  parameter PARAM_POLY_WIDTH = 6;
  parameter PARAM_PRIMITIVE_POLY = 3;
    output [PARAM_POLY_WIDTH-1:0] prdct_z;
    input [PARAM_POLY_WIDTH-1:0] fact_a;
    wire [PARAM_POLY_WIDTH-1:0] fact_b = 6'd12;


//@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # 

endmodule
(* keep_hierarchy = "yes" *) (* keep = "true" *) module ChiencrcMult__00004(
                   prdct_z,
                   fact_a
                  );


  parameter PARAM_POLY_WIDTH = 6;
  parameter PARAM_PRIMITIVE_POLY = 3;
    output [PARAM_POLY_WIDTH-1:0] prdct_z;
    input [PARAM_POLY_WIDTH-1:0] fact_a;
    wire [PARAM_POLY_WIDTH-1:0] fact_b = 6'd19;


//@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # 

endmodule
(* keep_hierarchy = "yes" *) (* keep = "true" *) module ChiencrcMult__00005(
                   prdct_z,
                   fact_a
                  );


  parameter PARAM_POLY_WIDTH = 6;
  parameter PARAM_PRIMITIVE_POLY = 3;
    output [PARAM_POLY_WIDTH-1:0] prdct_z;
    input [PARAM_POLY_WIDTH-1:0] fact_a;
    wire [PARAM_POLY_WIDTH-1:0] fact_b = 6'd9;


//@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # //@ # 

endmodule


//END:



// CCCC primitive_P(x) = 1100001// CCCC 
// CCCC Pass Enter code length:59 (31 < length <= 63): 
