//#;; DO NOT EDIT THIS FILE
/*ENCRYPT_ME*/
////////////////////////////////////////////////////////////////////////////////
//# Copyright (c) 2018 Secantec
//# No Permission to modify and distribute this program
//# even if this copyright message remains unaltered.
//#
//# Author: Secantec 27 April, 2018
//# $Id: $//#
//# Revision History
//#       MM      17  April, 2018    Initial release
//#
////////////////////////////////////////////////////////////////////////////////

 /*ENCRYPT_ME*/

//final:MYSEED:600500
//final:PARAM_m:6
//final:PARAM_t:5

// pRev[0]:1
// pRev[1]:0
// pRev[2]:0
// pRev[3]:0
// pRev[4]:0
// pRev[5]:1
// POLY perl :0x3
// pRev[0]:1
// pRev[1]:0
// pRev[2]:0
// pRev[3]:0
// pRev[4]:0
// pRev[5]:1
// POLY perl :0x3
//  PARAM_length 63
//  1


/* verilator lint_off DECLFILENAME */
(* keep_hierarchy = "yes" *) (* keep = "true" *) module  sntc_chien#(
 parameter PARAM_m = 6,
 parameter PARAM_nn1 = 63,
 parameter PARAM_reduced_n = 63,
 parameter PARAM_t = 5,
 parameter PARAM_t2 = 10,
 parameter PARAM_d = 11,
 parameter PARAM_w = 6,
 parameter PARAM_width_w = $clog2(PARAM_nn1+1),
 parameter PARAM_count_w = $clog2(63+1),
 parameter PARAM_states = 5,
 parameter PARAM_par_chien = 63,
 parameter PARAM_par_w = $clog2(63+1),
 parameter PARAM_no_eras_w = $clog2(10+1)+1,
 parameter u_w = $clog2(PARAM_t2+1),
// u_w: 4  u_2w: 5
 parameter PARAM_states_w = $clog2(PARAM_states+1)
) (

input [PARAM_w-1:0] sigma_arr_i_00001,
input [PARAM_w-1:0] sigma_arr_i_00002,
input [PARAM_w-1:0] sigma_arr_i_00003,
input [PARAM_w-1:0] sigma_arr_i_00004,
input [PARAM_w-1:0] sigma_arr_i_00005,
input start,

output reg [PARAM_width_w-1:0] loc_err_00001,
output reg [PARAM_width_w-1:0] loc_err_00002,
output reg [PARAM_width_w-1:0] loc_err_00003,
output reg [PARAM_width_w-1:0] loc_err_00004,
output reg [PARAM_width_w-1:0] loc_err_00005,

output reg [PARAM_width_w-1:0] root_err_00001,
output reg [PARAM_width_w-1:0] root_err_00002,
output reg [PARAM_width_w-1:0] root_err_00003,
output reg [PARAM_width_w-1:0] root_err_00004,
output reg [PARAM_width_w-1:0] root_err_00005,

/* verilator lint_off UNUSED */
input wire [u_w-1:0] PARAM_t_lower,
input wire [u_w:0] PARAM_t2_lower,
/* verilator lint_on UNUSED */
input wire [PARAM_w-1:0] ll_uuu_p1,
output reg [PARAM_w-1:0] ll_uuu_p1_out,
input wire [PARAM_no_eras_w -1:0] no_eras,
output reg [PARAM_no_eras_w -1:0] no_eras_out,
input wire [32 -1:0] token,
output reg [32 -1:0] token_out,
output wire [PARAM_count_w-1:0] err_count,

output reg valid
/* verilator lint_off UNUSED */
,

input rstn,
input clr,

input clk
/* verilator lint_on UNUSED */
);



reg valid_d;
/* verilator lint_off UNUSED */
reg [2*2-1:0] serial_err_cnt;
/* verilator lint_on UNUSED */
reg [u_w-1:0] PARAM_t_lower_reg;


reg  [PARAM_par_w-1:0] second_cur_err_cnt_00000_00062;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00001_00000;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00002_00001;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00003_00002;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00004_00003;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00005_00004;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00006_00005;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00007_00006;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00008_00007;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00009_00008;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00010_00009;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00011_00010;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00012_00011;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00013_00012;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00014_00013;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00015_00014;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00016_00015;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00017_00016;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00018_00017;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00019_00018;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00020_00019;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00021_00020;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00022_00021;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00023_00022;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00024_00023;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00025_00024;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00026_00025;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00027_00026;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00028_00027;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00029_00028;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00030_00029;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00031_00030;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00032_00031;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00033_00032;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00034_00033;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00035_00034;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00036_00035;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00037_00036;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00038_00037;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00039_00038;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00040_00039;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00041_00040;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00042_00041;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00043_00042;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00044_00043;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00045_00044;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00046_00045;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00047_00046;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00048_00047;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00049_00048;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00050_00049;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00051_00050;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00052_00051;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00053_00052;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00054_00053;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00055_00054;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00056_00055;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00057_00056;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00058_00057;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00059_00058;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00060_00059;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00061_00060;
reg  [PARAM_par_w-1:0] second_cur_err_cnt_00062_00061;




reg [PARAM_width_w-1:0] reg_loc_err_00001;
reg [PARAM_width_w-1:0] reg_loc_err_00002;
reg [PARAM_width_w-1:0] reg_loc_err_00003;
reg [PARAM_width_w-1:0] reg_loc_err_00004;
reg [PARAM_width_w-1:0] reg_loc_err_00005;

reg [PARAM_width_w-1:0] reg_root_err_00001;
reg [PARAM_width_w-1:0] reg_root_err_00002;
reg [PARAM_width_w-1:0] reg_root_err_00003;
reg [PARAM_width_w-1:0] reg_root_err_00004;
reg [PARAM_width_w-1:0] reg_root_err_00005;



reg  clk_en_reg_00000;
reg  clk_en_reg_00001;
reg  clk_en_reg_00002;
reg  clk_en_reg_00003;
reg  clk_en_reg_00004;
reg  clk_en_reg_00005;
reg  clk_en_reg_00006;
reg  clk_en_reg_00007;
reg  clk_en_reg_00008;
reg  clk_en_reg_00009;
reg  clk_en_reg_00010;
reg  clk_en_reg_00011;
reg  clk_en_reg_00012;
reg  clk_en_reg_00013;
reg  clk_en_reg_00014;
reg  clk_en_reg_00015;
reg  clk_en_reg_00016;
reg  clk_en_reg_00017;
reg  clk_en_reg_00018;
reg  clk_en_reg_00019;
reg  clk_en_reg_00020;
reg  clk_en_reg_00021;
reg  clk_en_reg_00022;
reg  clk_en_reg_00023;
reg  clk_en_reg_00024;
reg  clk_en_reg_00025;
reg  clk_en_reg_00026;
reg  clk_en_reg_00027;
reg  clk_en_reg_00028;
reg  clk_en_reg_00029;
reg  clk_en_reg_00030;
reg  clk_en_reg_00031;
reg  clk_en_reg_00032;
reg  clk_en_reg_00033;
reg  clk_en_reg_00034;
reg  clk_en_reg_00035;
reg  clk_en_reg_00036;
reg  clk_en_reg_00037;
reg  clk_en_reg_00038;
reg  clk_en_reg_00039;
reg  clk_en_reg_00040;
reg  clk_en_reg_00041;
reg  clk_en_reg_00042;
reg  clk_en_reg_00043;
reg  clk_en_reg_00044;
reg  clk_en_reg_00045;
reg  clk_en_reg_00046;
reg  clk_en_reg_00047;
reg  clk_en_reg_00048;
reg  clk_en_reg_00049;
reg  clk_en_reg_00050;
reg  clk_en_reg_00051;
reg  clk_en_reg_00052;
reg  clk_en_reg_00053;
reg  clk_en_reg_00054;
reg  clk_en_reg_00055;
reg  clk_en_reg_00056;
reg  clk_en_reg_00057;
reg  clk_en_reg_00058;
reg  clk_en_reg_00059;
reg  clk_en_reg_00060;
reg  clk_en_reg_00061;
reg  clk_en_reg_00062;


reg [PARAM_width_w-1:0] cur_err_cnt;
reg total_valid;
reg total_valid_reg;
reg total_valid_reg_final;

/* verilator lint_off UNUSED */
 wire [PARAM_w-1:0] q_output_00000;
 wire [PARAM_w-1:0] q_output_00001;
 wire [PARAM_w-1:0] q_output_00002;
 wire [PARAM_w-1:0] q_output_00003;
 wire [PARAM_w-1:0] q_output_00004;
 wire [PARAM_w-1:0] q_output_00005;
 wire [PARAM_w-1:0] q_output_00006;
 wire [PARAM_w-1:0] q_output_00007;
 wire [PARAM_w-1:0] q_output_00008;
 wire [PARAM_w-1:0] q_output_00009;
 wire [PARAM_w-1:0] q_output_00010;
 wire [PARAM_w-1:0] q_output_00011;
 wire [PARAM_w-1:0] q_output_00012;
 wire [PARAM_w-1:0] q_output_00013;
 wire [PARAM_w-1:0] q_output_00014;
 wire [PARAM_w-1:0] q_output_00015;
 wire [PARAM_w-1:0] q_output_00016;
 wire [PARAM_w-1:0] q_output_00017;
 wire [PARAM_w-1:0] q_output_00018;
 wire [PARAM_w-1:0] q_output_00019;
 wire [PARAM_w-1:0] q_output_00020;
 wire [PARAM_w-1:0] q_output_00021;
 wire [PARAM_w-1:0] q_output_00022;
 wire [PARAM_w-1:0] q_output_00023;
 wire [PARAM_w-1:0] q_output_00024;
 wire [PARAM_w-1:0] q_output_00025;
 wire [PARAM_w-1:0] q_output_00026;
 wire [PARAM_w-1:0] q_output_00027;
 wire [PARAM_w-1:0] q_output_00028;
 wire [PARAM_w-1:0] q_output_00029;
 wire [PARAM_w-1:0] q_output_00030;
 wire [PARAM_w-1:0] q_output_00031;
 wire [PARAM_w-1:0] q_output_00032;
 wire [PARAM_w-1:0] q_output_00033;
 wire [PARAM_w-1:0] q_output_00034;
 wire [PARAM_w-1:0] q_output_00035;
 wire [PARAM_w-1:0] q_output_00036;
 wire [PARAM_w-1:0] q_output_00037;
 wire [PARAM_w-1:0] q_output_00038;
 wire [PARAM_w-1:0] q_output_00039;
 wire [PARAM_w-1:0] q_output_00040;
 wire [PARAM_w-1:0] q_output_00041;
 wire [PARAM_w-1:0] q_output_00042;
 wire [PARAM_w-1:0] q_output_00043;
 wire [PARAM_w-1:0] q_output_00044;
 wire [PARAM_w-1:0] q_output_00045;
 wire [PARAM_w-1:0] q_output_00046;
 wire [PARAM_w-1:0] q_output_00047;
 wire [PARAM_w-1:0] q_output_00048;
 wire [PARAM_w-1:0] q_output_00049;
 wire [PARAM_w-1:0] q_output_00050;
 wire [PARAM_w-1:0] q_output_00051;
 wire [PARAM_w-1:0] q_output_00052;
 wire [PARAM_w-1:0] q_output_00053;
 wire [PARAM_w-1:0] q_output_00054;
 wire [PARAM_w-1:0] q_output_00055;
 wire [PARAM_w-1:0] q_output_00056;
 wire [PARAM_w-1:0] q_output_00057;
 wire [PARAM_w-1:0] q_output_00058;
 wire [PARAM_w-1:0] q_output_00059;
 wire [PARAM_w-1:0] q_output_00060;
 wire [PARAM_w-1:0] q_output_00061;
 wire [PARAM_w-1:0] q_output_00062;
/* verilator lint_on UNUSED */

 wire  err_q_output_root_00001_loc_00062;
 wire  err_q_output_root_00002_loc_00061;
 wire  err_q_output_root_00003_loc_00060;
 wire  err_q_output_root_00004_loc_00059;
 wire  err_q_output_root_00005_loc_00058;
 wire  err_q_output_root_00006_loc_00057;
 wire  err_q_output_root_00007_loc_00056;
 wire  err_q_output_root_00008_loc_00055;
 wire  err_q_output_root_00009_loc_00054;
 wire  err_q_output_root_00010_loc_00053;
 wire  err_q_output_root_00011_loc_00052;
 wire  err_q_output_root_00012_loc_00051;
 wire  err_q_output_root_00013_loc_00050;
 wire  err_q_output_root_00014_loc_00049;
 wire  err_q_output_root_00015_loc_00048;
 wire  err_q_output_root_00016_loc_00047;
 wire  err_q_output_root_00017_loc_00046;
 wire  err_q_output_root_00018_loc_00045;
 wire  err_q_output_root_00019_loc_00044;
 wire  err_q_output_root_00020_loc_00043;
 wire  err_q_output_root_00021_loc_00042;
 wire  err_q_output_root_00022_loc_00041;
 wire  err_q_output_root_00023_loc_00040;
 wire  err_q_output_root_00024_loc_00039;
 wire  err_q_output_root_00025_loc_00038;
 wire  err_q_output_root_00026_loc_00037;
 wire  err_q_output_root_00027_loc_00036;
 wire  err_q_output_root_00028_loc_00035;
 wire  err_q_output_root_00029_loc_00034;
 wire  err_q_output_root_00030_loc_00033;
 wire  err_q_output_root_00031_loc_00032;
 wire  err_q_output_root_00032_loc_00031;
 wire  err_q_output_root_00033_loc_00030;
 wire  err_q_output_root_00034_loc_00029;
 wire  err_q_output_root_00035_loc_00028;
 wire  err_q_output_root_00036_loc_00027;
 wire  err_q_output_root_00037_loc_00026;
 wire  err_q_output_root_00038_loc_00025;
 wire  err_q_output_root_00039_loc_00024;
 wire  err_q_output_root_00040_loc_00023;
 wire  err_q_output_root_00041_loc_00022;
 wire  err_q_output_root_00042_loc_00021;
 wire  err_q_output_root_00043_loc_00020;
 wire  err_q_output_root_00044_loc_00019;
 wire  err_q_output_root_00045_loc_00018;
 wire  err_q_output_root_00046_loc_00017;
 wire  err_q_output_root_00047_loc_00016;
 wire  err_q_output_root_00048_loc_00015;
 wire  err_q_output_root_00049_loc_00014;
 wire  err_q_output_root_00050_loc_00013;
 wire  err_q_output_root_00051_loc_00012;
 wire  err_q_output_root_00052_loc_00011;
 wire  err_q_output_root_00053_loc_00010;
 wire  err_q_output_root_00054_loc_00009;
 wire  err_q_output_root_00055_loc_00008;
 wire  err_q_output_root_00056_loc_00007;
 wire  err_q_output_root_00057_loc_00006;
 wire  err_q_output_root_00058_loc_00005;
 wire  err_q_output_root_00059_loc_00004;
 wire  err_q_output_root_00060_loc_00003;
 wire  err_q_output_root_00061_loc_00002;
 wire  err_q_output_root_00062_loc_00001;
 wire  err_q_output_root_00063_loc_00000;







 wire [PARAM_w-1:0] root_i_val_w_00001;
 wire [PARAM_w-1:0] loc_i_val_w_00062;
 wire [PARAM_w-1:0] root_i_val_w_00002;
 wire [PARAM_w-1:0] loc_i_val_w_00061;
 wire [PARAM_w-1:0] root_i_val_w_00003;
 wire [PARAM_w-1:0] loc_i_val_w_00060;
 wire [PARAM_w-1:0] root_i_val_w_00004;
 wire [PARAM_w-1:0] loc_i_val_w_00059;
 wire [PARAM_w-1:0] root_i_val_w_00005;
 wire [PARAM_w-1:0] loc_i_val_w_00058;
 wire [PARAM_w-1:0] root_i_val_w_00006;
 wire [PARAM_w-1:0] loc_i_val_w_00057;
 wire [PARAM_w-1:0] root_i_val_w_00007;
 wire [PARAM_w-1:0] loc_i_val_w_00056;
 wire [PARAM_w-1:0] root_i_val_w_00008;
 wire [PARAM_w-1:0] loc_i_val_w_00055;
 wire [PARAM_w-1:0] root_i_val_w_00009;
 wire [PARAM_w-1:0] loc_i_val_w_00054;
 wire [PARAM_w-1:0] root_i_val_w_00010;
 wire [PARAM_w-1:0] loc_i_val_w_00053;
 wire [PARAM_w-1:0] root_i_val_w_00011;
 wire [PARAM_w-1:0] loc_i_val_w_00052;
 wire [PARAM_w-1:0] root_i_val_w_00012;
 wire [PARAM_w-1:0] loc_i_val_w_00051;
 wire [PARAM_w-1:0] root_i_val_w_00013;
 wire [PARAM_w-1:0] loc_i_val_w_00050;
 wire [PARAM_w-1:0] root_i_val_w_00014;
 wire [PARAM_w-1:0] loc_i_val_w_00049;
 wire [PARAM_w-1:0] root_i_val_w_00015;
 wire [PARAM_w-1:0] loc_i_val_w_00048;
 wire [PARAM_w-1:0] root_i_val_w_00016;
 wire [PARAM_w-1:0] loc_i_val_w_00047;
 wire [PARAM_w-1:0] root_i_val_w_00017;
 wire [PARAM_w-1:0] loc_i_val_w_00046;
 wire [PARAM_w-1:0] root_i_val_w_00018;
 wire [PARAM_w-1:0] loc_i_val_w_00045;
 wire [PARAM_w-1:0] root_i_val_w_00019;
 wire [PARAM_w-1:0] loc_i_val_w_00044;
 wire [PARAM_w-1:0] root_i_val_w_00020;
 wire [PARAM_w-1:0] loc_i_val_w_00043;
 wire [PARAM_w-1:0] root_i_val_w_00021;
 wire [PARAM_w-1:0] loc_i_val_w_00042;
 wire [PARAM_w-1:0] root_i_val_w_00022;
 wire [PARAM_w-1:0] loc_i_val_w_00041;
 wire [PARAM_w-1:0] root_i_val_w_00023;
 wire [PARAM_w-1:0] loc_i_val_w_00040;
 wire [PARAM_w-1:0] root_i_val_w_00024;
 wire [PARAM_w-1:0] loc_i_val_w_00039;
 wire [PARAM_w-1:0] root_i_val_w_00025;
 wire [PARAM_w-1:0] loc_i_val_w_00038;
 wire [PARAM_w-1:0] root_i_val_w_00026;
 wire [PARAM_w-1:0] loc_i_val_w_00037;
 wire [PARAM_w-1:0] root_i_val_w_00027;
 wire [PARAM_w-1:0] loc_i_val_w_00036;
 wire [PARAM_w-1:0] root_i_val_w_00028;
 wire [PARAM_w-1:0] loc_i_val_w_00035;
 wire [PARAM_w-1:0] root_i_val_w_00029;
 wire [PARAM_w-1:0] loc_i_val_w_00034;
 wire [PARAM_w-1:0] root_i_val_w_00030;
 wire [PARAM_w-1:0] loc_i_val_w_00033;
 wire [PARAM_w-1:0] root_i_val_w_00031;
 wire [PARAM_w-1:0] loc_i_val_w_00032;
 wire [PARAM_w-1:0] root_i_val_w_00032;
 wire [PARAM_w-1:0] loc_i_val_w_00031;
 wire [PARAM_w-1:0] root_i_val_w_00033;
 wire [PARAM_w-1:0] loc_i_val_w_00030;
 wire [PARAM_w-1:0] root_i_val_w_00034;
 wire [PARAM_w-1:0] loc_i_val_w_00029;
 wire [PARAM_w-1:0] root_i_val_w_00035;
 wire [PARAM_w-1:0] loc_i_val_w_00028;
 wire [PARAM_w-1:0] root_i_val_w_00036;
 wire [PARAM_w-1:0] loc_i_val_w_00027;
 wire [PARAM_w-1:0] root_i_val_w_00037;
 wire [PARAM_w-1:0] loc_i_val_w_00026;
 wire [PARAM_w-1:0] root_i_val_w_00038;
 wire [PARAM_w-1:0] loc_i_val_w_00025;
 wire [PARAM_w-1:0] root_i_val_w_00039;
 wire [PARAM_w-1:0] loc_i_val_w_00024;
 wire [PARAM_w-1:0] root_i_val_w_00040;
 wire [PARAM_w-1:0] loc_i_val_w_00023;
 wire [PARAM_w-1:0] root_i_val_w_00041;
 wire [PARAM_w-1:0] loc_i_val_w_00022;
 wire [PARAM_w-1:0] root_i_val_w_00042;
 wire [PARAM_w-1:0] loc_i_val_w_00021;
 wire [PARAM_w-1:0] root_i_val_w_00043;
 wire [PARAM_w-1:0] loc_i_val_w_00020;
 wire [PARAM_w-1:0] root_i_val_w_00044;
 wire [PARAM_w-1:0] loc_i_val_w_00019;
 wire [PARAM_w-1:0] root_i_val_w_00045;
 wire [PARAM_w-1:0] loc_i_val_w_00018;
 wire [PARAM_w-1:0] root_i_val_w_00046;
 wire [PARAM_w-1:0] loc_i_val_w_00017;
 wire [PARAM_w-1:0] root_i_val_w_00047;
 wire [PARAM_w-1:0] loc_i_val_w_00016;
 wire [PARAM_w-1:0] root_i_val_w_00048;
 wire [PARAM_w-1:0] loc_i_val_w_00015;
 wire [PARAM_w-1:0] root_i_val_w_00049;
 wire [PARAM_w-1:0] loc_i_val_w_00014;
 wire [PARAM_w-1:0] root_i_val_w_00050;
 wire [PARAM_w-1:0] loc_i_val_w_00013;
 wire [PARAM_w-1:0] root_i_val_w_00051;
 wire [PARAM_w-1:0] loc_i_val_w_00012;
 wire [PARAM_w-1:0] root_i_val_w_00052;
 wire [PARAM_w-1:0] loc_i_val_w_00011;
 wire [PARAM_w-1:0] root_i_val_w_00053;
 wire [PARAM_w-1:0] loc_i_val_w_00010;
 wire [PARAM_w-1:0] root_i_val_w_00054;
 wire [PARAM_w-1:0] loc_i_val_w_00009;
 wire [PARAM_w-1:0] root_i_val_w_00055;
 wire [PARAM_w-1:0] loc_i_val_w_00008;
 wire [PARAM_w-1:0] root_i_val_w_00056;
 wire [PARAM_w-1:0] loc_i_val_w_00007;
 wire [PARAM_w-1:0] root_i_val_w_00057;
 wire [PARAM_w-1:0] loc_i_val_w_00006;
 wire [PARAM_w-1:0] root_i_val_w_00058;
 wire [PARAM_w-1:0] loc_i_val_w_00005;
 wire [PARAM_w-1:0] root_i_val_w_00059;
 wire [PARAM_w-1:0] loc_i_val_w_00004;
 wire [PARAM_w-1:0] root_i_val_w_00060;
 wire [PARAM_w-1:0] loc_i_val_w_00003;
 wire [PARAM_w-1:0] root_i_val_w_00061;
 wire [PARAM_w-1:0] loc_i_val_w_00002;
 wire [PARAM_w-1:0] root_i_val_w_00062;
 wire [PARAM_w-1:0] loc_i_val_w_00001;
 wire [PARAM_w-1:0] root_i_val_w_00063;
 wire [PARAM_w-1:0] loc_i_val_w_00000;



 reg  [PARAM_w-1:0] root_reg_i_val_00001;
 reg  [PARAM_w-1:0] root_reg_i_val_00002;
 reg  [PARAM_w-1:0] root_reg_i_val_00003;
 reg  [PARAM_w-1:0] root_reg_i_val_00004;
 reg  [PARAM_w-1:0] root_reg_i_val_00005;


 wire  valid_root_00001_loc_00062 ;
 wire  valid_root_00002_loc_00061 ;
 wire  valid_root_00003_loc_00060 ;
 wire  valid_root_00004_loc_00059 ;
 wire  valid_root_00005_loc_00058 ;
 wire  valid_root_00006_loc_00057 ;
 wire  valid_root_00007_loc_00056 ;
 wire  valid_root_00008_loc_00055 ;
 wire  valid_root_00009_loc_00054 ;
 wire  valid_root_00010_loc_00053 ;
 wire  valid_root_00011_loc_00052 ;
 wire  valid_root_00012_loc_00051 ;
 wire  valid_root_00013_loc_00050 ;
 wire  valid_root_00014_loc_00049 ;
 wire  valid_root_00015_loc_00048 ;
 wire  valid_root_00016_loc_00047 ;
 wire  valid_root_00017_loc_00046 ;
 wire  valid_root_00018_loc_00045 ;
 wire  valid_root_00019_loc_00044 ;
 wire  valid_root_00020_loc_00043 ;
 wire  valid_root_00021_loc_00042 ;
 wire  valid_root_00022_loc_00041 ;
 wire  valid_root_00023_loc_00040 ;
 wire  valid_root_00024_loc_00039 ;
 wire  valid_root_00025_loc_00038 ;
 wire  valid_root_00026_loc_00037 ;
 wire  valid_root_00027_loc_00036 ;
 wire  valid_root_00028_loc_00035 ;
 wire  valid_root_00029_loc_00034 ;
 wire  valid_root_00030_loc_00033 ;
 wire  valid_root_00031_loc_00032 ;
 wire  valid_root_00032_loc_00031 ;
 wire  valid_root_00033_loc_00030 ;
 wire  valid_root_00034_loc_00029 ;
 wire  valid_root_00035_loc_00028 ;
 wire  valid_root_00036_loc_00027 ;
 wire  valid_root_00037_loc_00026 ;
 wire  valid_root_00038_loc_00025 ;
 wire  valid_root_00039_loc_00024 ;
 wire  valid_root_00040_loc_00023 ;
 wire  valid_root_00041_loc_00022 ;
 wire  valid_root_00042_loc_00021 ;
 wire  valid_root_00043_loc_00020 ;
 wire  valid_root_00044_loc_00019 ;
 wire  valid_root_00045_loc_00018 ;
 wire  valid_root_00046_loc_00017 ;
 wire  valid_root_00047_loc_00016 ;
 wire  valid_root_00048_loc_00015 ;
 wire  valid_root_00049_loc_00014 ;
 wire  valid_root_00050_loc_00013 ;
 wire  valid_root_00051_loc_00012 ;
 wire  valid_root_00052_loc_00011 ;
 wire  valid_root_00053_loc_00010 ;
 wire  valid_root_00054_loc_00009 ;
 wire  valid_root_00055_loc_00008 ;
 wire  valid_root_00056_loc_00007 ;
 wire  valid_root_00057_loc_00006 ;
 wire  valid_root_00058_loc_00005 ;
 wire  valid_root_00059_loc_00004 ;
 wire  valid_root_00060_loc_00003 ;
 wire  valid_root_00061_loc_00002 ;
 wire  valid_root_00062_loc_00001 ;
 wire  valid_root_00063_loc_00000 ;






reg  [PARAM_par_w-1:0] first_cur_err_cnt_00000;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00001;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00002;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00003;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00004;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00005;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00006;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00007;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00008;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00009;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00010;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00011;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00012;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00013;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00014;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00015;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00016;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00017;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00018;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00019;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00020;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00021;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00022;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00023;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00024;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00025;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00026;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00027;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00028;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00029;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00030;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00031;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00032;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00033;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00034;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00035;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00036;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00037;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00038;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00039;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00040;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00041;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00042;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00043;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00044;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00045;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00046;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00047;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00048;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00049;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00050;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00051;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00052;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00053;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00054;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00055;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00056;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00057;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00058;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00059;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00060;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00061;
reg  [PARAM_par_w-1:0] first_cur_err_cnt_00062;

reg [6-1:0] root_err_arr_00001;
reg [6-1:0] root_err_arr_00002;
reg [6-1:0] root_err_arr_00003;
reg [6-1:0] root_err_arr_00004;
reg [6-1:0] root_err_arr_00005;


 wire [0:(63-1 -0)] wire_cur_err_cnt_00000;
 wire [0:(63-1 -1)] wire_cur_err_cnt_00001;
 wire [0:(63-1 -2)] wire_cur_err_cnt_00002;
 wire [0:(63-1 -3)] wire_cur_err_cnt_00003;
 wire [0:(63-1 -4)] wire_cur_err_cnt_00004;


reg start_engine_w;
reg start_engine_q;
reg start_engine_w_pre_pulse;
reg start_engine_d1;
reg start_engine_d;



reg start_00000;
reg start_00001;
reg start_00002;
reg start_00003;
reg start_all;
reg start_all_end;

always_comb begin
           if (start) begin
              PARAM_t_lower_reg  = PARAM_t_lower;
           end else if (valid) begin
              PARAM_t_lower_reg  = {{(4-1){1'b0}},1'b0};
           end
end










`include "sntc_chien.inst.svp.sv"








`include "sntc_chien.root.svp.sv"




always_comb
begin

                        loc_err_00001  = PARAM_nn1 - root_reg_i_val_00001;
                        root_err_00001 = root_reg_i_val_00001;
                        loc_err_00002  = PARAM_nn1 - root_reg_i_val_00002;
                        root_err_00002 = root_reg_i_val_00002;
                        loc_err_00003  = PARAM_nn1 - root_reg_i_val_00003;
                        root_err_00003 = root_reg_i_val_00003;
                        loc_err_00004  = PARAM_nn1 - root_reg_i_val_00004;
                        root_err_00004 = root_reg_i_val_00004;
                        loc_err_00005  = PARAM_nn1 - root_reg_i_val_00005;
                        root_err_00005 = root_reg_i_val_00005;
end








`include "sntc_chien.cnt.svp.sv"


always_comb
begin
                       if (first_cur_err_cnt_00000 != 6'd0)
                           second_cur_err_cnt_00000_00062 = 1;
                       else
                           second_cur_err_cnt_00000_00062 = 6'd0;
                       if (first_cur_err_cnt_00001 != first_cur_err_cnt_00000)
                           second_cur_err_cnt_00001_00000 = first_cur_err_cnt_00001;
                       else
                           second_cur_err_cnt_00001_00000 = 6'd0;
                       if (first_cur_err_cnt_00002 != first_cur_err_cnt_00001)
                           second_cur_err_cnt_00002_00001 = first_cur_err_cnt_00002;
                       else
                           second_cur_err_cnt_00002_00001 = 6'd0;
                       if (first_cur_err_cnt_00003 != first_cur_err_cnt_00002)
                           second_cur_err_cnt_00003_00002 = first_cur_err_cnt_00003;
                       else
                           second_cur_err_cnt_00003_00002 = 6'd0;
                       if (first_cur_err_cnt_00004 != first_cur_err_cnt_00003)
                           second_cur_err_cnt_00004_00003 = first_cur_err_cnt_00004;
                       else
                           second_cur_err_cnt_00004_00003 = 6'd0;
                       if (first_cur_err_cnt_00005 != first_cur_err_cnt_00004)
                           second_cur_err_cnt_00005_00004 = first_cur_err_cnt_00005;
                       else
                           second_cur_err_cnt_00005_00004 = 6'd0;
                       if (first_cur_err_cnt_00006 != first_cur_err_cnt_00005)
                           second_cur_err_cnt_00006_00005 = first_cur_err_cnt_00006;
                       else
                           second_cur_err_cnt_00006_00005 = 6'd0;
                       if (first_cur_err_cnt_00007 != first_cur_err_cnt_00006)
                           second_cur_err_cnt_00007_00006 = first_cur_err_cnt_00007;
                       else
                           second_cur_err_cnt_00007_00006 = 6'd0;
                       if (first_cur_err_cnt_00008 != first_cur_err_cnt_00007)
                           second_cur_err_cnt_00008_00007 = first_cur_err_cnt_00008;
                       else
                           second_cur_err_cnt_00008_00007 = 6'd0;
                       if (first_cur_err_cnt_00009 != first_cur_err_cnt_00008)
                           second_cur_err_cnt_00009_00008 = first_cur_err_cnt_00009;
                       else
                           second_cur_err_cnt_00009_00008 = 6'd0;
                       if (first_cur_err_cnt_00010 != first_cur_err_cnt_00009)
                           second_cur_err_cnt_00010_00009 = first_cur_err_cnt_00010;
                       else
                           second_cur_err_cnt_00010_00009 = 6'd0;
                       if (first_cur_err_cnt_00011 != first_cur_err_cnt_00010)
                           second_cur_err_cnt_00011_00010 = first_cur_err_cnt_00011;
                       else
                           second_cur_err_cnt_00011_00010 = 6'd0;
                       if (first_cur_err_cnt_00012 != first_cur_err_cnt_00011)
                           second_cur_err_cnt_00012_00011 = first_cur_err_cnt_00012;
                       else
                           second_cur_err_cnt_00012_00011 = 6'd0;
                       if (first_cur_err_cnt_00013 != first_cur_err_cnt_00012)
                           second_cur_err_cnt_00013_00012 = first_cur_err_cnt_00013;
                       else
                           second_cur_err_cnt_00013_00012 = 6'd0;
                       if (first_cur_err_cnt_00014 != first_cur_err_cnt_00013)
                           second_cur_err_cnt_00014_00013 = first_cur_err_cnt_00014;
                       else
                           second_cur_err_cnt_00014_00013 = 6'd0;
                       if (first_cur_err_cnt_00015 != first_cur_err_cnt_00014)
                           second_cur_err_cnt_00015_00014 = first_cur_err_cnt_00015;
                       else
                           second_cur_err_cnt_00015_00014 = 6'd0;
                       if (first_cur_err_cnt_00016 != first_cur_err_cnt_00015)
                           second_cur_err_cnt_00016_00015 = first_cur_err_cnt_00016;
                       else
                           second_cur_err_cnt_00016_00015 = 6'd0;
                       if (first_cur_err_cnt_00017 != first_cur_err_cnt_00016)
                           second_cur_err_cnt_00017_00016 = first_cur_err_cnt_00017;
                       else
                           second_cur_err_cnt_00017_00016 = 6'd0;
                       if (first_cur_err_cnt_00018 != first_cur_err_cnt_00017)
                           second_cur_err_cnt_00018_00017 = first_cur_err_cnt_00018;
                       else
                           second_cur_err_cnt_00018_00017 = 6'd0;
                       if (first_cur_err_cnt_00019 != first_cur_err_cnt_00018)
                           second_cur_err_cnt_00019_00018 = first_cur_err_cnt_00019;
                       else
                           second_cur_err_cnt_00019_00018 = 6'd0;
                       if (first_cur_err_cnt_00020 != first_cur_err_cnt_00019)
                           second_cur_err_cnt_00020_00019 = first_cur_err_cnt_00020;
                       else
                           second_cur_err_cnt_00020_00019 = 6'd0;
                       if (first_cur_err_cnt_00021 != first_cur_err_cnt_00020)
                           second_cur_err_cnt_00021_00020 = first_cur_err_cnt_00021;
                       else
                           second_cur_err_cnt_00021_00020 = 6'd0;
                       if (first_cur_err_cnt_00022 != first_cur_err_cnt_00021)
                           second_cur_err_cnt_00022_00021 = first_cur_err_cnt_00022;
                       else
                           second_cur_err_cnt_00022_00021 = 6'd0;
                       if (first_cur_err_cnt_00023 != first_cur_err_cnt_00022)
                           second_cur_err_cnt_00023_00022 = first_cur_err_cnt_00023;
                       else
                           second_cur_err_cnt_00023_00022 = 6'd0;
                       if (first_cur_err_cnt_00024 != first_cur_err_cnt_00023)
                           second_cur_err_cnt_00024_00023 = first_cur_err_cnt_00024;
                       else
                           second_cur_err_cnt_00024_00023 = 6'd0;
                       if (first_cur_err_cnt_00025 != first_cur_err_cnt_00024)
                           second_cur_err_cnt_00025_00024 = first_cur_err_cnt_00025;
                       else
                           second_cur_err_cnt_00025_00024 = 6'd0;
                       if (first_cur_err_cnt_00026 != first_cur_err_cnt_00025)
                           second_cur_err_cnt_00026_00025 = first_cur_err_cnt_00026;
                       else
                           second_cur_err_cnt_00026_00025 = 6'd0;
                       if (first_cur_err_cnt_00027 != first_cur_err_cnt_00026)
                           second_cur_err_cnt_00027_00026 = first_cur_err_cnt_00027;
                       else
                           second_cur_err_cnt_00027_00026 = 6'd0;
                       if (first_cur_err_cnt_00028 != first_cur_err_cnt_00027)
                           second_cur_err_cnt_00028_00027 = first_cur_err_cnt_00028;
                       else
                           second_cur_err_cnt_00028_00027 = 6'd0;
                       if (first_cur_err_cnt_00029 != first_cur_err_cnt_00028)
                           second_cur_err_cnt_00029_00028 = first_cur_err_cnt_00029;
                       else
                           second_cur_err_cnt_00029_00028 = 6'd0;
                       if (first_cur_err_cnt_00030 != first_cur_err_cnt_00029)
                           second_cur_err_cnt_00030_00029 = first_cur_err_cnt_00030;
                       else
                           second_cur_err_cnt_00030_00029 = 6'd0;
                       if (first_cur_err_cnt_00031 != first_cur_err_cnt_00030)
                           second_cur_err_cnt_00031_00030 = first_cur_err_cnt_00031;
                       else
                           second_cur_err_cnt_00031_00030 = 6'd0;
                       if (first_cur_err_cnt_00032 != first_cur_err_cnt_00031)
                           second_cur_err_cnt_00032_00031 = first_cur_err_cnt_00032;
                       else
                           second_cur_err_cnt_00032_00031 = 6'd0;
                       if (first_cur_err_cnt_00033 != first_cur_err_cnt_00032)
                           second_cur_err_cnt_00033_00032 = first_cur_err_cnt_00033;
                       else
                           second_cur_err_cnt_00033_00032 = 6'd0;
                       if (first_cur_err_cnt_00034 != first_cur_err_cnt_00033)
                           second_cur_err_cnt_00034_00033 = first_cur_err_cnt_00034;
                       else
                           second_cur_err_cnt_00034_00033 = 6'd0;
                       if (first_cur_err_cnt_00035 != first_cur_err_cnt_00034)
                           second_cur_err_cnt_00035_00034 = first_cur_err_cnt_00035;
                       else
                           second_cur_err_cnt_00035_00034 = 6'd0;
                       if (first_cur_err_cnt_00036 != first_cur_err_cnt_00035)
                           second_cur_err_cnt_00036_00035 = first_cur_err_cnt_00036;
                       else
                           second_cur_err_cnt_00036_00035 = 6'd0;
                       if (first_cur_err_cnt_00037 != first_cur_err_cnt_00036)
                           second_cur_err_cnt_00037_00036 = first_cur_err_cnt_00037;
                       else
                           second_cur_err_cnt_00037_00036 = 6'd0;
                       if (first_cur_err_cnt_00038 != first_cur_err_cnt_00037)
                           second_cur_err_cnt_00038_00037 = first_cur_err_cnt_00038;
                       else
                           second_cur_err_cnt_00038_00037 = 6'd0;
                       if (first_cur_err_cnt_00039 != first_cur_err_cnt_00038)
                           second_cur_err_cnt_00039_00038 = first_cur_err_cnt_00039;
                       else
                           second_cur_err_cnt_00039_00038 = 6'd0;
                       if (first_cur_err_cnt_00040 != first_cur_err_cnt_00039)
                           second_cur_err_cnt_00040_00039 = first_cur_err_cnt_00040;
                       else
                           second_cur_err_cnt_00040_00039 = 6'd0;
                       if (first_cur_err_cnt_00041 != first_cur_err_cnt_00040)
                           second_cur_err_cnt_00041_00040 = first_cur_err_cnt_00041;
                       else
                           second_cur_err_cnt_00041_00040 = 6'd0;
                       if (first_cur_err_cnt_00042 != first_cur_err_cnt_00041)
                           second_cur_err_cnt_00042_00041 = first_cur_err_cnt_00042;
                       else
                           second_cur_err_cnt_00042_00041 = 6'd0;
                       if (first_cur_err_cnt_00043 != first_cur_err_cnt_00042)
                           second_cur_err_cnt_00043_00042 = first_cur_err_cnt_00043;
                       else
                           second_cur_err_cnt_00043_00042 = 6'd0;
                       if (first_cur_err_cnt_00044 != first_cur_err_cnt_00043)
                           second_cur_err_cnt_00044_00043 = first_cur_err_cnt_00044;
                       else
                           second_cur_err_cnt_00044_00043 = 6'd0;
                       if (first_cur_err_cnt_00045 != first_cur_err_cnt_00044)
                           second_cur_err_cnt_00045_00044 = first_cur_err_cnt_00045;
                       else
                           second_cur_err_cnt_00045_00044 = 6'd0;
                       if (first_cur_err_cnt_00046 != first_cur_err_cnt_00045)
                           second_cur_err_cnt_00046_00045 = first_cur_err_cnt_00046;
                       else
                           second_cur_err_cnt_00046_00045 = 6'd0;
                       if (first_cur_err_cnt_00047 != first_cur_err_cnt_00046)
                           second_cur_err_cnt_00047_00046 = first_cur_err_cnt_00047;
                       else
                           second_cur_err_cnt_00047_00046 = 6'd0;
                       if (first_cur_err_cnt_00048 != first_cur_err_cnt_00047)
                           second_cur_err_cnt_00048_00047 = first_cur_err_cnt_00048;
                       else
                           second_cur_err_cnt_00048_00047 = 6'd0;
                       if (first_cur_err_cnt_00049 != first_cur_err_cnt_00048)
                           second_cur_err_cnt_00049_00048 = first_cur_err_cnt_00049;
                       else
                           second_cur_err_cnt_00049_00048 = 6'd0;
                       if (first_cur_err_cnt_00050 != first_cur_err_cnt_00049)
                           second_cur_err_cnt_00050_00049 = first_cur_err_cnt_00050;
                       else
                           second_cur_err_cnt_00050_00049 = 6'd0;
                       if (first_cur_err_cnt_00051 != first_cur_err_cnt_00050)
                           second_cur_err_cnt_00051_00050 = first_cur_err_cnt_00051;
                       else
                           second_cur_err_cnt_00051_00050 = 6'd0;
                       if (first_cur_err_cnt_00052 != first_cur_err_cnt_00051)
                           second_cur_err_cnt_00052_00051 = first_cur_err_cnt_00052;
                       else
                           second_cur_err_cnt_00052_00051 = 6'd0;
                       if (first_cur_err_cnt_00053 != first_cur_err_cnt_00052)
                           second_cur_err_cnt_00053_00052 = first_cur_err_cnt_00053;
                       else
                           second_cur_err_cnt_00053_00052 = 6'd0;
                       if (first_cur_err_cnt_00054 != first_cur_err_cnt_00053)
                           second_cur_err_cnt_00054_00053 = first_cur_err_cnt_00054;
                       else
                           second_cur_err_cnt_00054_00053 = 6'd0;
                       if (first_cur_err_cnt_00055 != first_cur_err_cnt_00054)
                           second_cur_err_cnt_00055_00054 = first_cur_err_cnt_00055;
                       else
                           second_cur_err_cnt_00055_00054 = 6'd0;
                       if (first_cur_err_cnt_00056 != first_cur_err_cnt_00055)
                           second_cur_err_cnt_00056_00055 = first_cur_err_cnt_00056;
                       else
                           second_cur_err_cnt_00056_00055 = 6'd0;
                       if (first_cur_err_cnt_00057 != first_cur_err_cnt_00056)
                           second_cur_err_cnt_00057_00056 = first_cur_err_cnt_00057;
                       else
                           second_cur_err_cnt_00057_00056 = 6'd0;
                       if (first_cur_err_cnt_00058 != first_cur_err_cnt_00057)
                           second_cur_err_cnt_00058_00057 = first_cur_err_cnt_00058;
                       else
                           second_cur_err_cnt_00058_00057 = 6'd0;
                       if (first_cur_err_cnt_00059 != first_cur_err_cnt_00058)
                           second_cur_err_cnt_00059_00058 = first_cur_err_cnt_00059;
                       else
                           second_cur_err_cnt_00059_00058 = 6'd0;
                       if (first_cur_err_cnt_00060 != first_cur_err_cnt_00059)
                           second_cur_err_cnt_00060_00059 = first_cur_err_cnt_00060;
                       else
                           second_cur_err_cnt_00060_00059 = 6'd0;
                       if (first_cur_err_cnt_00061 != first_cur_err_cnt_00060)
                           second_cur_err_cnt_00061_00060 = first_cur_err_cnt_00061;
                       else
                           second_cur_err_cnt_00061_00060 = 6'd0;
                       if (first_cur_err_cnt_00062 != first_cur_err_cnt_00061)
                           second_cur_err_cnt_00062_00061 = first_cur_err_cnt_00062;
                       else
                           second_cur_err_cnt_00062_00061 = 6'd0;
end






assign err_count = cur_err_cnt;

always_comb begin
                cur_err_cnt =
                         err_q_output_root_00001_loc_00062 +
                         err_q_output_root_00002_loc_00061 +
                         err_q_output_root_00003_loc_00060 +
                         err_q_output_root_00004_loc_00059 +
                         err_q_output_root_00005_loc_00058 +
                         err_q_output_root_00006_loc_00057 +
                         err_q_output_root_00007_loc_00056 +
                         err_q_output_root_00008_loc_00055 +
                         err_q_output_root_00009_loc_00054 +
                         err_q_output_root_00010_loc_00053 +
                         err_q_output_root_00011_loc_00052 +
                         err_q_output_root_00012_loc_00051 +
                         err_q_output_root_00013_loc_00050 +
                         err_q_output_root_00014_loc_00049 +
                         err_q_output_root_00015_loc_00048 +
                         err_q_output_root_00016_loc_00047 +
                         err_q_output_root_00017_loc_00046 +
                         err_q_output_root_00018_loc_00045 +
                         err_q_output_root_00019_loc_00044 +
                         err_q_output_root_00020_loc_00043 +
                         err_q_output_root_00021_loc_00042 +
                         err_q_output_root_00022_loc_00041 +
                         err_q_output_root_00023_loc_00040 +
                         err_q_output_root_00024_loc_00039 +
                         err_q_output_root_00025_loc_00038 +
                         err_q_output_root_00026_loc_00037 +
                         err_q_output_root_00027_loc_00036 +
                         err_q_output_root_00028_loc_00035 +
                         err_q_output_root_00029_loc_00034 +
                         err_q_output_root_00030_loc_00033 +
                         err_q_output_root_00031_loc_00032 +
                         err_q_output_root_00032_loc_00031 +
                         err_q_output_root_00033_loc_00030 +
                         err_q_output_root_00034_loc_00029 +
                         err_q_output_root_00035_loc_00028 +
                         err_q_output_root_00036_loc_00027 +
                         err_q_output_root_00037_loc_00026 +
                         err_q_output_root_00038_loc_00025 +
                         err_q_output_root_00039_loc_00024 +
                         err_q_output_root_00040_loc_00023 +
                         err_q_output_root_00041_loc_00022 +
                         err_q_output_root_00042_loc_00021 +
                         err_q_output_root_00043_loc_00020 +
                         err_q_output_root_00044_loc_00019 +
                         err_q_output_root_00045_loc_00018 +
                         err_q_output_root_00046_loc_00017 +
                         err_q_output_root_00047_loc_00016 +
                         err_q_output_root_00048_loc_00015 +
                         err_q_output_root_00049_loc_00014 +
                         err_q_output_root_00050_loc_00013 +
                         err_q_output_root_00051_loc_00012 +
                         err_q_output_root_00052_loc_00011 +
                         err_q_output_root_00053_loc_00010 +
                         err_q_output_root_00054_loc_00009 +
                         err_q_output_root_00055_loc_00008 +
                         err_q_output_root_00056_loc_00007 +
                         err_q_output_root_00057_loc_00006 +
                         err_q_output_root_00058_loc_00005 +
                         err_q_output_root_00059_loc_00004 +
                         err_q_output_root_00060_loc_00003 +
                         err_q_output_root_00061_loc_00002 +
                         err_q_output_root_00062_loc_00001 +
                         err_q_output_root_00063_loc_00000 +
                            0;
end
/* verilator lint_on WIDTH */



always_comb begin
      total_valid_reg = total_valid;
end
always_comb
begin
      valid = valid_d;
end
always_comb valid_d = start_00003;


always_comb  start_engine_w = start_all;






endmodule


//END:



// CCCC primitive_P(x) = 1100001// CCCC 
// CCCC Pass Enter code length:59 (31 < length <= 63): 
