//#;; DO NOT EDIT THIS FILE
/*ENCRYPT_ME*/
////////////////////////////////////////////////////////////////////////////////
//# Copyright (c) 2018 Secantec
//# No Permission to modify and distribute this program
//# even if this copyright message remains unaltered.
//#
//# Author: Secantec 27 April, 2018
//# $Id: $//#
//# Revision History
//#       MM      17  April, 2018    Initial release
//#
////////////////////////////////////////////////////////////////////////////////

 /*ENCRYPT_ME*/


//rm -rf *simv* *csrc* ; perl vpp.pl -perl sntc_rs_gen_poly.sv > sntc_rs_gen_poly.vpp.sv ; vcs -sverilo -R -debug_all sntc_rs_gen_poly.vpp.sv -l sntc_rs_gen_poly.vpp.sv.log

/* verilator lint_off DECLFILENAME */

//final:MYSEED:600500
//final:PARAM_m:6
//final:PARAM_t:5

// pRev[0]:1
// pRev[1]:0
// pRev[2]:0
// pRev[3]:0
// pRev[4]:0
// pRev[5]:1
// POLY perl :0x3
// pRev[0]:1
// pRev[1]:0
// pRev[2]:0
// pRev[3]:0
// pRev[4]:0
// pRev[5]:1
// POLY perl :0x3
`define d_d_q 4
`define d_m 6
function integer clog2;
  input integer value;
begin
   value = value-1;
   for (clog2=0; value>0; clog2=clog2+1)
      value = value>>1;
   end
endfunction

module  sntc_rs_gen_poly#(
 parameter  PARAM_m = 6,
 parameter  PARAM_nn = 63,
 parameter  PARAM_reduced_n = 63,
 parameter  PARAM_k = 53,
 parameter  PARAM_t = 5,
 parameter  PARAM_t2 = 10,
 parameter  PARAM_d = 11,
 parameter  PARAM_w = 6,
 parameter  PARAM_no_eras_w = $clog2(10+1),
 parameter  PARAM_tt2_w = 5,
 parameter  PARAM_states = 12,
 parameter  PARAM_states_w = $clog2(PARAM_states+1)
) (

input wire [6-1:0] bb0,  //has to be 1 or greater

//BEGIN:
output reg  [PARAM_w-1:0] gg_00000,
output reg  [PARAM_w-1:0] gg_00001,
output reg  [PARAM_w-1:0] gg_00002,
output reg  [PARAM_w-1:0] gg_00003,
output reg  [PARAM_w-1:0] gg_00004,
output reg  [PARAM_w-1:0] gg_00005,
output reg  [PARAM_w-1:0] gg_00006,
output reg  [PARAM_w-1:0] gg_00007,
output reg  [PARAM_w-1:0] gg_00008,
output reg  [PARAM_w-1:0] gg_00009,
output reg  [PARAM_w-1:0] gg_00010,
//END:

/* verilator lint_off UNUSED */
(* keep = "true" *) input wire [4-1:0] PARAM_t_lower,
/* verilator lint_on UNUSED */
(* keep = "true" *) input wire [5-1:0] PARAM_t2_lower
/* verilator lint_off UNUSED */
,
input wire start,
/* verilator lint_off UNDRIVEN */
output reg valid,
/* verilator lint_on UNDRIVEN */
input wire rstn,
input wire clr,
input wire clk
/* verilator lint_on UNUSED */

);



// BEGIN: local variables



//BEGIN:
wire [PARAM_w-1:0] alpha_pow_gg_00001_00000;
wire [PARAM_w-1:0] alpha_pow_gg_00002_00001;
wire [PARAM_w-1:0] alpha_pow_gg_00002_00000;
wire [PARAM_w-1:0] alpha_pow_gg_00003_00002;
wire [PARAM_w-1:0] alpha_pow_gg_00003_00001;
wire [PARAM_w-1:0] alpha_pow_gg_00003_00000;
wire [PARAM_w-1:0] alpha_pow_gg_00004_00003;
wire [PARAM_w-1:0] alpha_pow_gg_00004_00002;
wire [PARAM_w-1:0] alpha_pow_gg_00004_00001;
wire [PARAM_w-1:0] alpha_pow_gg_00004_00000;
wire [PARAM_w-1:0] alpha_pow_gg_00005_00004;
wire [PARAM_w-1:0] alpha_pow_gg_00005_00003;
wire [PARAM_w-1:0] alpha_pow_gg_00005_00002;
wire [PARAM_w-1:0] alpha_pow_gg_00005_00001;
wire [PARAM_w-1:0] alpha_pow_gg_00005_00000;
wire [PARAM_w-1:0] alpha_pow_gg_00006_00005;
wire [PARAM_w-1:0] alpha_pow_gg_00006_00004;
wire [PARAM_w-1:0] alpha_pow_gg_00006_00003;
wire [PARAM_w-1:0] alpha_pow_gg_00006_00002;
wire [PARAM_w-1:0] alpha_pow_gg_00006_00001;
wire [PARAM_w-1:0] alpha_pow_gg_00006_00000;
wire [PARAM_w-1:0] alpha_pow_gg_00007_00006;
wire [PARAM_w-1:0] alpha_pow_gg_00007_00005;
wire [PARAM_w-1:0] alpha_pow_gg_00007_00004;
wire [PARAM_w-1:0] alpha_pow_gg_00007_00003;
wire [PARAM_w-1:0] alpha_pow_gg_00007_00002;
wire [PARAM_w-1:0] alpha_pow_gg_00007_00001;
wire [PARAM_w-1:0] alpha_pow_gg_00007_00000;
wire [PARAM_w-1:0] alpha_pow_gg_00008_00007;
wire [PARAM_w-1:0] alpha_pow_gg_00008_00006;
wire [PARAM_w-1:0] alpha_pow_gg_00008_00005;
wire [PARAM_w-1:0] alpha_pow_gg_00008_00004;
wire [PARAM_w-1:0] alpha_pow_gg_00008_00003;
wire [PARAM_w-1:0] alpha_pow_gg_00008_00002;
wire [PARAM_w-1:0] alpha_pow_gg_00008_00001;
wire [PARAM_w-1:0] alpha_pow_gg_00008_00000;
wire [PARAM_w-1:0] alpha_pow_gg_00009_00008;
wire [PARAM_w-1:0] alpha_pow_gg_00009_00007;
wire [PARAM_w-1:0] alpha_pow_gg_00009_00006;
wire [PARAM_w-1:0] alpha_pow_gg_00009_00005;
wire [PARAM_w-1:0] alpha_pow_gg_00009_00004;
wire [PARAM_w-1:0] alpha_pow_gg_00009_00003;
wire [PARAM_w-1:0] alpha_pow_gg_00009_00002;
wire [PARAM_w-1:0] alpha_pow_gg_00009_00001;
wire [PARAM_w-1:0] alpha_pow_gg_00009_00000;
wire [PARAM_w-1:0] alpha_pow_gg_00010_00009;
wire [PARAM_w-1:0] alpha_pow_gg_00010_00008;
wire [PARAM_w-1:0] alpha_pow_gg_00010_00007;
wire [PARAM_w-1:0] alpha_pow_gg_00010_00006;
wire [PARAM_w-1:0] alpha_pow_gg_00010_00005;
wire [PARAM_w-1:0] alpha_pow_gg_00010_00004;
wire [PARAM_w-1:0] alpha_pow_gg_00010_00003;
wire [PARAM_w-1:0] alpha_pow_gg_00010_00002;
wire [PARAM_w-1:0] alpha_pow_gg_00010_00001;
wire [PARAM_w-1:0] alpha_pow_gg_00010_00000;
//END:





//BEGIN:
wire [PARAM_w-1:0] gg_00000_00000;
wire [PARAM_w-1:0] gg_00001_00001;
wire [PARAM_w-1:0] gg_00001_00000;
wire [PARAM_w-1:0] gg_00002_00002;
wire [PARAM_w-1:0] gg_00002_00001;
wire [PARAM_w-1:0] gg_00002_00000;
wire [PARAM_w-1:0] gg_00003_00003;
wire [PARAM_w-1:0] gg_00003_00002;
wire [PARAM_w-1:0] gg_00003_00001;
wire [PARAM_w-1:0] gg_00003_00000;
wire [PARAM_w-1:0] gg_00004_00004;
wire [PARAM_w-1:0] gg_00004_00003;
wire [PARAM_w-1:0] gg_00004_00002;
wire [PARAM_w-1:0] gg_00004_00001;
wire [PARAM_w-1:0] gg_00004_00000;
wire [PARAM_w-1:0] gg_00005_00005;
wire [PARAM_w-1:0] gg_00005_00004;
wire [PARAM_w-1:0] gg_00005_00003;
wire [PARAM_w-1:0] gg_00005_00002;
wire [PARAM_w-1:0] gg_00005_00001;
wire [PARAM_w-1:0] gg_00005_00000;
wire [PARAM_w-1:0] gg_00006_00006;
wire [PARAM_w-1:0] gg_00006_00005;
wire [PARAM_w-1:0] gg_00006_00004;
wire [PARAM_w-1:0] gg_00006_00003;
wire [PARAM_w-1:0] gg_00006_00002;
wire [PARAM_w-1:0] gg_00006_00001;
wire [PARAM_w-1:0] gg_00006_00000;
wire [PARAM_w-1:0] gg_00007_00007;
wire [PARAM_w-1:0] gg_00007_00006;
wire [PARAM_w-1:0] gg_00007_00005;
wire [PARAM_w-1:0] gg_00007_00004;
wire [PARAM_w-1:0] gg_00007_00003;
wire [PARAM_w-1:0] gg_00007_00002;
wire [PARAM_w-1:0] gg_00007_00001;
wire [PARAM_w-1:0] gg_00007_00000;
wire [PARAM_w-1:0] gg_00008_00008;
wire [PARAM_w-1:0] gg_00008_00007;
wire [PARAM_w-1:0] gg_00008_00006;
wire [PARAM_w-1:0] gg_00008_00005;
wire [PARAM_w-1:0] gg_00008_00004;
wire [PARAM_w-1:0] gg_00008_00003;
wire [PARAM_w-1:0] gg_00008_00002;
wire [PARAM_w-1:0] gg_00008_00001;
wire [PARAM_w-1:0] gg_00008_00000;
wire [PARAM_w-1:0] gg_00009_00009;
wire [PARAM_w-1:0] gg_00009_00008;
wire [PARAM_w-1:0] gg_00009_00007;
wire [PARAM_w-1:0] gg_00009_00006;
wire [PARAM_w-1:0] gg_00009_00005;
wire [PARAM_w-1:0] gg_00009_00004;
wire [PARAM_w-1:0] gg_00009_00003;
wire [PARAM_w-1:0] gg_00009_00002;
wire [PARAM_w-1:0] gg_00009_00001;
wire [PARAM_w-1:0] gg_00009_00000;
wire [PARAM_w-1:0] gg_00010_00010;
wire [PARAM_w-1:0] gg_00010_00009;
wire [PARAM_w-1:0] gg_00010_00008;
wire [PARAM_w-1:0] gg_00010_00007;
wire [PARAM_w-1:0] gg_00010_00006;
wire [PARAM_w-1:0] gg_00010_00005;
wire [PARAM_w-1:0] gg_00010_00004;
wire [PARAM_w-1:0] gg_00010_00003;
wire [PARAM_w-1:0] gg_00010_00002;
wire [PARAM_w-1:0] gg_00010_00001;
wire [PARAM_w-1:0] gg_00010_00000;
//END:


//BEGIN:
wire [6-1:0] alpha_pow_bb0WithI_00002;  //has to be 1 or greater
wire [6-1:0] alpha_pow_bb0WithI_00003;  //has to be 1 or greater
wire [6-1:0] alpha_pow_bb0WithI_00004;  //has to be 1 or greater
wire [6-1:0] alpha_pow_bb0WithI_00005;  //has to be 1 or greater
wire [6-1:0] alpha_pow_bb0WithI_00006;  //has to be 1 or greater
wire [6-1:0] alpha_pow_bb0WithI_00007;  //has to be 1 or greater
wire [6-1:0] alpha_pow_bb0WithI_00008;  //has to be 1 or greater
wire [6-1:0] alpha_pow_bb0WithI_00009;  //has to be 1 or greater
wire [6-1:0] alpha_pow_bb0WithI_00010;  //has to be 1 or greater
//END:



//BEGIN:
wire [3*6-1:0] bb0WithI_00002;  //has to be 1 or greater
wire [3*6-1:0] bb0WithI_00003;  //has to be 1 or greater
wire [3*6-1:0] bb0WithI_00004;  //has to be 1 or greater
wire [3*6-1:0] bb0WithI_00005;  //has to be 1 or greater
wire [3*6-1:0] bb0WithI_00006;  //has to be 1 or greater
wire [3*6-1:0] bb0WithI_00007;  //has to be 1 or greater
wire [3*6-1:0] bb0WithI_00008;  //has to be 1 or greater
wire [3*6-1:0] bb0WithI_00009;  //has to be 1 or greater
wire [3*6-1:0] bb0WithI_00010;  //has to be 1 or greater
//END:

wire [3*6-1:0] bb0WithI0;  //has to be 1 or greater

// END: local variables





assign gg_00001_00000 = alpha_pow_gg_00001_00000;

//BEGIN:
assign gg_00000_00000 = 6'b1;
assign gg_00001_00001 = 6'b1;
assign gg_00002_00002 = 6'b1;
assign gg_00003_00003 = 6'b1;
assign gg_00004_00004 = 6'b1;
assign gg_00005_00005 = 6'b1;
assign gg_00006_00006 = 6'b1;
assign gg_00007_00007 = 6'b1;
assign gg_00008_00008 = 6'b1;
assign gg_00009_00009 = 6'b1;
assign gg_00010_00010 = 6'b1;
//END:


assign bb0WithI0 = { {(2*6){1'b0}}, bb0 };

calc_alpha_pow calc_alpha_pow_6_00001_U (
                  .iInput(bb0WithI0),
                  .num1(6'd1),
                  .calcAlphaPow(alpha_pow_gg_00001_00000),
                  .clk(clk),
                  .clr(clr),
                  .rstn(rstn)
                  );



//BEGIN:

// begin II: 2
assign bb0WithI_00002 = { {(2*6){1'b0}}, bb0 } + 18'd2 + 18'd63 - 18'd1;

calc_alpha_pow calc_alpha_pow_6_00002_U (
                  .iInput(bb0WithI_00002),
                  .num1(6'd1),
                  .calcAlphaPow(alpha_pow_bb0WithI_00002),
                  .clk(clk),
                  .clr(clr),
                  .rstn(rstn)
                  );



             assign alpha_pow_gg_00002_00001 = alpha_pow_bb0WithI_00002;


assign gg_00002_00001 = gg_00001_00000 ^ alpha_pow_gg_00002_00001;


// end JJ: 1

 PowcrcMult PowcrcMult_00002_00000(
                   .prdct_z(alpha_pow_gg_00002_00000),
                   .fact_a(alpha_pow_bb0WithI_00002),
                   .fact_b(gg_00001_00000)
                  );

assign gg_00002_00000 = alpha_pow_gg_00002_00000;

// end II: 2


// begin II: 3
assign bb0WithI_00003 = { {(2*6){1'b0}}, bb0 } + 18'd3 + 18'd63 - 18'd1;

calc_alpha_pow calc_alpha_pow_6_00003_U (
                  .iInput(bb0WithI_00003),
                  .num1(6'd1),
                  .calcAlphaPow(alpha_pow_bb0WithI_00003),
                  .clk(clk),
                  .clr(clr),
                  .rstn(rstn)
                  );



             assign alpha_pow_gg_00003_00002 = alpha_pow_bb0WithI_00003;


assign gg_00003_00002 = gg_00002_00001 ^ alpha_pow_gg_00003_00002;


// end JJ: 2

// begin JJ: 1
 PowcrcMult PowcrcMult_00003_00001(
                   .prdct_z(alpha_pow_gg_00003_00001),
                   .fact_a(alpha_pow_bb0WithI_00003),
                   .fact_b(gg_00002_00001)
                  );


assign gg_00003_00001 = gg_00002_00000 ^ alpha_pow_gg_00003_00001;


// end JJ: 1

 PowcrcMult PowcrcMult_00003_00000(
                   .prdct_z(alpha_pow_gg_00003_00000),
                   .fact_a(alpha_pow_bb0WithI_00003),
                   .fact_b(gg_00002_00000)
                  );

assign gg_00003_00000 = alpha_pow_gg_00003_00000;

// end II: 3


// begin II: 4
assign bb0WithI_00004 = { {(2*6){1'b0}}, bb0 } + 18'd4 + 18'd63 - 18'd1;

calc_alpha_pow calc_alpha_pow_6_00004_U (
                  .iInput(bb0WithI_00004),
                  .num1(6'd1),
                  .calcAlphaPow(alpha_pow_bb0WithI_00004),
                  .clk(clk),
                  .clr(clr),
                  .rstn(rstn)
                  );



             assign alpha_pow_gg_00004_00003 = alpha_pow_bb0WithI_00004;


assign gg_00004_00003 = gg_00003_00002 ^ alpha_pow_gg_00004_00003;


// end JJ: 3

// begin JJ: 2
 PowcrcMult PowcrcMult_00004_00002(
                   .prdct_z(alpha_pow_gg_00004_00002),
                   .fact_a(alpha_pow_bb0WithI_00004),
                   .fact_b(gg_00003_00002)
                  );


assign gg_00004_00002 = gg_00003_00001 ^ alpha_pow_gg_00004_00002;


// end JJ: 2

// begin JJ: 1
 PowcrcMult PowcrcMult_00004_00001(
                   .prdct_z(alpha_pow_gg_00004_00001),
                   .fact_a(alpha_pow_bb0WithI_00004),
                   .fact_b(gg_00003_00001)
                  );


assign gg_00004_00001 = gg_00003_00000 ^ alpha_pow_gg_00004_00001;


// end JJ: 1

 PowcrcMult PowcrcMult_00004_00000(
                   .prdct_z(alpha_pow_gg_00004_00000),
                   .fact_a(alpha_pow_bb0WithI_00004),
                   .fact_b(gg_00003_00000)
                  );

assign gg_00004_00000 = alpha_pow_gg_00004_00000;

// end II: 4


// begin II: 5
assign bb0WithI_00005 = { {(2*6){1'b0}}, bb0 } + 18'd5 + 18'd63 - 18'd1;

calc_alpha_pow calc_alpha_pow_6_00005_U (
                  .iInput(bb0WithI_00005),
                  .num1(6'd1),
                  .calcAlphaPow(alpha_pow_bb0WithI_00005),
                  .clk(clk),
                  .clr(clr),
                  .rstn(rstn)
                  );



             assign alpha_pow_gg_00005_00004 = alpha_pow_bb0WithI_00005;


assign gg_00005_00004 = gg_00004_00003 ^ alpha_pow_gg_00005_00004;


// end JJ: 4

// begin JJ: 3
 PowcrcMult PowcrcMult_00005_00003(
                   .prdct_z(alpha_pow_gg_00005_00003),
                   .fact_a(alpha_pow_bb0WithI_00005),
                   .fact_b(gg_00004_00003)
                  );


assign gg_00005_00003 = gg_00004_00002 ^ alpha_pow_gg_00005_00003;


// end JJ: 3

// begin JJ: 2
 PowcrcMult PowcrcMult_00005_00002(
                   .prdct_z(alpha_pow_gg_00005_00002),
                   .fact_a(alpha_pow_bb0WithI_00005),
                   .fact_b(gg_00004_00002)
                  );


assign gg_00005_00002 = gg_00004_00001 ^ alpha_pow_gg_00005_00002;


// end JJ: 2

// begin JJ: 1
 PowcrcMult PowcrcMult_00005_00001(
                   .prdct_z(alpha_pow_gg_00005_00001),
                   .fact_a(alpha_pow_bb0WithI_00005),
                   .fact_b(gg_00004_00001)
                  );


assign gg_00005_00001 = gg_00004_00000 ^ alpha_pow_gg_00005_00001;


// end JJ: 1

 PowcrcMult PowcrcMult_00005_00000(
                   .prdct_z(alpha_pow_gg_00005_00000),
                   .fact_a(alpha_pow_bb0WithI_00005),
                   .fact_b(gg_00004_00000)
                  );

assign gg_00005_00000 = alpha_pow_gg_00005_00000;

// end II: 5


// begin II: 6
assign bb0WithI_00006 = { {(2*6){1'b0}}, bb0 } + 18'd6 + 18'd63 - 18'd1;

calc_alpha_pow calc_alpha_pow_6_00006_U (
                  .iInput(bb0WithI_00006),
                  .num1(6'd1),
                  .calcAlphaPow(alpha_pow_bb0WithI_00006),
                  .clk(clk),
                  .clr(clr),
                  .rstn(rstn)
                  );



             assign alpha_pow_gg_00006_00005 = alpha_pow_bb0WithI_00006;


assign gg_00006_00005 = gg_00005_00004 ^ alpha_pow_gg_00006_00005;


// end JJ: 5

// begin JJ: 4
 PowcrcMult PowcrcMult_00006_00004(
                   .prdct_z(alpha_pow_gg_00006_00004),
                   .fact_a(alpha_pow_bb0WithI_00006),
                   .fact_b(gg_00005_00004)
                  );


assign gg_00006_00004 = gg_00005_00003 ^ alpha_pow_gg_00006_00004;


// end JJ: 4

// begin JJ: 3
 PowcrcMult PowcrcMult_00006_00003(
                   .prdct_z(alpha_pow_gg_00006_00003),
                   .fact_a(alpha_pow_bb0WithI_00006),
                   .fact_b(gg_00005_00003)
                  );


assign gg_00006_00003 = gg_00005_00002 ^ alpha_pow_gg_00006_00003;


// end JJ: 3

// begin JJ: 2
 PowcrcMult PowcrcMult_00006_00002(
                   .prdct_z(alpha_pow_gg_00006_00002),
                   .fact_a(alpha_pow_bb0WithI_00006),
                   .fact_b(gg_00005_00002)
                  );


assign gg_00006_00002 = gg_00005_00001 ^ alpha_pow_gg_00006_00002;


// end JJ: 2

// begin JJ: 1
 PowcrcMult PowcrcMult_00006_00001(
                   .prdct_z(alpha_pow_gg_00006_00001),
                   .fact_a(alpha_pow_bb0WithI_00006),
                   .fact_b(gg_00005_00001)
                  );


assign gg_00006_00001 = gg_00005_00000 ^ alpha_pow_gg_00006_00001;


// end JJ: 1

 PowcrcMult PowcrcMult_00006_00000(
                   .prdct_z(alpha_pow_gg_00006_00000),
                   .fact_a(alpha_pow_bb0WithI_00006),
                   .fact_b(gg_00005_00000)
                  );

assign gg_00006_00000 = alpha_pow_gg_00006_00000;

// end II: 6


// begin II: 7
assign bb0WithI_00007 = { {(2*6){1'b0}}, bb0 } + 18'd7 + 18'd63 - 18'd1;

calc_alpha_pow calc_alpha_pow_6_00007_U (
                  .iInput(bb0WithI_00007),
                  .num1(6'd1),
                  .calcAlphaPow(alpha_pow_bb0WithI_00007),
                  .clk(clk),
                  .clr(clr),
                  .rstn(rstn)
                  );



             assign alpha_pow_gg_00007_00006 = alpha_pow_bb0WithI_00007;


assign gg_00007_00006 = gg_00006_00005 ^ alpha_pow_gg_00007_00006;


// end JJ: 6

// begin JJ: 5
 PowcrcMult PowcrcMult_00007_00005(
                   .prdct_z(alpha_pow_gg_00007_00005),
                   .fact_a(alpha_pow_bb0WithI_00007),
                   .fact_b(gg_00006_00005)
                  );


assign gg_00007_00005 = gg_00006_00004 ^ alpha_pow_gg_00007_00005;


// end JJ: 5

// begin JJ: 4
 PowcrcMult PowcrcMult_00007_00004(
                   .prdct_z(alpha_pow_gg_00007_00004),
                   .fact_a(alpha_pow_bb0WithI_00007),
                   .fact_b(gg_00006_00004)
                  );


assign gg_00007_00004 = gg_00006_00003 ^ alpha_pow_gg_00007_00004;


// end JJ: 4

// begin JJ: 3
 PowcrcMult PowcrcMult_00007_00003(
                   .prdct_z(alpha_pow_gg_00007_00003),
                   .fact_a(alpha_pow_bb0WithI_00007),
                   .fact_b(gg_00006_00003)
                  );


assign gg_00007_00003 = gg_00006_00002 ^ alpha_pow_gg_00007_00003;


// end JJ: 3

// begin JJ: 2
 PowcrcMult PowcrcMult_00007_00002(
                   .prdct_z(alpha_pow_gg_00007_00002),
                   .fact_a(alpha_pow_bb0WithI_00007),
                   .fact_b(gg_00006_00002)
                  );


assign gg_00007_00002 = gg_00006_00001 ^ alpha_pow_gg_00007_00002;


// end JJ: 2

// begin JJ: 1
 PowcrcMult PowcrcMult_00007_00001(
                   .prdct_z(alpha_pow_gg_00007_00001),
                   .fact_a(alpha_pow_bb0WithI_00007),
                   .fact_b(gg_00006_00001)
                  );


assign gg_00007_00001 = gg_00006_00000 ^ alpha_pow_gg_00007_00001;


// end JJ: 1

 PowcrcMult PowcrcMult_00007_00000(
                   .prdct_z(alpha_pow_gg_00007_00000),
                   .fact_a(alpha_pow_bb0WithI_00007),
                   .fact_b(gg_00006_00000)
                  );

assign gg_00007_00000 = alpha_pow_gg_00007_00000;

// end II: 7


// begin II: 8
assign bb0WithI_00008 = { {(2*6){1'b0}}, bb0 } + 18'd8 + 18'd63 - 18'd1;

calc_alpha_pow calc_alpha_pow_6_00008_U (
                  .iInput(bb0WithI_00008),
                  .num1(6'd1),
                  .calcAlphaPow(alpha_pow_bb0WithI_00008),
                  .clk(clk),
                  .clr(clr),
                  .rstn(rstn)
                  );



             assign alpha_pow_gg_00008_00007 = alpha_pow_bb0WithI_00008;


assign gg_00008_00007 = gg_00007_00006 ^ alpha_pow_gg_00008_00007;


// end JJ: 7

// begin JJ: 6
 PowcrcMult PowcrcMult_00008_00006(
                   .prdct_z(alpha_pow_gg_00008_00006),
                   .fact_a(alpha_pow_bb0WithI_00008),
                   .fact_b(gg_00007_00006)
                  );


assign gg_00008_00006 = gg_00007_00005 ^ alpha_pow_gg_00008_00006;


// end JJ: 6

// begin JJ: 5
 PowcrcMult PowcrcMult_00008_00005(
                   .prdct_z(alpha_pow_gg_00008_00005),
                   .fact_a(alpha_pow_bb0WithI_00008),
                   .fact_b(gg_00007_00005)
                  );


assign gg_00008_00005 = gg_00007_00004 ^ alpha_pow_gg_00008_00005;


// end JJ: 5

// begin JJ: 4
 PowcrcMult PowcrcMult_00008_00004(
                   .prdct_z(alpha_pow_gg_00008_00004),
                   .fact_a(alpha_pow_bb0WithI_00008),
                   .fact_b(gg_00007_00004)
                  );


assign gg_00008_00004 = gg_00007_00003 ^ alpha_pow_gg_00008_00004;


// end JJ: 4

// begin JJ: 3
 PowcrcMult PowcrcMult_00008_00003(
                   .prdct_z(alpha_pow_gg_00008_00003),
                   .fact_a(alpha_pow_bb0WithI_00008),
                   .fact_b(gg_00007_00003)
                  );


assign gg_00008_00003 = gg_00007_00002 ^ alpha_pow_gg_00008_00003;


// end JJ: 3

// begin JJ: 2
 PowcrcMult PowcrcMult_00008_00002(
                   .prdct_z(alpha_pow_gg_00008_00002),
                   .fact_a(alpha_pow_bb0WithI_00008),
                   .fact_b(gg_00007_00002)
                  );


assign gg_00008_00002 = gg_00007_00001 ^ alpha_pow_gg_00008_00002;


// end JJ: 2

// begin JJ: 1
 PowcrcMult PowcrcMult_00008_00001(
                   .prdct_z(alpha_pow_gg_00008_00001),
                   .fact_a(alpha_pow_bb0WithI_00008),
                   .fact_b(gg_00007_00001)
                  );


assign gg_00008_00001 = gg_00007_00000 ^ alpha_pow_gg_00008_00001;


// end JJ: 1

 PowcrcMult PowcrcMult_00008_00000(
                   .prdct_z(alpha_pow_gg_00008_00000),
                   .fact_a(alpha_pow_bb0WithI_00008),
                   .fact_b(gg_00007_00000)
                  );

assign gg_00008_00000 = alpha_pow_gg_00008_00000;

// end II: 8


// begin II: 9
assign bb0WithI_00009 = { {(2*6){1'b0}}, bb0 } + 18'd9 + 18'd63 - 18'd1;

calc_alpha_pow calc_alpha_pow_6_00009_U (
                  .iInput(bb0WithI_00009),
                  .num1(6'd1),
                  .calcAlphaPow(alpha_pow_bb0WithI_00009),
                  .clk(clk),
                  .clr(clr),
                  .rstn(rstn)
                  );



             assign alpha_pow_gg_00009_00008 = alpha_pow_bb0WithI_00009;


assign gg_00009_00008 = gg_00008_00007 ^ alpha_pow_gg_00009_00008;


// end JJ: 8

// begin JJ: 7
 PowcrcMult PowcrcMult_00009_00007(
                   .prdct_z(alpha_pow_gg_00009_00007),
                   .fact_a(alpha_pow_bb0WithI_00009),
                   .fact_b(gg_00008_00007)
                  );


assign gg_00009_00007 = gg_00008_00006 ^ alpha_pow_gg_00009_00007;


// end JJ: 7

// begin JJ: 6
 PowcrcMult PowcrcMult_00009_00006(
                   .prdct_z(alpha_pow_gg_00009_00006),
                   .fact_a(alpha_pow_bb0WithI_00009),
                   .fact_b(gg_00008_00006)
                  );


assign gg_00009_00006 = gg_00008_00005 ^ alpha_pow_gg_00009_00006;


// end JJ: 6

// begin JJ: 5
 PowcrcMult PowcrcMult_00009_00005(
                   .prdct_z(alpha_pow_gg_00009_00005),
                   .fact_a(alpha_pow_bb0WithI_00009),
                   .fact_b(gg_00008_00005)
                  );


assign gg_00009_00005 = gg_00008_00004 ^ alpha_pow_gg_00009_00005;


// end JJ: 5

// begin JJ: 4
 PowcrcMult PowcrcMult_00009_00004(
                   .prdct_z(alpha_pow_gg_00009_00004),
                   .fact_a(alpha_pow_bb0WithI_00009),
                   .fact_b(gg_00008_00004)
                  );


assign gg_00009_00004 = gg_00008_00003 ^ alpha_pow_gg_00009_00004;


// end JJ: 4

// begin JJ: 3
 PowcrcMult PowcrcMult_00009_00003(
                   .prdct_z(alpha_pow_gg_00009_00003),
                   .fact_a(alpha_pow_bb0WithI_00009),
                   .fact_b(gg_00008_00003)
                  );


assign gg_00009_00003 = gg_00008_00002 ^ alpha_pow_gg_00009_00003;


// end JJ: 3

// begin JJ: 2
 PowcrcMult PowcrcMult_00009_00002(
                   .prdct_z(alpha_pow_gg_00009_00002),
                   .fact_a(alpha_pow_bb0WithI_00009),
                   .fact_b(gg_00008_00002)
                  );


assign gg_00009_00002 = gg_00008_00001 ^ alpha_pow_gg_00009_00002;


// end JJ: 2

// begin JJ: 1
 PowcrcMult PowcrcMult_00009_00001(
                   .prdct_z(alpha_pow_gg_00009_00001),
                   .fact_a(alpha_pow_bb0WithI_00009),
                   .fact_b(gg_00008_00001)
                  );


assign gg_00009_00001 = gg_00008_00000 ^ alpha_pow_gg_00009_00001;


// end JJ: 1

 PowcrcMult PowcrcMult_00009_00000(
                   .prdct_z(alpha_pow_gg_00009_00000),
                   .fact_a(alpha_pow_bb0WithI_00009),
                   .fact_b(gg_00008_00000)
                  );

assign gg_00009_00000 = alpha_pow_gg_00009_00000;

// end II: 9


// begin II: 10
assign bb0WithI_00010 = { {(2*6){1'b0}}, bb0 } + 18'd10 + 18'd63 - 18'd1;

calc_alpha_pow calc_alpha_pow_6_00010_U (
                  .iInput(bb0WithI_00010),
                  .num1(6'd1),
                  .calcAlphaPow(alpha_pow_bb0WithI_00010),
                  .clk(clk),
                  .clr(clr),
                  .rstn(rstn)
                  );



             assign alpha_pow_gg_00010_00009 = alpha_pow_bb0WithI_00010;


assign gg_00010_00009 = gg_00009_00008 ^ alpha_pow_gg_00010_00009;


// end JJ: 9

// begin JJ: 8
 PowcrcMult PowcrcMult_00010_00008(
                   .prdct_z(alpha_pow_gg_00010_00008),
                   .fact_a(alpha_pow_bb0WithI_00010),
                   .fact_b(gg_00009_00008)
                  );


assign gg_00010_00008 = gg_00009_00007 ^ alpha_pow_gg_00010_00008;


// end JJ: 8

// begin JJ: 7
 PowcrcMult PowcrcMult_00010_00007(
                   .prdct_z(alpha_pow_gg_00010_00007),
                   .fact_a(alpha_pow_bb0WithI_00010),
                   .fact_b(gg_00009_00007)
                  );


assign gg_00010_00007 = gg_00009_00006 ^ alpha_pow_gg_00010_00007;


// end JJ: 7

// begin JJ: 6
 PowcrcMult PowcrcMult_00010_00006(
                   .prdct_z(alpha_pow_gg_00010_00006),
                   .fact_a(alpha_pow_bb0WithI_00010),
                   .fact_b(gg_00009_00006)
                  );


assign gg_00010_00006 = gg_00009_00005 ^ alpha_pow_gg_00010_00006;


// end JJ: 6

// begin JJ: 5
 PowcrcMult PowcrcMult_00010_00005(
                   .prdct_z(alpha_pow_gg_00010_00005),
                   .fact_a(alpha_pow_bb0WithI_00010),
                   .fact_b(gg_00009_00005)
                  );


assign gg_00010_00005 = gg_00009_00004 ^ alpha_pow_gg_00010_00005;


// end JJ: 5

// begin JJ: 4
 PowcrcMult PowcrcMult_00010_00004(
                   .prdct_z(alpha_pow_gg_00010_00004),
                   .fact_a(alpha_pow_bb0WithI_00010),
                   .fact_b(gg_00009_00004)
                  );


assign gg_00010_00004 = gg_00009_00003 ^ alpha_pow_gg_00010_00004;


// end JJ: 4

// begin JJ: 3
 PowcrcMult PowcrcMult_00010_00003(
                   .prdct_z(alpha_pow_gg_00010_00003),
                   .fact_a(alpha_pow_bb0WithI_00010),
                   .fact_b(gg_00009_00003)
                  );


assign gg_00010_00003 = gg_00009_00002 ^ alpha_pow_gg_00010_00003;


// end JJ: 3

// begin JJ: 2
 PowcrcMult PowcrcMult_00010_00002(
                   .prdct_z(alpha_pow_gg_00010_00002),
                   .fact_a(alpha_pow_bb0WithI_00010),
                   .fact_b(gg_00009_00002)
                  );


assign gg_00010_00002 = gg_00009_00001 ^ alpha_pow_gg_00010_00002;


// end JJ: 2

// begin JJ: 1
 PowcrcMult PowcrcMult_00010_00001(
                   .prdct_z(alpha_pow_gg_00010_00001),
                   .fact_a(alpha_pow_bb0WithI_00010),
                   .fact_b(gg_00009_00001)
                  );


assign gg_00010_00001 = gg_00009_00000 ^ alpha_pow_gg_00010_00001;


// end JJ: 1

 PowcrcMult PowcrcMult_00010_00000(
                   .prdct_z(alpha_pow_gg_00010_00000),
                   .fact_a(alpha_pow_bb0WithI_00010),
                   .fact_b(gg_00009_00000)
                  );

assign gg_00010_00000 = alpha_pow_gg_00010_00000;

// end II: 10

//END:

//BEGIN:

assign gg_00000 =
                         (PARAM_t2_lower == 0) ? gg_00000_00000 :

                         (PARAM_t2_lower == 1) ? gg_00001_00000 :

                         (PARAM_t2_lower == 2) ? gg_00002_00000 :

                         (PARAM_t2_lower == 3) ? gg_00003_00000 :

                         (PARAM_t2_lower == 4) ? gg_00004_00000 :

                         (PARAM_t2_lower == 5) ? gg_00005_00000 :

                         (PARAM_t2_lower == 6) ? gg_00006_00000 :

                         (PARAM_t2_lower == 7) ? gg_00007_00000 :

                         (PARAM_t2_lower == 8) ? gg_00008_00000 :

                         (PARAM_t2_lower == 9) ? gg_00009_00000 :

                         (PARAM_t2_lower == 10) ? gg_00010_00000 :

                           6'h0;

assign gg_00001 =
                         (PARAM_t2_lower == 1) ? gg_00001_00001 :

                         (PARAM_t2_lower == 2) ? gg_00002_00001 :

                         (PARAM_t2_lower == 3) ? gg_00003_00001 :

                         (PARAM_t2_lower == 4) ? gg_00004_00001 :

                         (PARAM_t2_lower == 5) ? gg_00005_00001 :

                         (PARAM_t2_lower == 6) ? gg_00006_00001 :

                         (PARAM_t2_lower == 7) ? gg_00007_00001 :

                         (PARAM_t2_lower == 8) ? gg_00008_00001 :

                         (PARAM_t2_lower == 9) ? gg_00009_00001 :

                         (PARAM_t2_lower == 10) ? gg_00010_00001 :

                           6'h0;

assign gg_00002 =
                         (PARAM_t2_lower == 2) ? gg_00002_00002 :

                         (PARAM_t2_lower == 3) ? gg_00003_00002 :

                         (PARAM_t2_lower == 4) ? gg_00004_00002 :

                         (PARAM_t2_lower == 5) ? gg_00005_00002 :

                         (PARAM_t2_lower == 6) ? gg_00006_00002 :

                         (PARAM_t2_lower == 7) ? gg_00007_00002 :

                         (PARAM_t2_lower == 8) ? gg_00008_00002 :

                         (PARAM_t2_lower == 9) ? gg_00009_00002 :

                         (PARAM_t2_lower == 10) ? gg_00010_00002 :

                           6'h0;

assign gg_00003 =
                         (PARAM_t2_lower == 3) ? gg_00003_00003 :

                         (PARAM_t2_lower == 4) ? gg_00004_00003 :

                         (PARAM_t2_lower == 5) ? gg_00005_00003 :

                         (PARAM_t2_lower == 6) ? gg_00006_00003 :

                         (PARAM_t2_lower == 7) ? gg_00007_00003 :

                         (PARAM_t2_lower == 8) ? gg_00008_00003 :

                         (PARAM_t2_lower == 9) ? gg_00009_00003 :

                         (PARAM_t2_lower == 10) ? gg_00010_00003 :

                           6'h0;

assign gg_00004 =
                         (PARAM_t2_lower == 4) ? gg_00004_00004 :

                         (PARAM_t2_lower == 5) ? gg_00005_00004 :

                         (PARAM_t2_lower == 6) ? gg_00006_00004 :

                         (PARAM_t2_lower == 7) ? gg_00007_00004 :

                         (PARAM_t2_lower == 8) ? gg_00008_00004 :

                         (PARAM_t2_lower == 9) ? gg_00009_00004 :

                         (PARAM_t2_lower == 10) ? gg_00010_00004 :

                           6'h0;

assign gg_00005 =
                         (PARAM_t2_lower == 5) ? gg_00005_00005 :

                         (PARAM_t2_lower == 6) ? gg_00006_00005 :

                         (PARAM_t2_lower == 7) ? gg_00007_00005 :

                         (PARAM_t2_lower == 8) ? gg_00008_00005 :

                         (PARAM_t2_lower == 9) ? gg_00009_00005 :

                         (PARAM_t2_lower == 10) ? gg_00010_00005 :

                           6'h0;

assign gg_00006 =
                         (PARAM_t2_lower == 6) ? gg_00006_00006 :

                         (PARAM_t2_lower == 7) ? gg_00007_00006 :

                         (PARAM_t2_lower == 8) ? gg_00008_00006 :

                         (PARAM_t2_lower == 9) ? gg_00009_00006 :

                         (PARAM_t2_lower == 10) ? gg_00010_00006 :

                           6'h0;

assign gg_00007 =
                         (PARAM_t2_lower == 7) ? gg_00007_00007 :

                         (PARAM_t2_lower == 8) ? gg_00008_00007 :

                         (PARAM_t2_lower == 9) ? gg_00009_00007 :

                         (PARAM_t2_lower == 10) ? gg_00010_00007 :

                           6'h0;

assign gg_00008 =
                         (PARAM_t2_lower == 8) ? gg_00008_00008 :

                         (PARAM_t2_lower == 9) ? gg_00009_00008 :

                         (PARAM_t2_lower == 10) ? gg_00010_00008 :

                           6'h0;

assign gg_00009 =
                         (PARAM_t2_lower == 9) ? gg_00009_00009 :

                         (PARAM_t2_lower == 10) ? gg_00010_00009 :

                           6'h0;

assign gg_00010 =
                         (PARAM_t2_lower == 10) ? gg_00010_00010 :

                           6'h0;
//END:



endmodule : sntc_rs_gen_poly
















