//#;; DO NOT EDIT THIS FILE
/*ENCRYPT_ME*/
////////////////////////////////////////////////////////////////////////////////
//# Copyright (c) 2018 Secantec
//# No Permission to modify and distribute this program
//# even if this copyright message remains unaltered.
//#
//# Author: Secantec 27 April, 2018
//# $Id: $//#
//# Revision History
//#       MM      17  April, 2018    Initial release
//#
////////////////////////////////////////////////////////////////////////////////

 /*ENCRYPT_ME*/


//final:MYSEED:600500
//final:PARAM_m:6
//final:PARAM_t:5

// pRev[0]:1
// pRev[1]:0
// pRev[2]:0
// pRev[3]:0
// pRev[4]:0
// pRev[5]:1
// POLY perl :0x3
// pRev[0]:1
// pRev[1]:0
// pRev[2]:0
// pRev[3]:0
// pRev[4]:0
// pRev[5]:1
// POLY perl :0x3

//  PARAM_length 63
//  1


always_comb begin
                      if (0)
                      begin
                      end
                      else if (second_cur_err_cnt_00000_00062 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00001;
                      end
                      else if (second_cur_err_cnt_00001_00000 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00002;
                      end
                      else if (second_cur_err_cnt_00002_00001 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00003;
                      end
                      else if (second_cur_err_cnt_00003_00002 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00004;
                      end
                      else if (second_cur_err_cnt_00004_00003 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00005;
                      end
                      else if (second_cur_err_cnt_00005_00004 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00006;
                      end
                      else if (second_cur_err_cnt_00006_00005 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00007;
                      end
                      else if (second_cur_err_cnt_00007_00006 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00008;
                      end
                      else if (second_cur_err_cnt_00008_00007 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00009;
                      end
                      else if (second_cur_err_cnt_00009_00008 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00010;
                      end
                      else if (second_cur_err_cnt_00010_00009 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00011;
                      end
                      else if (second_cur_err_cnt_00011_00010 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00012;
                      end
                      else if (second_cur_err_cnt_00012_00011 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00013;
                      end
                      else if (second_cur_err_cnt_00013_00012 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00014;
                      end
                      else if (second_cur_err_cnt_00014_00013 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00015;
                      end
                      else if (second_cur_err_cnt_00015_00014 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00016;
                      end
                      else if (second_cur_err_cnt_00016_00015 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00017;
                      end
                      else if (second_cur_err_cnt_00017_00016 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00018;
                      end
                      else if (second_cur_err_cnt_00018_00017 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00019;
                      end
                      else if (second_cur_err_cnt_00019_00018 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00020;
                      end
                      else if (second_cur_err_cnt_00020_00019 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00021;
                      end
                      else if (second_cur_err_cnt_00021_00020 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00022;
                      end
                      else if (second_cur_err_cnt_00022_00021 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00023;
                      end
                      else if (second_cur_err_cnt_00023_00022 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00024;
                      end
                      else if (second_cur_err_cnt_00024_00023 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00025;
                      end
                      else if (second_cur_err_cnt_00025_00024 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00026;
                      end
                      else if (second_cur_err_cnt_00026_00025 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00027;
                      end
                      else if (second_cur_err_cnt_00027_00026 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00028;
                      end
                      else if (second_cur_err_cnt_00028_00027 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00029;
                      end
                      else if (second_cur_err_cnt_00029_00028 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00030;
                      end
                      else if (second_cur_err_cnt_00030_00029 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00031;
                      end
                      else if (second_cur_err_cnt_00031_00030 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00032;
                      end
                      else if (second_cur_err_cnt_00032_00031 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00033;
                      end
                      else if (second_cur_err_cnt_00033_00032 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00034;
                      end
                      else if (second_cur_err_cnt_00034_00033 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00035;
                      end
                      else if (second_cur_err_cnt_00035_00034 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00036;
                      end
                      else if (second_cur_err_cnt_00036_00035 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00037;
                      end
                      else if (second_cur_err_cnt_00037_00036 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00038;
                      end
                      else if (second_cur_err_cnt_00038_00037 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00039;
                      end
                      else if (second_cur_err_cnt_00039_00038 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00040;
                      end
                      else if (second_cur_err_cnt_00040_00039 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00041;
                      end
                      else if (second_cur_err_cnt_00041_00040 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00042;
                      end
                      else if (second_cur_err_cnt_00042_00041 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00043;
                      end
                      else if (second_cur_err_cnt_00043_00042 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00044;
                      end
                      else if (second_cur_err_cnt_00044_00043 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00045;
                      end
                      else if (second_cur_err_cnt_00045_00044 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00046;
                      end
                      else if (second_cur_err_cnt_00046_00045 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00047;
                      end
                      else if (second_cur_err_cnt_00047_00046 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00048;
                      end
                      else if (second_cur_err_cnt_00048_00047 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00049;
                      end
                      else if (second_cur_err_cnt_00049_00048 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00050;
                      end
                      else if (second_cur_err_cnt_00050_00049 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00051;
                      end
                      else if (second_cur_err_cnt_00051_00050 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00052;
                      end
                      else if (second_cur_err_cnt_00052_00051 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00053;
                      end
                      else if (second_cur_err_cnt_00053_00052 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00054;
                      end
                      else if (second_cur_err_cnt_00054_00053 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00055;
                      end
                      else if (second_cur_err_cnt_00055_00054 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00056;
                      end
                      else if (second_cur_err_cnt_00056_00055 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00057;
                      end
                      else if (second_cur_err_cnt_00057_00056 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00058;
                      end
                      else if (second_cur_err_cnt_00058_00057 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00059;
                      end
                      else if (second_cur_err_cnt_00059_00058 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00060;
                      end
                      else if (second_cur_err_cnt_00060_00059 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00061;
                      end
                      else if (second_cur_err_cnt_00061_00060 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00062;
                      end
                      else if (second_cur_err_cnt_00062_00061 == 1)
                      begin
                          root_err_arr_00001 =  root_i_val_w_00063;
                      end
                      else begin
                          root_err_arr_00001 =  0;
                      end
                      if (0)
                      begin
                      end
                      else if (second_cur_err_cnt_00000_00062 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00001;
                      end
                      else if (second_cur_err_cnt_00001_00000 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00002;
                      end
                      else if (second_cur_err_cnt_00002_00001 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00003;
                      end
                      else if (second_cur_err_cnt_00003_00002 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00004;
                      end
                      else if (second_cur_err_cnt_00004_00003 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00005;
                      end
                      else if (second_cur_err_cnt_00005_00004 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00006;
                      end
                      else if (second_cur_err_cnt_00006_00005 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00007;
                      end
                      else if (second_cur_err_cnt_00007_00006 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00008;
                      end
                      else if (second_cur_err_cnt_00008_00007 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00009;
                      end
                      else if (second_cur_err_cnt_00009_00008 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00010;
                      end
                      else if (second_cur_err_cnt_00010_00009 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00011;
                      end
                      else if (second_cur_err_cnt_00011_00010 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00012;
                      end
                      else if (second_cur_err_cnt_00012_00011 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00013;
                      end
                      else if (second_cur_err_cnt_00013_00012 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00014;
                      end
                      else if (second_cur_err_cnt_00014_00013 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00015;
                      end
                      else if (second_cur_err_cnt_00015_00014 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00016;
                      end
                      else if (second_cur_err_cnt_00016_00015 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00017;
                      end
                      else if (second_cur_err_cnt_00017_00016 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00018;
                      end
                      else if (second_cur_err_cnt_00018_00017 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00019;
                      end
                      else if (second_cur_err_cnt_00019_00018 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00020;
                      end
                      else if (second_cur_err_cnt_00020_00019 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00021;
                      end
                      else if (second_cur_err_cnt_00021_00020 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00022;
                      end
                      else if (second_cur_err_cnt_00022_00021 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00023;
                      end
                      else if (second_cur_err_cnt_00023_00022 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00024;
                      end
                      else if (second_cur_err_cnt_00024_00023 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00025;
                      end
                      else if (second_cur_err_cnt_00025_00024 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00026;
                      end
                      else if (second_cur_err_cnt_00026_00025 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00027;
                      end
                      else if (second_cur_err_cnt_00027_00026 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00028;
                      end
                      else if (second_cur_err_cnt_00028_00027 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00029;
                      end
                      else if (second_cur_err_cnt_00029_00028 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00030;
                      end
                      else if (second_cur_err_cnt_00030_00029 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00031;
                      end
                      else if (second_cur_err_cnt_00031_00030 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00032;
                      end
                      else if (second_cur_err_cnt_00032_00031 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00033;
                      end
                      else if (second_cur_err_cnt_00033_00032 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00034;
                      end
                      else if (second_cur_err_cnt_00034_00033 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00035;
                      end
                      else if (second_cur_err_cnt_00035_00034 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00036;
                      end
                      else if (second_cur_err_cnt_00036_00035 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00037;
                      end
                      else if (second_cur_err_cnt_00037_00036 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00038;
                      end
                      else if (second_cur_err_cnt_00038_00037 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00039;
                      end
                      else if (second_cur_err_cnt_00039_00038 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00040;
                      end
                      else if (second_cur_err_cnt_00040_00039 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00041;
                      end
                      else if (second_cur_err_cnt_00041_00040 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00042;
                      end
                      else if (second_cur_err_cnt_00042_00041 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00043;
                      end
                      else if (second_cur_err_cnt_00043_00042 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00044;
                      end
                      else if (second_cur_err_cnt_00044_00043 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00045;
                      end
                      else if (second_cur_err_cnt_00045_00044 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00046;
                      end
                      else if (second_cur_err_cnt_00046_00045 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00047;
                      end
                      else if (second_cur_err_cnt_00047_00046 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00048;
                      end
                      else if (second_cur_err_cnt_00048_00047 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00049;
                      end
                      else if (second_cur_err_cnt_00049_00048 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00050;
                      end
                      else if (second_cur_err_cnt_00050_00049 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00051;
                      end
                      else if (second_cur_err_cnt_00051_00050 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00052;
                      end
                      else if (second_cur_err_cnt_00052_00051 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00053;
                      end
                      else if (second_cur_err_cnt_00053_00052 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00054;
                      end
                      else if (second_cur_err_cnt_00054_00053 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00055;
                      end
                      else if (second_cur_err_cnt_00055_00054 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00056;
                      end
                      else if (second_cur_err_cnt_00056_00055 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00057;
                      end
                      else if (second_cur_err_cnt_00057_00056 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00058;
                      end
                      else if (second_cur_err_cnt_00058_00057 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00059;
                      end
                      else if (second_cur_err_cnt_00059_00058 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00060;
                      end
                      else if (second_cur_err_cnt_00060_00059 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00061;
                      end
                      else if (second_cur_err_cnt_00061_00060 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00062;
                      end
                      else if (second_cur_err_cnt_00062_00061 == 2)
                      begin
                          root_err_arr_00002 =  root_i_val_w_00063;
                      end
                      else begin
                          root_err_arr_00002 =  0;
                      end
                      if (0)
                      begin
                      end
                      else if (second_cur_err_cnt_00000_00062 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00001;
                      end
                      else if (second_cur_err_cnt_00001_00000 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00002;
                      end
                      else if (second_cur_err_cnt_00002_00001 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00003;
                      end
                      else if (second_cur_err_cnt_00003_00002 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00004;
                      end
                      else if (second_cur_err_cnt_00004_00003 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00005;
                      end
                      else if (second_cur_err_cnt_00005_00004 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00006;
                      end
                      else if (second_cur_err_cnt_00006_00005 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00007;
                      end
                      else if (second_cur_err_cnt_00007_00006 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00008;
                      end
                      else if (second_cur_err_cnt_00008_00007 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00009;
                      end
                      else if (second_cur_err_cnt_00009_00008 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00010;
                      end
                      else if (second_cur_err_cnt_00010_00009 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00011;
                      end
                      else if (second_cur_err_cnt_00011_00010 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00012;
                      end
                      else if (second_cur_err_cnt_00012_00011 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00013;
                      end
                      else if (second_cur_err_cnt_00013_00012 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00014;
                      end
                      else if (second_cur_err_cnt_00014_00013 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00015;
                      end
                      else if (second_cur_err_cnt_00015_00014 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00016;
                      end
                      else if (second_cur_err_cnt_00016_00015 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00017;
                      end
                      else if (second_cur_err_cnt_00017_00016 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00018;
                      end
                      else if (second_cur_err_cnt_00018_00017 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00019;
                      end
                      else if (second_cur_err_cnt_00019_00018 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00020;
                      end
                      else if (second_cur_err_cnt_00020_00019 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00021;
                      end
                      else if (second_cur_err_cnt_00021_00020 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00022;
                      end
                      else if (second_cur_err_cnt_00022_00021 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00023;
                      end
                      else if (second_cur_err_cnt_00023_00022 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00024;
                      end
                      else if (second_cur_err_cnt_00024_00023 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00025;
                      end
                      else if (second_cur_err_cnt_00025_00024 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00026;
                      end
                      else if (second_cur_err_cnt_00026_00025 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00027;
                      end
                      else if (second_cur_err_cnt_00027_00026 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00028;
                      end
                      else if (second_cur_err_cnt_00028_00027 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00029;
                      end
                      else if (second_cur_err_cnt_00029_00028 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00030;
                      end
                      else if (second_cur_err_cnt_00030_00029 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00031;
                      end
                      else if (second_cur_err_cnt_00031_00030 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00032;
                      end
                      else if (second_cur_err_cnt_00032_00031 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00033;
                      end
                      else if (second_cur_err_cnt_00033_00032 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00034;
                      end
                      else if (second_cur_err_cnt_00034_00033 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00035;
                      end
                      else if (second_cur_err_cnt_00035_00034 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00036;
                      end
                      else if (second_cur_err_cnt_00036_00035 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00037;
                      end
                      else if (second_cur_err_cnt_00037_00036 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00038;
                      end
                      else if (second_cur_err_cnt_00038_00037 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00039;
                      end
                      else if (second_cur_err_cnt_00039_00038 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00040;
                      end
                      else if (second_cur_err_cnt_00040_00039 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00041;
                      end
                      else if (second_cur_err_cnt_00041_00040 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00042;
                      end
                      else if (second_cur_err_cnt_00042_00041 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00043;
                      end
                      else if (second_cur_err_cnt_00043_00042 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00044;
                      end
                      else if (second_cur_err_cnt_00044_00043 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00045;
                      end
                      else if (second_cur_err_cnt_00045_00044 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00046;
                      end
                      else if (second_cur_err_cnt_00046_00045 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00047;
                      end
                      else if (second_cur_err_cnt_00047_00046 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00048;
                      end
                      else if (second_cur_err_cnt_00048_00047 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00049;
                      end
                      else if (second_cur_err_cnt_00049_00048 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00050;
                      end
                      else if (second_cur_err_cnt_00050_00049 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00051;
                      end
                      else if (second_cur_err_cnt_00051_00050 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00052;
                      end
                      else if (second_cur_err_cnt_00052_00051 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00053;
                      end
                      else if (second_cur_err_cnt_00053_00052 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00054;
                      end
                      else if (second_cur_err_cnt_00054_00053 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00055;
                      end
                      else if (second_cur_err_cnt_00055_00054 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00056;
                      end
                      else if (second_cur_err_cnt_00056_00055 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00057;
                      end
                      else if (second_cur_err_cnt_00057_00056 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00058;
                      end
                      else if (second_cur_err_cnt_00058_00057 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00059;
                      end
                      else if (second_cur_err_cnt_00059_00058 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00060;
                      end
                      else if (second_cur_err_cnt_00060_00059 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00061;
                      end
                      else if (second_cur_err_cnt_00061_00060 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00062;
                      end
                      else if (second_cur_err_cnt_00062_00061 == 3)
                      begin
                          root_err_arr_00003 =  root_i_val_w_00063;
                      end
                      else begin
                          root_err_arr_00003 =  0;
                      end
                      if (0)
                      begin
                      end
                      else if (second_cur_err_cnt_00000_00062 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00001;
                      end
                      else if (second_cur_err_cnt_00001_00000 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00002;
                      end
                      else if (second_cur_err_cnt_00002_00001 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00003;
                      end
                      else if (second_cur_err_cnt_00003_00002 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00004;
                      end
                      else if (second_cur_err_cnt_00004_00003 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00005;
                      end
                      else if (second_cur_err_cnt_00005_00004 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00006;
                      end
                      else if (second_cur_err_cnt_00006_00005 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00007;
                      end
                      else if (second_cur_err_cnt_00007_00006 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00008;
                      end
                      else if (second_cur_err_cnt_00008_00007 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00009;
                      end
                      else if (second_cur_err_cnt_00009_00008 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00010;
                      end
                      else if (second_cur_err_cnt_00010_00009 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00011;
                      end
                      else if (second_cur_err_cnt_00011_00010 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00012;
                      end
                      else if (second_cur_err_cnt_00012_00011 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00013;
                      end
                      else if (second_cur_err_cnt_00013_00012 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00014;
                      end
                      else if (second_cur_err_cnt_00014_00013 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00015;
                      end
                      else if (second_cur_err_cnt_00015_00014 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00016;
                      end
                      else if (second_cur_err_cnt_00016_00015 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00017;
                      end
                      else if (second_cur_err_cnt_00017_00016 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00018;
                      end
                      else if (second_cur_err_cnt_00018_00017 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00019;
                      end
                      else if (second_cur_err_cnt_00019_00018 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00020;
                      end
                      else if (second_cur_err_cnt_00020_00019 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00021;
                      end
                      else if (second_cur_err_cnt_00021_00020 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00022;
                      end
                      else if (second_cur_err_cnt_00022_00021 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00023;
                      end
                      else if (second_cur_err_cnt_00023_00022 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00024;
                      end
                      else if (second_cur_err_cnt_00024_00023 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00025;
                      end
                      else if (second_cur_err_cnt_00025_00024 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00026;
                      end
                      else if (second_cur_err_cnt_00026_00025 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00027;
                      end
                      else if (second_cur_err_cnt_00027_00026 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00028;
                      end
                      else if (second_cur_err_cnt_00028_00027 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00029;
                      end
                      else if (second_cur_err_cnt_00029_00028 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00030;
                      end
                      else if (second_cur_err_cnt_00030_00029 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00031;
                      end
                      else if (second_cur_err_cnt_00031_00030 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00032;
                      end
                      else if (second_cur_err_cnt_00032_00031 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00033;
                      end
                      else if (second_cur_err_cnt_00033_00032 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00034;
                      end
                      else if (second_cur_err_cnt_00034_00033 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00035;
                      end
                      else if (second_cur_err_cnt_00035_00034 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00036;
                      end
                      else if (second_cur_err_cnt_00036_00035 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00037;
                      end
                      else if (second_cur_err_cnt_00037_00036 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00038;
                      end
                      else if (second_cur_err_cnt_00038_00037 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00039;
                      end
                      else if (second_cur_err_cnt_00039_00038 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00040;
                      end
                      else if (second_cur_err_cnt_00040_00039 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00041;
                      end
                      else if (second_cur_err_cnt_00041_00040 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00042;
                      end
                      else if (second_cur_err_cnt_00042_00041 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00043;
                      end
                      else if (second_cur_err_cnt_00043_00042 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00044;
                      end
                      else if (second_cur_err_cnt_00044_00043 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00045;
                      end
                      else if (second_cur_err_cnt_00045_00044 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00046;
                      end
                      else if (second_cur_err_cnt_00046_00045 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00047;
                      end
                      else if (second_cur_err_cnt_00047_00046 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00048;
                      end
                      else if (second_cur_err_cnt_00048_00047 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00049;
                      end
                      else if (second_cur_err_cnt_00049_00048 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00050;
                      end
                      else if (second_cur_err_cnt_00050_00049 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00051;
                      end
                      else if (second_cur_err_cnt_00051_00050 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00052;
                      end
                      else if (second_cur_err_cnt_00052_00051 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00053;
                      end
                      else if (second_cur_err_cnt_00053_00052 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00054;
                      end
                      else if (second_cur_err_cnt_00054_00053 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00055;
                      end
                      else if (second_cur_err_cnt_00055_00054 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00056;
                      end
                      else if (second_cur_err_cnt_00056_00055 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00057;
                      end
                      else if (second_cur_err_cnt_00057_00056 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00058;
                      end
                      else if (second_cur_err_cnt_00058_00057 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00059;
                      end
                      else if (second_cur_err_cnt_00059_00058 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00060;
                      end
                      else if (second_cur_err_cnt_00060_00059 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00061;
                      end
                      else if (second_cur_err_cnt_00061_00060 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00062;
                      end
                      else if (second_cur_err_cnt_00062_00061 == 4)
                      begin
                          root_err_arr_00004 =  root_i_val_w_00063;
                      end
                      else begin
                          root_err_arr_00004 =  0;
                      end
                      if (0)
                      begin
                      end
                      else if (second_cur_err_cnt_00000_00062 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00001;
                      end
                      else if (second_cur_err_cnt_00001_00000 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00002;
                      end
                      else if (second_cur_err_cnt_00002_00001 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00003;
                      end
                      else if (second_cur_err_cnt_00003_00002 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00004;
                      end
                      else if (second_cur_err_cnt_00004_00003 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00005;
                      end
                      else if (second_cur_err_cnt_00005_00004 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00006;
                      end
                      else if (second_cur_err_cnt_00006_00005 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00007;
                      end
                      else if (second_cur_err_cnt_00007_00006 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00008;
                      end
                      else if (second_cur_err_cnt_00008_00007 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00009;
                      end
                      else if (second_cur_err_cnt_00009_00008 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00010;
                      end
                      else if (second_cur_err_cnt_00010_00009 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00011;
                      end
                      else if (second_cur_err_cnt_00011_00010 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00012;
                      end
                      else if (second_cur_err_cnt_00012_00011 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00013;
                      end
                      else if (second_cur_err_cnt_00013_00012 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00014;
                      end
                      else if (second_cur_err_cnt_00014_00013 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00015;
                      end
                      else if (second_cur_err_cnt_00015_00014 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00016;
                      end
                      else if (second_cur_err_cnt_00016_00015 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00017;
                      end
                      else if (second_cur_err_cnt_00017_00016 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00018;
                      end
                      else if (second_cur_err_cnt_00018_00017 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00019;
                      end
                      else if (second_cur_err_cnt_00019_00018 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00020;
                      end
                      else if (second_cur_err_cnt_00020_00019 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00021;
                      end
                      else if (second_cur_err_cnt_00021_00020 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00022;
                      end
                      else if (second_cur_err_cnt_00022_00021 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00023;
                      end
                      else if (second_cur_err_cnt_00023_00022 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00024;
                      end
                      else if (second_cur_err_cnt_00024_00023 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00025;
                      end
                      else if (second_cur_err_cnt_00025_00024 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00026;
                      end
                      else if (second_cur_err_cnt_00026_00025 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00027;
                      end
                      else if (second_cur_err_cnt_00027_00026 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00028;
                      end
                      else if (second_cur_err_cnt_00028_00027 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00029;
                      end
                      else if (second_cur_err_cnt_00029_00028 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00030;
                      end
                      else if (second_cur_err_cnt_00030_00029 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00031;
                      end
                      else if (second_cur_err_cnt_00031_00030 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00032;
                      end
                      else if (second_cur_err_cnt_00032_00031 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00033;
                      end
                      else if (second_cur_err_cnt_00033_00032 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00034;
                      end
                      else if (second_cur_err_cnt_00034_00033 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00035;
                      end
                      else if (second_cur_err_cnt_00035_00034 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00036;
                      end
                      else if (second_cur_err_cnt_00036_00035 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00037;
                      end
                      else if (second_cur_err_cnt_00037_00036 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00038;
                      end
                      else if (second_cur_err_cnt_00038_00037 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00039;
                      end
                      else if (second_cur_err_cnt_00039_00038 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00040;
                      end
                      else if (second_cur_err_cnt_00040_00039 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00041;
                      end
                      else if (second_cur_err_cnt_00041_00040 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00042;
                      end
                      else if (second_cur_err_cnt_00042_00041 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00043;
                      end
                      else if (second_cur_err_cnt_00043_00042 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00044;
                      end
                      else if (second_cur_err_cnt_00044_00043 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00045;
                      end
                      else if (second_cur_err_cnt_00045_00044 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00046;
                      end
                      else if (second_cur_err_cnt_00046_00045 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00047;
                      end
                      else if (second_cur_err_cnt_00047_00046 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00048;
                      end
                      else if (second_cur_err_cnt_00048_00047 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00049;
                      end
                      else if (second_cur_err_cnt_00049_00048 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00050;
                      end
                      else if (second_cur_err_cnt_00050_00049 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00051;
                      end
                      else if (second_cur_err_cnt_00051_00050 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00052;
                      end
                      else if (second_cur_err_cnt_00052_00051 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00053;
                      end
                      else if (second_cur_err_cnt_00053_00052 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00054;
                      end
                      else if (second_cur_err_cnt_00054_00053 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00055;
                      end
                      else if (second_cur_err_cnt_00055_00054 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00056;
                      end
                      else if (second_cur_err_cnt_00056_00055 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00057;
                      end
                      else if (second_cur_err_cnt_00057_00056 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00058;
                      end
                      else if (second_cur_err_cnt_00058_00057 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00059;
                      end
                      else if (second_cur_err_cnt_00059_00058 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00060;
                      end
                      else if (second_cur_err_cnt_00060_00059 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00061;
                      end
                      else if (second_cur_err_cnt_00061_00060 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00062;
                      end
                      else if (second_cur_err_cnt_00062_00061 == 5)
                      begin
                          root_err_arr_00005 =  root_i_val_w_00063;
                      end
                      else begin
                          root_err_arr_00005 =  0;
                      end
end


always_comb begin
   root_reg_i_val_00001  =  root_err_arr_00001;
end
always_comb begin
   root_reg_i_val_00002  =  root_err_arr_00002;
end
always_comb begin
   root_reg_i_val_00003  =  root_err_arr_00003;
end
always_comb begin
   root_reg_i_val_00004  =  root_err_arr_00004;
end
always_comb begin
   root_reg_i_val_00005  =  root_err_arr_00005;
end




//END:



// CCCC primitive_P(x) = 1100001// CCCC 
// CCCC Pass Enter code length:59 (31 < length <= 63): 
