//#;; DO NOT EDIT THIS FILE
/*ENCRYPT_ME*/
////////////////////////////////////////////////////////////////////////////////
//# Copyright (c) 2018 Secantec
//# No Permission to modify and distribute this program
//# even if this copyright message remains unaltered.
//#
//# Author: Secantec 27 April, 2018
//# $Id: $//#
//# Revision History
//#       MM      17  April, 2018    Initial release
//#
////////////////////////////////////////////////////////////////////////////////

 /*ENCRYPT_ME*/


//final:MYSEED:600500
//final:PARAM_m:6
//final:PARAM_t:5

// pRev[0]:1
// pRev[1]:0
// pRev[2]:0
// pRev[3]:0
// pRev[4]:0
// pRev[5]:1
// POLY perl :0x3
// pRev[0]:1
// pRev[1]:0
// pRev[2]:0
// pRev[3]:0
// pRev[4]:0
// pRev[5]:1
// POLY perl :0x3

//  PARAM_length 63
//  1
















/* verilator lint_off DECLFILENAME */
(* keep_hierarchy = "yes" *) (* keep = "true" *) module sntc_chien_single_engine#(
 parameter PARAM_m = 6,
 parameter PARAM_nn1 = 63,
 parameter PARAM_reduced_n = 63,
 parameter PARAM_t = 5,
 parameter PARAM_t2 = 10,
 parameter PARAM_d = 11,
 parameter PARAM_w = 6,
 parameter PARAM_width_w = $clog2(PARAM_nn1+1),
 parameter PARAM_states = 5,
 parameter PARAM_START_VAL = 1,
 parameter PARAM_INST_NUM = 1,
 parameter PARAM_states_w = $clog2(PARAM_states+1)
) (

input [PARAM_w-1:0] sigma_arr_i_00001,
input [PARAM_w-1:0] sigma_arr_i_00002,
input [PARAM_w-1:0] sigma_arr_i_00003,
input [PARAM_w-1:0] sigma_arr_i_00004,
input [PARAM_w-1:0] sigma_arr_i_00005,
input wire start_engine_w,
input wire start_engine_w_pre_pulse,

input wire start_00000,
input wire start_00001,
input wire start_00002,
input wire start_00003,
input wire start_all,
input wire start_all_end,

/* verilator lint_off UNUSED */
input [6-1:0] root_start_val,
/* verilator lint_on UNUSED */

input wire last_inst,
output wire [PARAM_w-1:0] q_output,
output wire [PARAM_w-1:0] root_i_val_out,
output wire [PARAM_w-1:0] loc_i_val_out,

input wire [PARAM_w-1:0] i_val_mult_j_00001_00000,
input wire [PARAM_w-1:0] i_val_mult_j_00002_00000,
input wire [PARAM_w-1:0] i_val_mult_j_00003_00000,
input wire [PARAM_w-1:0] i_val_mult_j_00004_00000,
input wire [PARAM_w-1:0] i_val_mult_j_00005_00000,

/* verilator lint_off UNUSED */
input wire [PARAM_w-1:0] end_root_val,
/* verilator lint_on UNUSED */

output reg valid,
output wire err_q_output,
input rstn,
input clr,

input clk
);




/* verilator lint_off UNUSED */
reg  valid_reg;
reg  start_engine_end_pulse;
/* verilator lint_on UNUSED */


reg [PARAM_w+1:0] root_mult_00001_00000;
reg [PARAM_w  :0] root_mult_00001_00000_wire_int;
reg [PARAM_w-1:0] root_mult_00001_00000_wire;
reg [PARAM_w+1:0] reg_root_mult_00001_00000;

reg [PARAM_w+1:0] root_mult_00002_00000;
reg [PARAM_w  :0] root_mult_00002_00000_wire_int;
reg [PARAM_w-1:0] root_mult_00002_00000_wire;
reg [PARAM_w+1:0] reg_root_mult_00002_00000;

reg [PARAM_w+1:0] root_mult_00003_00000;
reg [PARAM_w  :0] root_mult_00003_00000_wire_int;
reg [PARAM_w-1:0] root_mult_00003_00000_wire;
reg [PARAM_w+1:0] reg_root_mult_00003_00000;

reg [PARAM_w+1:0] root_mult_00004_00000;
reg [PARAM_w  :0] root_mult_00004_00000_wire_int;
reg [PARAM_w-1:0] root_mult_00004_00000_wire;
reg [PARAM_w+1:0] reg_root_mult_00004_00000;

reg [PARAM_w+1:0] root_mult_00005_00000;
reg [PARAM_w  :0] root_mult_00005_00000_wire_int;
reg [PARAM_w-1:0] root_mult_00005_00000_wire;
reg [PARAM_w+1:0] reg_root_mult_00005_00000;




reg [PARAM_w-1:0] sigma_arr_00001_reg_00000;
reg [PARAM_w-1:0] sigma_arr_00002_reg_00000;
reg [PARAM_w-1:0] sigma_arr_00003_reg_00000;
reg [PARAM_w-1:0] sigma_arr_00004_reg_00000;
reg [PARAM_w-1:0] sigma_arr_00005_reg_00000;
reg [PARAM_w-1:0] sigma_arr_00001_reg_00001;
reg [PARAM_w-1:0] sigma_arr_00002_reg_00001;
reg [PARAM_w-1:0] sigma_arr_00003_reg_00001;
reg [PARAM_w-1:0] sigma_arr_00004_reg_00001;
reg [PARAM_w-1:0] sigma_arr_00005_reg_00001;



wire [PARAM_w-1:0] sigma_arr_00001_wire;
wire [PARAM_w-1:0] sigma_arr_00002_wire;
wire [PARAM_w-1:0] sigma_arr_00003_wire;
wire [PARAM_w-1:0] sigma_arr_00004_wire;
wire [PARAM_w-1:0] sigma_arr_00005_wire;


wire start;





always_comb begin
       sigma_arr_00001_reg_00000 = sigma_arr_i_00001;
end
always_comb begin
       sigma_arr_00002_reg_00000 = sigma_arr_i_00002;
end
always_comb begin
       sigma_arr_00003_reg_00000 = sigma_arr_i_00003;
end
always_comb begin
       sigma_arr_00004_reg_00000 = sigma_arr_i_00004;
end
always_comb begin
       sigma_arr_00005_reg_00000 = sigma_arr_i_00005;
end
always_comb begin
       sigma_arr_00001_reg_00001 = sigma_arr_00001_reg_00000;
end
always_comb begin
       sigma_arr_00002_reg_00001 = sigma_arr_00002_reg_00000;
end
always_comb begin
       sigma_arr_00003_reg_00001 = sigma_arr_00003_reg_00000;
end
always_comb begin
       sigma_arr_00004_reg_00001 = sigma_arr_00004_reg_00000;
end
always_comb begin
       sigma_arr_00005_reg_00001 = sigma_arr_00005_reg_00000;
end




assign start = start_engine_w;



always_comb
begin
                             root_mult_00001_00000 = {2'b0,i_val_mult_j_00001_00000};
                             root_mult_00002_00000 = {2'b0,i_val_mult_j_00002_00000};
                             root_mult_00003_00000 = {2'b0,i_val_mult_j_00003_00000};
                             root_mult_00004_00000 = {2'b0,i_val_mult_j_00004_00000};
                             root_mult_00005_00000 = {2'b0,i_val_mult_j_00005_00000};
end
















wire [PARAM_w-1:0] i_output_00001;
wire [PARAM_w-1:0] i_output_00002;
wire [PARAM_w-1:0] i_output_00003;
wire [PARAM_w-1:0] i_output_00004;
wire [PARAM_w-1:0] i_output_00005;




assign err_q_output = (q_output == {PARAM_m{1'b0}}) && start_all_end;

// if q_output is zero then it is a root
assign q_output =
          i_output_00001 ^
          i_output_00002 ^
          i_output_00003 ^
          i_output_00004 ^
          i_output_00005 ^
          {{(PARAM_w-1){1'b0}},1'b1};






assign root_i_val_out = err_q_output ? root_mult_00001_00000_wire : {PARAM_w{1'b0}};

assign loc_i_val_out  = 6'd63 - root_i_val_out;

assign sigma_arr_00001_wire =
               sigma_arr_i_00001;
assign sigma_arr_00002_wire =
               sigma_arr_i_00002;
assign sigma_arr_00003_wire =
               sigma_arr_i_00003;
assign sigma_arr_00004_wire =
               sigma_arr_i_00004;
assign sigma_arr_00005_wire =
               sigma_arr_i_00005;




(* keep_hierarchy = "yes" *) calc_alpha_pow Mcalc_alpha_pow_00001_00001_U (
                  .iInput({{(2*6){1'b0}}, root_mult_00001_00000_wire}), //alpha_to
                  .num1(sigma_arr_00001_wire), //number to be multiplied
                  .calcAlphaPow(i_output_00001),
                  .rstn(rstn),
                  .clr(clr),
                  .clk(clk)
                  );

(* keep_hierarchy = "yes" *) calc_alpha_pow Mcalc_alpha_pow_00002_00002_U (
                  .iInput({{(2*6){1'b0}}, root_mult_00002_00000_wire}), //alpha_to
                  .num1(sigma_arr_00002_wire), //number to be multiplied
                  .calcAlphaPow(i_output_00002),
                  .rstn(rstn),
                  .clr(clr),
                  .clk(clk)
                  );

(* keep_hierarchy = "yes" *) calc_alpha_pow Mcalc_alpha_pow_00003_00003_U (
                  .iInput({{(2*6){1'b0}}, root_mult_00003_00000_wire}), //alpha_to
                  .num1(sigma_arr_00003_wire), //number to be multiplied
                  .calcAlphaPow(i_output_00003),
                  .rstn(rstn),
                  .clr(clr),
                  .clk(clk)
                  );

(* keep_hierarchy = "yes" *) calc_alpha_pow Mcalc_alpha_pow_00004_00004_U (
                  .iInput({{(2*6){1'b0}}, root_mult_00004_00000_wire}), //alpha_to
                  .num1(sigma_arr_00004_wire), //number to be multiplied
                  .calcAlphaPow(i_output_00004),
                  .rstn(rstn),
                  .clr(clr),
                  .clk(clk)
                  );

(* keep_hierarchy = "yes" *) calc_alpha_pow Mcalc_alpha_pow_00005_00005_U (
                  .iInput({{(2*6){1'b0}}, root_mult_00005_00000_wire}), //alpha_to
                  .num1(sigma_arr_00005_wire), //number to be multiplied
                  .calcAlphaPow(i_output_00005),
                  .rstn(rstn),
                  .clr(clr),
                  .clk(clk)
                  );



always_comb root_mult_00001_00000_wire_int =
                                  root_mult_00001_00000[(6-1):0] +
                                  root_mult_00001_00000[(6+1):(6)] ;

always_comb root_mult_00001_00000_wire =
                                  root_mult_00001_00000_wire_int[(6-1):0] +
                                  root_mult_00001_00000_wire_int[(6)] ;


always_comb root_mult_00002_00000_wire_int =
                                  root_mult_00002_00000[(6-1):0] +
                                  root_mult_00002_00000[(6+1):(6)] ;

always_comb root_mult_00002_00000_wire =
                                  root_mult_00002_00000_wire_int[(6-1):0] +
                                  root_mult_00002_00000_wire_int[(6)] ;


always_comb root_mult_00003_00000_wire_int =
                                  root_mult_00003_00000[(6-1):0] +
                                  root_mult_00003_00000[(6+1):(6)] ;

always_comb root_mult_00003_00000_wire =
                                  root_mult_00003_00000_wire_int[(6-1):0] +
                                  root_mult_00003_00000_wire_int[(6)] ;


always_comb root_mult_00004_00000_wire_int =
                                  root_mult_00004_00000[(6-1):0] +
                                  root_mult_00004_00000[(6+1):(6)] ;

always_comb root_mult_00004_00000_wire =
                                  root_mult_00004_00000_wire_int[(6-1):0] +
                                  root_mult_00004_00000_wire_int[(6)] ;


always_comb root_mult_00005_00000_wire_int =
                                  root_mult_00005_00000[(6-1):0] +
                                  root_mult_00005_00000[(6+1):(6)] ;

always_comb root_mult_00005_00000_wire =
                                  root_mult_00005_00000_wire_int[(6-1):0] +
                                  root_mult_00005_00000_wire_int[(6)] ;



endmodule
















//END:



// CCCC primitive_P(x) = 1100001// CCCC 
// CCCC Pass Enter code length:59 (31 < length <= 63): 
