//#;; DO NOT EDIT THIS FILE
/*ENCRYPT_ME*/
////////////////////////////////////////////////////////////////////////////////
//# Copyright (c) 2018 Secantec
//# No Permission to modify and distribute this program
//# even if this copyright message remains unaltered.
//#
//# Author: Secantec 27 April, 2018
//# $Id: $//#
//# Revision History
//#       MM      17  April, 2018    Initial release
//#
////////////////////////////////////////////////////////////////////////////////

 /*ENCRYPT_ME*/


//final:MYSEED:600500
//final:PARAM_m:6
//final:PARAM_t:5

// pRev[0]:1
// pRev[1]:0
// pRev[2]:0
// pRev[3]:0
// pRev[4]:0
// pRev[5]:1
// POLY perl :0x3
// pRev[0]:1
// pRev[1]:0
// pRev[2]:0
// pRev[3]:0
// pRev[4]:0
// pRev[5]:1
// POLY perl :0x3

//  PARAM_length 63
//  1





genvar gi = 0;
generate
begin
  if (gi) begin
  end
    else if ( PARAM_INST_NUM == 0 ) assign i_val_mult_j_00001_00000 = 6'd 63;
    else if ( PARAM_INST_NUM == 0 ) assign i_val_mult_j_00002_00000 = 6'd 63;
    else if ( PARAM_INST_NUM == 0 ) assign i_val_mult_j_00003_00000 = 6'd 63;
    else if ( PARAM_INST_NUM == 0 ) assign i_val_mult_j_00004_00000 = 6'd 63;
    else if ( PARAM_INST_NUM == 0 ) assign i_val_mult_j_00005_00000 = 6'd 63;
    else if ( PARAM_INST_NUM == 1 ) assign i_val_mult_j_00001_00000 = 6'd 1;
    else if ( PARAM_INST_NUM == 1 ) assign i_val_mult_j_00002_00000 = 6'd 2;
    else if ( PARAM_INST_NUM == 1 ) assign i_val_mult_j_00003_00000 = 6'd 3;
    else if ( PARAM_INST_NUM == 1 ) assign i_val_mult_j_00004_00000 = 6'd 4;
    else if ( PARAM_INST_NUM == 1 ) assign i_val_mult_j_00005_00000 = 6'd 5;
    else if ( PARAM_INST_NUM == 2 ) assign i_val_mult_j_00001_00000 = 6'd 2;
    else if ( PARAM_INST_NUM == 2 ) assign i_val_mult_j_00002_00000 = 6'd 4;
    else if ( PARAM_INST_NUM == 2 ) assign i_val_mult_j_00003_00000 = 6'd 6;
    else if ( PARAM_INST_NUM == 2 ) assign i_val_mult_j_00004_00000 = 6'd 8;
    else if ( PARAM_INST_NUM == 2 ) assign i_val_mult_j_00005_00000 = 6'd 10;
    else if ( PARAM_INST_NUM == 3 ) assign i_val_mult_j_00001_00000 = 6'd 3;
    else if ( PARAM_INST_NUM == 3 ) assign i_val_mult_j_00002_00000 = 6'd 6;
    else if ( PARAM_INST_NUM == 3 ) assign i_val_mult_j_00003_00000 = 6'd 9;
    else if ( PARAM_INST_NUM == 3 ) assign i_val_mult_j_00004_00000 = 6'd 12;
    else if ( PARAM_INST_NUM == 3 ) assign i_val_mult_j_00005_00000 = 6'd 15;
    else if ( PARAM_INST_NUM == 4 ) assign i_val_mult_j_00001_00000 = 6'd 4;
    else if ( PARAM_INST_NUM == 4 ) assign i_val_mult_j_00002_00000 = 6'd 8;
    else if ( PARAM_INST_NUM == 4 ) assign i_val_mult_j_00003_00000 = 6'd 12;
    else if ( PARAM_INST_NUM == 4 ) assign i_val_mult_j_00004_00000 = 6'd 16;
    else if ( PARAM_INST_NUM == 4 ) assign i_val_mult_j_00005_00000 = 6'd 20;
    else if ( PARAM_INST_NUM == 5 ) assign i_val_mult_j_00001_00000 = 6'd 5;
    else if ( PARAM_INST_NUM == 5 ) assign i_val_mult_j_00002_00000 = 6'd 10;
    else if ( PARAM_INST_NUM == 5 ) assign i_val_mult_j_00003_00000 = 6'd 15;
    else if ( PARAM_INST_NUM == 5 ) assign i_val_mult_j_00004_00000 = 6'd 20;
    else if ( PARAM_INST_NUM == 5 ) assign i_val_mult_j_00005_00000 = 6'd 25;
    else if ( PARAM_INST_NUM == 6 ) assign i_val_mult_j_00001_00000 = 6'd 6;
    else if ( PARAM_INST_NUM == 6 ) assign i_val_mult_j_00002_00000 = 6'd 12;
    else if ( PARAM_INST_NUM == 6 ) assign i_val_mult_j_00003_00000 = 6'd 18;
    else if ( PARAM_INST_NUM == 6 ) assign i_val_mult_j_00004_00000 = 6'd 24;
    else if ( PARAM_INST_NUM == 6 ) assign i_val_mult_j_00005_00000 = 6'd 30;
    else if ( PARAM_INST_NUM == 7 ) assign i_val_mult_j_00001_00000 = 6'd 7;
    else if ( PARAM_INST_NUM == 7 ) assign i_val_mult_j_00002_00000 = 6'd 14;
    else if ( PARAM_INST_NUM == 7 ) assign i_val_mult_j_00003_00000 = 6'd 21;
    else if ( PARAM_INST_NUM == 7 ) assign i_val_mult_j_00004_00000 = 6'd 28;
    else if ( PARAM_INST_NUM == 7 ) assign i_val_mult_j_00005_00000 = 6'd 35;
    else if ( PARAM_INST_NUM == 8 ) assign i_val_mult_j_00001_00000 = 6'd 8;
    else if ( PARAM_INST_NUM == 8 ) assign i_val_mult_j_00002_00000 = 6'd 16;
    else if ( PARAM_INST_NUM == 8 ) assign i_val_mult_j_00003_00000 = 6'd 24;
    else if ( PARAM_INST_NUM == 8 ) assign i_val_mult_j_00004_00000 = 6'd 32;
    else if ( PARAM_INST_NUM == 8 ) assign i_val_mult_j_00005_00000 = 6'd 40;
    else if ( PARAM_INST_NUM == 9 ) assign i_val_mult_j_00001_00000 = 6'd 9;
    else if ( PARAM_INST_NUM == 9 ) assign i_val_mult_j_00002_00000 = 6'd 18;
    else if ( PARAM_INST_NUM == 9 ) assign i_val_mult_j_00003_00000 = 6'd 27;
    else if ( PARAM_INST_NUM == 9 ) assign i_val_mult_j_00004_00000 = 6'd 36;
    else if ( PARAM_INST_NUM == 9 ) assign i_val_mult_j_00005_00000 = 6'd 45;
    else if ( PARAM_INST_NUM == 10 ) assign i_val_mult_j_00001_00000 = 6'd 10;
    else if ( PARAM_INST_NUM == 10 ) assign i_val_mult_j_00002_00000 = 6'd 20;
    else if ( PARAM_INST_NUM == 10 ) assign i_val_mult_j_00003_00000 = 6'd 30;
    else if ( PARAM_INST_NUM == 10 ) assign i_val_mult_j_00004_00000 = 6'd 40;
    else if ( PARAM_INST_NUM == 10 ) assign i_val_mult_j_00005_00000 = 6'd 50;
    else if ( PARAM_INST_NUM == 11 ) assign i_val_mult_j_00001_00000 = 6'd 11;
    else if ( PARAM_INST_NUM == 11 ) assign i_val_mult_j_00002_00000 = 6'd 22;
    else if ( PARAM_INST_NUM == 11 ) assign i_val_mult_j_00003_00000 = 6'd 33;
    else if ( PARAM_INST_NUM == 11 ) assign i_val_mult_j_00004_00000 = 6'd 44;
    else if ( PARAM_INST_NUM == 11 ) assign i_val_mult_j_00005_00000 = 6'd 55;
    else if ( PARAM_INST_NUM == 12 ) assign i_val_mult_j_00001_00000 = 6'd 12;
    else if ( PARAM_INST_NUM == 12 ) assign i_val_mult_j_00002_00000 = 6'd 24;
    else if ( PARAM_INST_NUM == 12 ) assign i_val_mult_j_00003_00000 = 6'd 36;
    else if ( PARAM_INST_NUM == 12 ) assign i_val_mult_j_00004_00000 = 6'd 48;
    else if ( PARAM_INST_NUM == 12 ) assign i_val_mult_j_00005_00000 = 6'd 60;
    else if ( PARAM_INST_NUM == 13 ) assign i_val_mult_j_00001_00000 = 6'd 13;
    else if ( PARAM_INST_NUM == 13 ) assign i_val_mult_j_00002_00000 = 6'd 26;
    else if ( PARAM_INST_NUM == 13 ) assign i_val_mult_j_00003_00000 = 6'd 39;
    else if ( PARAM_INST_NUM == 13 ) assign i_val_mult_j_00004_00000 = 6'd 52;
    else if ( PARAM_INST_NUM == 13 ) assign i_val_mult_j_00005_00000 = 6'd 2;
    else if ( PARAM_INST_NUM == 14 ) assign i_val_mult_j_00001_00000 = 6'd 14;
    else if ( PARAM_INST_NUM == 14 ) assign i_val_mult_j_00002_00000 = 6'd 28;
    else if ( PARAM_INST_NUM == 14 ) assign i_val_mult_j_00003_00000 = 6'd 42;
    else if ( PARAM_INST_NUM == 14 ) assign i_val_mult_j_00004_00000 = 6'd 56;
    else if ( PARAM_INST_NUM == 14 ) assign i_val_mult_j_00005_00000 = 6'd 7;
    else if ( PARAM_INST_NUM == 15 ) assign i_val_mult_j_00001_00000 = 6'd 15;
    else if ( PARAM_INST_NUM == 15 ) assign i_val_mult_j_00002_00000 = 6'd 30;
    else if ( PARAM_INST_NUM == 15 ) assign i_val_mult_j_00003_00000 = 6'd 45;
    else if ( PARAM_INST_NUM == 15 ) assign i_val_mult_j_00004_00000 = 6'd 60;
    else if ( PARAM_INST_NUM == 15 ) assign i_val_mult_j_00005_00000 = 6'd 12;
    else if ( PARAM_INST_NUM == 16 ) assign i_val_mult_j_00001_00000 = 6'd 16;
    else if ( PARAM_INST_NUM == 16 ) assign i_val_mult_j_00002_00000 = 6'd 32;
    else if ( PARAM_INST_NUM == 16 ) assign i_val_mult_j_00003_00000 = 6'd 48;
    else if ( PARAM_INST_NUM == 16 ) assign i_val_mult_j_00004_00000 = 6'd 1;
    else if ( PARAM_INST_NUM == 16 ) assign i_val_mult_j_00005_00000 = 6'd 17;
    else if ( PARAM_INST_NUM == 17 ) assign i_val_mult_j_00001_00000 = 6'd 17;
    else if ( PARAM_INST_NUM == 17 ) assign i_val_mult_j_00002_00000 = 6'd 34;
    else if ( PARAM_INST_NUM == 17 ) assign i_val_mult_j_00003_00000 = 6'd 51;
    else if ( PARAM_INST_NUM == 17 ) assign i_val_mult_j_00004_00000 = 6'd 5;
    else if ( PARAM_INST_NUM == 17 ) assign i_val_mult_j_00005_00000 = 6'd 22;
    else if ( PARAM_INST_NUM == 18 ) assign i_val_mult_j_00001_00000 = 6'd 18;
    else if ( PARAM_INST_NUM == 18 ) assign i_val_mult_j_00002_00000 = 6'd 36;
    else if ( PARAM_INST_NUM == 18 ) assign i_val_mult_j_00003_00000 = 6'd 54;
    else if ( PARAM_INST_NUM == 18 ) assign i_val_mult_j_00004_00000 = 6'd 9;
    else if ( PARAM_INST_NUM == 18 ) assign i_val_mult_j_00005_00000 = 6'd 27;
    else if ( PARAM_INST_NUM == 19 ) assign i_val_mult_j_00001_00000 = 6'd 19;
    else if ( PARAM_INST_NUM == 19 ) assign i_val_mult_j_00002_00000 = 6'd 38;
    else if ( PARAM_INST_NUM == 19 ) assign i_val_mult_j_00003_00000 = 6'd 57;
    else if ( PARAM_INST_NUM == 19 ) assign i_val_mult_j_00004_00000 = 6'd 13;
    else if ( PARAM_INST_NUM == 19 ) assign i_val_mult_j_00005_00000 = 6'd 32;
    else if ( PARAM_INST_NUM == 20 ) assign i_val_mult_j_00001_00000 = 6'd 20;
    else if ( PARAM_INST_NUM == 20 ) assign i_val_mult_j_00002_00000 = 6'd 40;
    else if ( PARAM_INST_NUM == 20 ) assign i_val_mult_j_00003_00000 = 6'd 60;
    else if ( PARAM_INST_NUM == 20 ) assign i_val_mult_j_00004_00000 = 6'd 17;
    else if ( PARAM_INST_NUM == 20 ) assign i_val_mult_j_00005_00000 = 6'd 37;
    else if ( PARAM_INST_NUM == 21 ) assign i_val_mult_j_00001_00000 = 6'd 21;
    else if ( PARAM_INST_NUM == 21 ) assign i_val_mult_j_00002_00000 = 6'd 42;
    else if ( PARAM_INST_NUM == 21 ) assign i_val_mult_j_00003_00000 = 6'd 63;
    else if ( PARAM_INST_NUM == 21 ) assign i_val_mult_j_00004_00000 = 6'd 21;
    else if ( PARAM_INST_NUM == 21 ) assign i_val_mult_j_00005_00000 = 6'd 42;
    else if ( PARAM_INST_NUM == 22 ) assign i_val_mult_j_00001_00000 = 6'd 22;
    else if ( PARAM_INST_NUM == 22 ) assign i_val_mult_j_00002_00000 = 6'd 44;
    else if ( PARAM_INST_NUM == 22 ) assign i_val_mult_j_00003_00000 = 6'd 3;
    else if ( PARAM_INST_NUM == 22 ) assign i_val_mult_j_00004_00000 = 6'd 25;
    else if ( PARAM_INST_NUM == 22 ) assign i_val_mult_j_00005_00000 = 6'd 47;
    else if ( PARAM_INST_NUM == 23 ) assign i_val_mult_j_00001_00000 = 6'd 23;
    else if ( PARAM_INST_NUM == 23 ) assign i_val_mult_j_00002_00000 = 6'd 46;
    else if ( PARAM_INST_NUM == 23 ) assign i_val_mult_j_00003_00000 = 6'd 6;
    else if ( PARAM_INST_NUM == 23 ) assign i_val_mult_j_00004_00000 = 6'd 29;
    else if ( PARAM_INST_NUM == 23 ) assign i_val_mult_j_00005_00000 = 6'd 52;
    else if ( PARAM_INST_NUM == 24 ) assign i_val_mult_j_00001_00000 = 6'd 24;
    else if ( PARAM_INST_NUM == 24 ) assign i_val_mult_j_00002_00000 = 6'd 48;
    else if ( PARAM_INST_NUM == 24 ) assign i_val_mult_j_00003_00000 = 6'd 9;
    else if ( PARAM_INST_NUM == 24 ) assign i_val_mult_j_00004_00000 = 6'd 33;
    else if ( PARAM_INST_NUM == 24 ) assign i_val_mult_j_00005_00000 = 6'd 57;
    else if ( PARAM_INST_NUM == 25 ) assign i_val_mult_j_00001_00000 = 6'd 25;
    else if ( PARAM_INST_NUM == 25 ) assign i_val_mult_j_00002_00000 = 6'd 50;
    else if ( PARAM_INST_NUM == 25 ) assign i_val_mult_j_00003_00000 = 6'd 12;
    else if ( PARAM_INST_NUM == 25 ) assign i_val_mult_j_00004_00000 = 6'd 37;
    else if ( PARAM_INST_NUM == 25 ) assign i_val_mult_j_00005_00000 = 6'd 62;
    else if ( PARAM_INST_NUM == 26 ) assign i_val_mult_j_00001_00000 = 6'd 26;
    else if ( PARAM_INST_NUM == 26 ) assign i_val_mult_j_00002_00000 = 6'd 52;
    else if ( PARAM_INST_NUM == 26 ) assign i_val_mult_j_00003_00000 = 6'd 15;
    else if ( PARAM_INST_NUM == 26 ) assign i_val_mult_j_00004_00000 = 6'd 41;
    else if ( PARAM_INST_NUM == 26 ) assign i_val_mult_j_00005_00000 = 6'd 4;
    else if ( PARAM_INST_NUM == 27 ) assign i_val_mult_j_00001_00000 = 6'd 27;
    else if ( PARAM_INST_NUM == 27 ) assign i_val_mult_j_00002_00000 = 6'd 54;
    else if ( PARAM_INST_NUM == 27 ) assign i_val_mult_j_00003_00000 = 6'd 18;
    else if ( PARAM_INST_NUM == 27 ) assign i_val_mult_j_00004_00000 = 6'd 45;
    else if ( PARAM_INST_NUM == 27 ) assign i_val_mult_j_00005_00000 = 6'd 9;
    else if ( PARAM_INST_NUM == 28 ) assign i_val_mult_j_00001_00000 = 6'd 28;
    else if ( PARAM_INST_NUM == 28 ) assign i_val_mult_j_00002_00000 = 6'd 56;
    else if ( PARAM_INST_NUM == 28 ) assign i_val_mult_j_00003_00000 = 6'd 21;
    else if ( PARAM_INST_NUM == 28 ) assign i_val_mult_j_00004_00000 = 6'd 49;
    else if ( PARAM_INST_NUM == 28 ) assign i_val_mult_j_00005_00000 = 6'd 14;
    else if ( PARAM_INST_NUM == 29 ) assign i_val_mult_j_00001_00000 = 6'd 29;
    else if ( PARAM_INST_NUM == 29 ) assign i_val_mult_j_00002_00000 = 6'd 58;
    else if ( PARAM_INST_NUM == 29 ) assign i_val_mult_j_00003_00000 = 6'd 24;
    else if ( PARAM_INST_NUM == 29 ) assign i_val_mult_j_00004_00000 = 6'd 53;
    else if ( PARAM_INST_NUM == 29 ) assign i_val_mult_j_00005_00000 = 6'd 19;
    else if ( PARAM_INST_NUM == 30 ) assign i_val_mult_j_00001_00000 = 6'd 30;
    else if ( PARAM_INST_NUM == 30 ) assign i_val_mult_j_00002_00000 = 6'd 60;
    else if ( PARAM_INST_NUM == 30 ) assign i_val_mult_j_00003_00000 = 6'd 27;
    else if ( PARAM_INST_NUM == 30 ) assign i_val_mult_j_00004_00000 = 6'd 57;
    else if ( PARAM_INST_NUM == 30 ) assign i_val_mult_j_00005_00000 = 6'd 24;
    else if ( PARAM_INST_NUM == 31 ) assign i_val_mult_j_00001_00000 = 6'd 31;
    else if ( PARAM_INST_NUM == 31 ) assign i_val_mult_j_00002_00000 = 6'd 62;
    else if ( PARAM_INST_NUM == 31 ) assign i_val_mult_j_00003_00000 = 6'd 30;
    else if ( PARAM_INST_NUM == 31 ) assign i_val_mult_j_00004_00000 = 6'd 61;
    else if ( PARAM_INST_NUM == 31 ) assign i_val_mult_j_00005_00000 = 6'd 29;
    else if ( PARAM_INST_NUM == 32 ) assign i_val_mult_j_00001_00000 = 6'd 32;
    else if ( PARAM_INST_NUM == 32 ) assign i_val_mult_j_00002_00000 = 6'd 1;
    else if ( PARAM_INST_NUM == 32 ) assign i_val_mult_j_00003_00000 = 6'd 33;
    else if ( PARAM_INST_NUM == 32 ) assign i_val_mult_j_00004_00000 = 6'd 2;
    else if ( PARAM_INST_NUM == 32 ) assign i_val_mult_j_00005_00000 = 6'd 34;
    else if ( PARAM_INST_NUM == 33 ) assign i_val_mult_j_00001_00000 = 6'd 33;
    else if ( PARAM_INST_NUM == 33 ) assign i_val_mult_j_00002_00000 = 6'd 3;
    else if ( PARAM_INST_NUM == 33 ) assign i_val_mult_j_00003_00000 = 6'd 36;
    else if ( PARAM_INST_NUM == 33 ) assign i_val_mult_j_00004_00000 = 6'd 6;
    else if ( PARAM_INST_NUM == 33 ) assign i_val_mult_j_00005_00000 = 6'd 39;
    else if ( PARAM_INST_NUM == 34 ) assign i_val_mult_j_00001_00000 = 6'd 34;
    else if ( PARAM_INST_NUM == 34 ) assign i_val_mult_j_00002_00000 = 6'd 5;
    else if ( PARAM_INST_NUM == 34 ) assign i_val_mult_j_00003_00000 = 6'd 39;
    else if ( PARAM_INST_NUM == 34 ) assign i_val_mult_j_00004_00000 = 6'd 10;
    else if ( PARAM_INST_NUM == 34 ) assign i_val_mult_j_00005_00000 = 6'd 44;
    else if ( PARAM_INST_NUM == 35 ) assign i_val_mult_j_00001_00000 = 6'd 35;
    else if ( PARAM_INST_NUM == 35 ) assign i_val_mult_j_00002_00000 = 6'd 7;
    else if ( PARAM_INST_NUM == 35 ) assign i_val_mult_j_00003_00000 = 6'd 42;
    else if ( PARAM_INST_NUM == 35 ) assign i_val_mult_j_00004_00000 = 6'd 14;
    else if ( PARAM_INST_NUM == 35 ) assign i_val_mult_j_00005_00000 = 6'd 49;
    else if ( PARAM_INST_NUM == 36 ) assign i_val_mult_j_00001_00000 = 6'd 36;
    else if ( PARAM_INST_NUM == 36 ) assign i_val_mult_j_00002_00000 = 6'd 9;
    else if ( PARAM_INST_NUM == 36 ) assign i_val_mult_j_00003_00000 = 6'd 45;
    else if ( PARAM_INST_NUM == 36 ) assign i_val_mult_j_00004_00000 = 6'd 18;
    else if ( PARAM_INST_NUM == 36 ) assign i_val_mult_j_00005_00000 = 6'd 54;
    else if ( PARAM_INST_NUM == 37 ) assign i_val_mult_j_00001_00000 = 6'd 37;
    else if ( PARAM_INST_NUM == 37 ) assign i_val_mult_j_00002_00000 = 6'd 11;
    else if ( PARAM_INST_NUM == 37 ) assign i_val_mult_j_00003_00000 = 6'd 48;
    else if ( PARAM_INST_NUM == 37 ) assign i_val_mult_j_00004_00000 = 6'd 22;
    else if ( PARAM_INST_NUM == 37 ) assign i_val_mult_j_00005_00000 = 6'd 59;
    else if ( PARAM_INST_NUM == 38 ) assign i_val_mult_j_00001_00000 = 6'd 38;
    else if ( PARAM_INST_NUM == 38 ) assign i_val_mult_j_00002_00000 = 6'd 13;
    else if ( PARAM_INST_NUM == 38 ) assign i_val_mult_j_00003_00000 = 6'd 51;
    else if ( PARAM_INST_NUM == 38 ) assign i_val_mult_j_00004_00000 = 6'd 26;
    else if ( PARAM_INST_NUM == 38 ) assign i_val_mult_j_00005_00000 = 6'd 1;
    else if ( PARAM_INST_NUM == 39 ) assign i_val_mult_j_00001_00000 = 6'd 39;
    else if ( PARAM_INST_NUM == 39 ) assign i_val_mult_j_00002_00000 = 6'd 15;
    else if ( PARAM_INST_NUM == 39 ) assign i_val_mult_j_00003_00000 = 6'd 54;
    else if ( PARAM_INST_NUM == 39 ) assign i_val_mult_j_00004_00000 = 6'd 30;
    else if ( PARAM_INST_NUM == 39 ) assign i_val_mult_j_00005_00000 = 6'd 6;
    else if ( PARAM_INST_NUM == 40 ) assign i_val_mult_j_00001_00000 = 6'd 40;
    else if ( PARAM_INST_NUM == 40 ) assign i_val_mult_j_00002_00000 = 6'd 17;
    else if ( PARAM_INST_NUM == 40 ) assign i_val_mult_j_00003_00000 = 6'd 57;
    else if ( PARAM_INST_NUM == 40 ) assign i_val_mult_j_00004_00000 = 6'd 34;
    else if ( PARAM_INST_NUM == 40 ) assign i_val_mult_j_00005_00000 = 6'd 11;
    else if ( PARAM_INST_NUM == 41 ) assign i_val_mult_j_00001_00000 = 6'd 41;
    else if ( PARAM_INST_NUM == 41 ) assign i_val_mult_j_00002_00000 = 6'd 19;
    else if ( PARAM_INST_NUM == 41 ) assign i_val_mult_j_00003_00000 = 6'd 60;
    else if ( PARAM_INST_NUM == 41 ) assign i_val_mult_j_00004_00000 = 6'd 38;
    else if ( PARAM_INST_NUM == 41 ) assign i_val_mult_j_00005_00000 = 6'd 16;
    else if ( PARAM_INST_NUM == 42 ) assign i_val_mult_j_00001_00000 = 6'd 42;
    else if ( PARAM_INST_NUM == 42 ) assign i_val_mult_j_00002_00000 = 6'd 21;
    else if ( PARAM_INST_NUM == 42 ) assign i_val_mult_j_00003_00000 = 6'd 63;
    else if ( PARAM_INST_NUM == 42 ) assign i_val_mult_j_00004_00000 = 6'd 42;
    else if ( PARAM_INST_NUM == 42 ) assign i_val_mult_j_00005_00000 = 6'd 21;
    else if ( PARAM_INST_NUM == 43 ) assign i_val_mult_j_00001_00000 = 6'd 43;
    else if ( PARAM_INST_NUM == 43 ) assign i_val_mult_j_00002_00000 = 6'd 23;
    else if ( PARAM_INST_NUM == 43 ) assign i_val_mult_j_00003_00000 = 6'd 3;
    else if ( PARAM_INST_NUM == 43 ) assign i_val_mult_j_00004_00000 = 6'd 46;
    else if ( PARAM_INST_NUM == 43 ) assign i_val_mult_j_00005_00000 = 6'd 26;
    else if ( PARAM_INST_NUM == 44 ) assign i_val_mult_j_00001_00000 = 6'd 44;
    else if ( PARAM_INST_NUM == 44 ) assign i_val_mult_j_00002_00000 = 6'd 25;
    else if ( PARAM_INST_NUM == 44 ) assign i_val_mult_j_00003_00000 = 6'd 6;
    else if ( PARAM_INST_NUM == 44 ) assign i_val_mult_j_00004_00000 = 6'd 50;
    else if ( PARAM_INST_NUM == 44 ) assign i_val_mult_j_00005_00000 = 6'd 31;
    else if ( PARAM_INST_NUM == 45 ) assign i_val_mult_j_00001_00000 = 6'd 45;
    else if ( PARAM_INST_NUM == 45 ) assign i_val_mult_j_00002_00000 = 6'd 27;
    else if ( PARAM_INST_NUM == 45 ) assign i_val_mult_j_00003_00000 = 6'd 9;
    else if ( PARAM_INST_NUM == 45 ) assign i_val_mult_j_00004_00000 = 6'd 54;
    else if ( PARAM_INST_NUM == 45 ) assign i_val_mult_j_00005_00000 = 6'd 36;
    else if ( PARAM_INST_NUM == 46 ) assign i_val_mult_j_00001_00000 = 6'd 46;
    else if ( PARAM_INST_NUM == 46 ) assign i_val_mult_j_00002_00000 = 6'd 29;
    else if ( PARAM_INST_NUM == 46 ) assign i_val_mult_j_00003_00000 = 6'd 12;
    else if ( PARAM_INST_NUM == 46 ) assign i_val_mult_j_00004_00000 = 6'd 58;
    else if ( PARAM_INST_NUM == 46 ) assign i_val_mult_j_00005_00000 = 6'd 41;
    else if ( PARAM_INST_NUM == 47 ) assign i_val_mult_j_00001_00000 = 6'd 47;
    else if ( PARAM_INST_NUM == 47 ) assign i_val_mult_j_00002_00000 = 6'd 31;
    else if ( PARAM_INST_NUM == 47 ) assign i_val_mult_j_00003_00000 = 6'd 15;
    else if ( PARAM_INST_NUM == 47 ) assign i_val_mult_j_00004_00000 = 6'd 62;
    else if ( PARAM_INST_NUM == 47 ) assign i_val_mult_j_00005_00000 = 6'd 46;
    else if ( PARAM_INST_NUM == 48 ) assign i_val_mult_j_00001_00000 = 6'd 48;
    else if ( PARAM_INST_NUM == 48 ) assign i_val_mult_j_00002_00000 = 6'd 33;
    else if ( PARAM_INST_NUM == 48 ) assign i_val_mult_j_00003_00000 = 6'd 18;
    else if ( PARAM_INST_NUM == 48 ) assign i_val_mult_j_00004_00000 = 6'd 3;
    else if ( PARAM_INST_NUM == 48 ) assign i_val_mult_j_00005_00000 = 6'd 51;
    else if ( PARAM_INST_NUM == 49 ) assign i_val_mult_j_00001_00000 = 6'd 49;
    else if ( PARAM_INST_NUM == 49 ) assign i_val_mult_j_00002_00000 = 6'd 35;
    else if ( PARAM_INST_NUM == 49 ) assign i_val_mult_j_00003_00000 = 6'd 21;
    else if ( PARAM_INST_NUM == 49 ) assign i_val_mult_j_00004_00000 = 6'd 7;
    else if ( PARAM_INST_NUM == 49 ) assign i_val_mult_j_00005_00000 = 6'd 56;
    else if ( PARAM_INST_NUM == 50 ) assign i_val_mult_j_00001_00000 = 6'd 50;
    else if ( PARAM_INST_NUM == 50 ) assign i_val_mult_j_00002_00000 = 6'd 37;
    else if ( PARAM_INST_NUM == 50 ) assign i_val_mult_j_00003_00000 = 6'd 24;
    else if ( PARAM_INST_NUM == 50 ) assign i_val_mult_j_00004_00000 = 6'd 11;
    else if ( PARAM_INST_NUM == 50 ) assign i_val_mult_j_00005_00000 = 6'd 61;
    else if ( PARAM_INST_NUM == 51 ) assign i_val_mult_j_00001_00000 = 6'd 51;
    else if ( PARAM_INST_NUM == 51 ) assign i_val_mult_j_00002_00000 = 6'd 39;
    else if ( PARAM_INST_NUM == 51 ) assign i_val_mult_j_00003_00000 = 6'd 27;
    else if ( PARAM_INST_NUM == 51 ) assign i_val_mult_j_00004_00000 = 6'd 15;
    else if ( PARAM_INST_NUM == 51 ) assign i_val_mult_j_00005_00000 = 6'd 3;
    else if ( PARAM_INST_NUM == 52 ) assign i_val_mult_j_00001_00000 = 6'd 52;
    else if ( PARAM_INST_NUM == 52 ) assign i_val_mult_j_00002_00000 = 6'd 41;
    else if ( PARAM_INST_NUM == 52 ) assign i_val_mult_j_00003_00000 = 6'd 30;
    else if ( PARAM_INST_NUM == 52 ) assign i_val_mult_j_00004_00000 = 6'd 19;
    else if ( PARAM_INST_NUM == 52 ) assign i_val_mult_j_00005_00000 = 6'd 8;
    else if ( PARAM_INST_NUM == 53 ) assign i_val_mult_j_00001_00000 = 6'd 53;
    else if ( PARAM_INST_NUM == 53 ) assign i_val_mult_j_00002_00000 = 6'd 43;
    else if ( PARAM_INST_NUM == 53 ) assign i_val_mult_j_00003_00000 = 6'd 33;
    else if ( PARAM_INST_NUM == 53 ) assign i_val_mult_j_00004_00000 = 6'd 23;
    else if ( PARAM_INST_NUM == 53 ) assign i_val_mult_j_00005_00000 = 6'd 13;
    else if ( PARAM_INST_NUM == 54 ) assign i_val_mult_j_00001_00000 = 6'd 54;
    else if ( PARAM_INST_NUM == 54 ) assign i_val_mult_j_00002_00000 = 6'd 45;
    else if ( PARAM_INST_NUM == 54 ) assign i_val_mult_j_00003_00000 = 6'd 36;
    else if ( PARAM_INST_NUM == 54 ) assign i_val_mult_j_00004_00000 = 6'd 27;
    else if ( PARAM_INST_NUM == 54 ) assign i_val_mult_j_00005_00000 = 6'd 18;
    else if ( PARAM_INST_NUM == 55 ) assign i_val_mult_j_00001_00000 = 6'd 55;
    else if ( PARAM_INST_NUM == 55 ) assign i_val_mult_j_00002_00000 = 6'd 47;
    else if ( PARAM_INST_NUM == 55 ) assign i_val_mult_j_00003_00000 = 6'd 39;
    else if ( PARAM_INST_NUM == 55 ) assign i_val_mult_j_00004_00000 = 6'd 31;
    else if ( PARAM_INST_NUM == 55 ) assign i_val_mult_j_00005_00000 = 6'd 23;
    else if ( PARAM_INST_NUM == 56 ) assign i_val_mult_j_00001_00000 = 6'd 56;
    else if ( PARAM_INST_NUM == 56 ) assign i_val_mult_j_00002_00000 = 6'd 49;
    else if ( PARAM_INST_NUM == 56 ) assign i_val_mult_j_00003_00000 = 6'd 42;
    else if ( PARAM_INST_NUM == 56 ) assign i_val_mult_j_00004_00000 = 6'd 35;
    else if ( PARAM_INST_NUM == 56 ) assign i_val_mult_j_00005_00000 = 6'd 28;
    else if ( PARAM_INST_NUM == 57 ) assign i_val_mult_j_00001_00000 = 6'd 57;
    else if ( PARAM_INST_NUM == 57 ) assign i_val_mult_j_00002_00000 = 6'd 51;
    else if ( PARAM_INST_NUM == 57 ) assign i_val_mult_j_00003_00000 = 6'd 45;
    else if ( PARAM_INST_NUM == 57 ) assign i_val_mult_j_00004_00000 = 6'd 39;
    else if ( PARAM_INST_NUM == 57 ) assign i_val_mult_j_00005_00000 = 6'd 33;
    else if ( PARAM_INST_NUM == 58 ) assign i_val_mult_j_00001_00000 = 6'd 58;
    else if ( PARAM_INST_NUM == 58 ) assign i_val_mult_j_00002_00000 = 6'd 53;
    else if ( PARAM_INST_NUM == 58 ) assign i_val_mult_j_00003_00000 = 6'd 48;
    else if ( PARAM_INST_NUM == 58 ) assign i_val_mult_j_00004_00000 = 6'd 43;
    else if ( PARAM_INST_NUM == 58 ) assign i_val_mult_j_00005_00000 = 6'd 38;
    else if ( PARAM_INST_NUM == 59 ) assign i_val_mult_j_00001_00000 = 6'd 59;
    else if ( PARAM_INST_NUM == 59 ) assign i_val_mult_j_00002_00000 = 6'd 55;
    else if ( PARAM_INST_NUM == 59 ) assign i_val_mult_j_00003_00000 = 6'd 51;
    else if ( PARAM_INST_NUM == 59 ) assign i_val_mult_j_00004_00000 = 6'd 47;
    else if ( PARAM_INST_NUM == 59 ) assign i_val_mult_j_00005_00000 = 6'd 43;
    else if ( PARAM_INST_NUM == 60 ) assign i_val_mult_j_00001_00000 = 6'd 60;
    else if ( PARAM_INST_NUM == 60 ) assign i_val_mult_j_00002_00000 = 6'd 57;
    else if ( PARAM_INST_NUM == 60 ) assign i_val_mult_j_00003_00000 = 6'd 54;
    else if ( PARAM_INST_NUM == 60 ) assign i_val_mult_j_00004_00000 = 6'd 51;
    else if ( PARAM_INST_NUM == 60 ) assign i_val_mult_j_00005_00000 = 6'd 48;
    else if ( PARAM_INST_NUM == 61 ) assign i_val_mult_j_00001_00000 = 6'd 61;
    else if ( PARAM_INST_NUM == 61 ) assign i_val_mult_j_00002_00000 = 6'd 59;
    else if ( PARAM_INST_NUM == 61 ) assign i_val_mult_j_00003_00000 = 6'd 57;
    else if ( PARAM_INST_NUM == 61 ) assign i_val_mult_j_00004_00000 = 6'd 55;
    else if ( PARAM_INST_NUM == 61 ) assign i_val_mult_j_00005_00000 = 6'd 53;
    else if ( PARAM_INST_NUM == 62 ) assign i_val_mult_j_00001_00000 = 6'd 62;
    else if ( PARAM_INST_NUM == 62 ) assign i_val_mult_j_00002_00000 = 6'd 61;
    else if ( PARAM_INST_NUM == 62 ) assign i_val_mult_j_00003_00000 = 6'd 60;
    else if ( PARAM_INST_NUM == 62 ) assign i_val_mult_j_00004_00000 = 6'd 59;
    else if ( PARAM_INST_NUM == 62 ) assign i_val_mult_j_00005_00000 = 6'd 58;
end
endgenerate


generate
begin
  if (gi) begin
  end
  else if ( PARAM_INST_NUM == 0 ) assign end_i_val_mult_j = 6'd1;
  else if ( PARAM_INST_NUM == 1 ) assign end_i_val_mult_j = 6'd2;
  else if ( PARAM_INST_NUM == 2 ) assign end_i_val_mult_j = 6'd3;
  else if ( PARAM_INST_NUM == 3 ) assign end_i_val_mult_j = 6'd4;
  else if ( PARAM_INST_NUM == 4 ) assign end_i_val_mult_j = 6'd5;
  else if ( PARAM_INST_NUM == 5 ) assign end_i_val_mult_j = 6'd6;
  else if ( PARAM_INST_NUM == 6 ) assign end_i_val_mult_j = 6'd7;
  else if ( PARAM_INST_NUM == 7 ) assign end_i_val_mult_j = 6'd8;
  else if ( PARAM_INST_NUM == 8 ) assign end_i_val_mult_j = 6'd9;
  else if ( PARAM_INST_NUM == 9 ) assign end_i_val_mult_j = 6'd10;
  else if ( PARAM_INST_NUM == 10 ) assign end_i_val_mult_j = 6'd11;
  else if ( PARAM_INST_NUM == 11 ) assign end_i_val_mult_j = 6'd12;
  else if ( PARAM_INST_NUM == 12 ) assign end_i_val_mult_j = 6'd13;
  else if ( PARAM_INST_NUM == 13 ) assign end_i_val_mult_j = 6'd14;
  else if ( PARAM_INST_NUM == 14 ) assign end_i_val_mult_j = 6'd15;
  else if ( PARAM_INST_NUM == 15 ) assign end_i_val_mult_j = 6'd16;
  else if ( PARAM_INST_NUM == 16 ) assign end_i_val_mult_j = 6'd17;
  else if ( PARAM_INST_NUM == 17 ) assign end_i_val_mult_j = 6'd18;
  else if ( PARAM_INST_NUM == 18 ) assign end_i_val_mult_j = 6'd19;
  else if ( PARAM_INST_NUM == 19 ) assign end_i_val_mult_j = 6'd20;
  else if ( PARAM_INST_NUM == 20 ) assign end_i_val_mult_j = 6'd21;
  else if ( PARAM_INST_NUM == 21 ) assign end_i_val_mult_j = 6'd22;
  else if ( PARAM_INST_NUM == 22 ) assign end_i_val_mult_j = 6'd23;
  else if ( PARAM_INST_NUM == 23 ) assign end_i_val_mult_j = 6'd24;
  else if ( PARAM_INST_NUM == 24 ) assign end_i_val_mult_j = 6'd25;
  else if ( PARAM_INST_NUM == 25 ) assign end_i_val_mult_j = 6'd26;
  else if ( PARAM_INST_NUM == 26 ) assign end_i_val_mult_j = 6'd27;
  else if ( PARAM_INST_NUM == 27 ) assign end_i_val_mult_j = 6'd28;
  else if ( PARAM_INST_NUM == 28 ) assign end_i_val_mult_j = 6'd29;
  else if ( PARAM_INST_NUM == 29 ) assign end_i_val_mult_j = 6'd30;
  else if ( PARAM_INST_NUM == 30 ) assign end_i_val_mult_j = 6'd31;
  else if ( PARAM_INST_NUM == 31 ) assign end_i_val_mult_j = 6'd32;
  else if ( PARAM_INST_NUM == 32 ) assign end_i_val_mult_j = 6'd33;
  else if ( PARAM_INST_NUM == 33 ) assign end_i_val_mult_j = 6'd34;
  else if ( PARAM_INST_NUM == 34 ) assign end_i_val_mult_j = 6'd35;
  else if ( PARAM_INST_NUM == 35 ) assign end_i_val_mult_j = 6'd36;
  else if ( PARAM_INST_NUM == 36 ) assign end_i_val_mult_j = 6'd37;
  else if ( PARAM_INST_NUM == 37 ) assign end_i_val_mult_j = 6'd38;
  else if ( PARAM_INST_NUM == 38 ) assign end_i_val_mult_j = 6'd39;
  else if ( PARAM_INST_NUM == 39 ) assign end_i_val_mult_j = 6'd40;
  else if ( PARAM_INST_NUM == 40 ) assign end_i_val_mult_j = 6'd41;
  else if ( PARAM_INST_NUM == 41 ) assign end_i_val_mult_j = 6'd42;
  else if ( PARAM_INST_NUM == 42 ) assign end_i_val_mult_j = 6'd43;
  else if ( PARAM_INST_NUM == 43 ) assign end_i_val_mult_j = 6'd44;
  else if ( PARAM_INST_NUM == 44 ) assign end_i_val_mult_j = 6'd45;
  else if ( PARAM_INST_NUM == 45 ) assign end_i_val_mult_j = 6'd46;
  else if ( PARAM_INST_NUM == 46 ) assign end_i_val_mult_j = 6'd47;
  else if ( PARAM_INST_NUM == 47 ) assign end_i_val_mult_j = 6'd48;
  else if ( PARAM_INST_NUM == 48 ) assign end_i_val_mult_j = 6'd49;
  else if ( PARAM_INST_NUM == 49 ) assign end_i_val_mult_j = 6'd50;
  else if ( PARAM_INST_NUM == 50 ) assign end_i_val_mult_j = 6'd51;
  else if ( PARAM_INST_NUM == 51 ) assign end_i_val_mult_j = 6'd52;
  else if ( PARAM_INST_NUM == 52 ) assign end_i_val_mult_j = 6'd53;
  else if ( PARAM_INST_NUM == 53 ) assign end_i_val_mult_j = 6'd54;
  else if ( PARAM_INST_NUM == 54 ) assign end_i_val_mult_j = 6'd55;
  else if ( PARAM_INST_NUM == 55 ) assign end_i_val_mult_j = 6'd56;
  else if ( PARAM_INST_NUM == 56 ) assign end_i_val_mult_j = 6'd57;
  else if ( PARAM_INST_NUM == 57 ) assign end_i_val_mult_j = 6'd58;
  else if ( PARAM_INST_NUM == 58 ) assign end_i_val_mult_j = 6'd59;
  else if ( PARAM_INST_NUM == 59 ) assign end_i_val_mult_j = 6'd60;
  else if ( PARAM_INST_NUM == 60 ) assign end_i_val_mult_j = 6'd61;
  else if ( PARAM_INST_NUM == 61 ) assign end_i_val_mult_j = 6'd62;
  else if ( PARAM_INST_NUM == 62 ) assign end_i_val_mult_j = 6'd63;
end
endgenerate


//END:



// CCCC primitive_P(x) = 1100001// CCCC 
// CCCC Pass Enter code length:59 (31 < length <= 63): 
