//#;; DO NOT EDIT THIS FILE
/*ENCRYPT_ME*/
////////////////////////////////////////////////////////////////////////////////
//# Copyright (c) 2018 Secantec
//# No Permission to modify and distribute this program
//# even if this copyright message remains unaltered.
//#
//# Author: Secantec 27 April, 2018
//# $Id: $//#
//# Revision History
//#       MM      17  April, 2018    Initial release
//#
////////////////////////////////////////////////////////////////////////////////

 /*ENCRYPT_ME*/


//final:MYSEED:600500
//final:PARAM_m:6
//final:PARAM_t:5

// pRev[0]:1
// pRev[1]:0
// pRev[2]:0
// pRev[3]:0
// pRev[4]:0
// pRev[5]:1
// POLY perl :0x3
// pRev[0]:1
// pRev[1]:0
// pRev[2]:0
// pRev[3]:0
// pRev[4]:0
// pRev[5]:1
// POLY perl :0x3

//  PARAM_length 63
//  1



//BEGIN:



/* verilator lint_off DECLFILENAME */
(* keep_hierarchy = "yes" *) (* keep = "true" *) module calc_alpha_pow_6(
                  iInput,
                  num1,
                  calcAlphaPow
/* verilator lint_off UNUSED */
                  ,
                  clk,
                  clr,
                  rstn
/* verilator lint_on UNUSED */
                  );
        parameter  PARAM_POLY_WIDTH = 6;
        parameter  PARAM_w = 6;
        input  [6-1:0] iInput;
        input  [PARAM_POLY_WIDTH-1   :0] num1;
        output [PARAM_POLY_WIDTH-1   :0] calcAlphaPow;
/* verilator lint_off UNUSED */
        input clk;
        input rstn;
        input clr;
/* verilator lint_on UNUSED */








// 1'b1 + 1'b1 + 1'b1 + carry from previous loc
// 3'b100, so 2 extra bits as 1 bit belongs to 6-1

wire [3*6-1:0] iInput_int;
wire [6+1:0] iInput_mm0_W;
wire [6-1:0] iInputW;

assign iInput_int = {{(3*6-6){1'b0}},iInput}; //width matching

assign iInput_mm0_W =
               {2'b00, iInput_int[1*6-1:0*6]} +
               {2'b00, iInput_int[2*6-1:1*6]} +
               {2'b00, iInput_int[3*6-1:2*6]} ;

assign iInputW = iInput_mm0_W[6-1:0] +
                 {{(6-2){1'b0}},iInput_mm0_W[6+1:6]};










             wire [PARAM_w-1:0] mult_z1_00000;
             wire [PARAM_w-1:0] mult_z1_00001;
             wire [PARAM_w-1:0] mult_z1_00002;
             wire [PARAM_w-1:0] mult_z1_00003;
             wire [PARAM_w-1:0] mult_z1_00004;
             wire [PARAM_w-1:0] mult_z1_00005;


             reg [PARAM_w-1:0] mult_a_00000;
             reg [PARAM_w-1:0] mult_a_00001;
             reg [PARAM_w-1:0] mult_a_00002;
             reg [PARAM_w-1:0] mult_a_00003;
             reg [PARAM_w-1:0] mult_a_00004;
             reg [PARAM_w-1:0] mult_a_00005;
             reg [PARAM_w-1:0] mult_a_00006;


always @(*)
begin
     begin
             mult_a_00000 =  num1;
     end
end
always @(*)
begin
     begin
             mult_a_00001 =
                                (iInputW[1-1] == 1'd1)  ?  mult_z1_00000 :
                                                            mult_a_00000 ;
     end
end
always @(*)
begin
     begin
             mult_a_00002 =
                                (iInputW[2-1] == 1'd1)  ?  mult_z1_00001 :
                                                            mult_a_00001 ;
     end
end
always @(*)
begin
     begin
             mult_a_00003 =
                                (iInputW[3-1] == 1'd1)  ?  mult_z1_00002 :
                                                            mult_a_00002 ;
     end
end
always @(*)
begin
     begin
             mult_a_00004 =
                                (iInputW[4-1] == 1'd1)  ?  mult_z1_00003 :
                                                            mult_a_00003 ;
     end
end
always @(*)
begin
     begin
             mult_a_00005 =
                                (iInputW[5-1] == 1'd1)  ?  mult_z1_00004 :
                                                            mult_a_00004 ;
     end
end
always @(*)
begin
     begin
             mult_a_00006 =
                                (iInputW[6-1] == 1'd1)  ?  mult_z1_00005 :
                                                            mult_a_00005 ;
     end
end


(* keep_hierarchy = "yes" *)  PowcrcMult PowcrcMult_00000(
                   .prdct_z(mult_z1_00000),
                   .fact_a(mult_a_00000),
                   .fact_b(6'd2)
                  );

(* keep_hierarchy = "yes" *)  PowcrcMult PowcrcMult_00001(
                   .prdct_z(mult_z1_00001),
                   .fact_a(mult_a_00001),
                   .fact_b(6'd4)
                  );

(* keep_hierarchy = "yes" *)  PowcrcMult PowcrcMult_00002(
                   .prdct_z(mult_z1_00002),
                   .fact_a(mult_a_00002),
                   .fact_b(6'd16)
                  );

(* keep_hierarchy = "yes" *)  PowcrcMult PowcrcMult_00003(
                   .prdct_z(mult_z1_00003),
                   .fact_a(mult_a_00003),
                   .fact_b(6'd12)
                  );

(* keep_hierarchy = "yes" *)  PowcrcMult PowcrcMult_00004(
                   .prdct_z(mult_z1_00004),
                   .fact_a(mult_a_00004),
                   .fact_b(6'd19)
                  );

(* keep_hierarchy = "yes" *)  PowcrcMult PowcrcMult_00005(
                   .prdct_z(mult_z1_00005),
                   .fact_a(mult_a_00005),
                   .fact_b(6'd9)
                  );


assign calcAlphaPow = mult_a_00006;

endmodule









// CCCC primitive_P(x) = 1100001// CCCC 
// CCCC Pass Enter code length:59 (31 < length <= 63): 
