//#;; DO NOT EDIT THIS FILE
/*ENCRYPT_ME*/
////////////////////////////////////////////////////////////////////////////////
//# Copyright (c) 2018 Secantec
//# No Permission to modify and distribute this program
//# even if this copyright message remains unaltered.
//#
//# Author: Secantec 27 April, 2018
//# $Id: $//#
//# Revision History
//#       MM      17  April, 2018    Initial release
//#
////////////////////////////////////////////////////////////////////////////////

// /bin/rm -rf *simv* *csrc* ; perl vpp.pl -perl sntc_berlekamp.1.sv > sntc_berlekamp.1.vpp.sv ; vcs -sverilog -R -debug_all sntc_berlekamp.1.vpp.sv -l sntc_berlekamp.1.vpp.sv.log

 /*ENCRYPT_ME*/

//final:MYSEED:600500
//final:PARAM_m:6
//final:PARAM_t:5

// pRev[0]:1
// pRev[1]:0
// pRev[2]:0
// pRev[3]:0
// pRev[4]:0
// pRev[5]:1
// POLY perl :0x3
// pRev[0]:1
// pRev[1]:0
// pRev[2]:0
// pRev[3]:0
// pRev[4]:0
// pRev[5]:1
// POLY perl :0x3

`define d_m 6













`ifdef SIMULATION
     `ifdef ENCRYPT
          `include "../RELENC/sntc_rs_syn_00001.svp.svp"
     `else
          `include "genSrcRs/rsSyn/sntc_rs_syn_00001.svp.sv"
     `endif
`endif


`ifdef SIMULATION
     `ifdef ENCRYPT
          `include "../RELENC/sntc_rs_syn_00002.svp.svp"
     `else
          `include "genSrcRs/rsSyn/sntc_rs_syn_00002.svp.sv"
     `endif
`endif


`ifdef SIMULATION
     `ifdef ENCRYPT
          `include "../RELENC/sntc_rs_syn_00003.svp.svp"
     `else
          `include "genSrcRs/rsSyn/sntc_rs_syn_00003.svp.sv"
     `endif
`endif


`ifdef SIMULATION
     `ifdef ENCRYPT
          `include "../RELENC/sntc_rs_syn_00004.svp.svp"
     `else
          `include "genSrcRs/rsSyn/sntc_rs_syn_00004.svp.sv"
     `endif
`endif


`ifdef SIMULATION
     `ifdef ENCRYPT
          `include "../RELENC/sntc_rs_syn_00005.svp.svp"
     `else
          `include "genSrcRs/rsSyn/sntc_rs_syn_00005.svp.sv"
     `endif
`endif


`ifdef SIMULATION
     `ifdef ENCRYPT
          `include "../RELENC/sntc_rs_syn_00006.svp.svp"
     `else
          `include "genSrcRs/rsSyn/sntc_rs_syn_00006.svp.sv"
     `endif
`endif


`ifdef SIMULATION
     `ifdef ENCRYPT
          `include "../RELENC/sntc_rs_syn_00007.svp.svp"
     `else
          `include "genSrcRs/rsSyn/sntc_rs_syn_00007.svp.sv"
     `endif
`endif


`ifdef SIMULATION
     `ifdef ENCRYPT
          `include "../RELENC/sntc_rs_syn_00008.svp.svp"
     `else
          `include "genSrcRs/rsSyn/sntc_rs_syn_00008.svp.sv"
     `endif
`endif


`ifdef SIMULATION
     `ifdef ENCRYPT
          `include "../RELENC/sntc_rs_syn_00009.svp.svp"
     `else
          `include "genSrcRs/rsSyn/sntc_rs_syn_00009.svp.sv"
     `endif
`endif


`ifdef SIMULATION
     `ifdef ENCRYPT
          `include "../RELENC/sntc_rs_syn_00010.svp.svp"
     `else
          `include "genSrcRs/rsSyn/sntc_rs_syn_00010.svp.sv"
     `endif
`endif



