//#;; DO NOT EDIT THIS FILE
/*ENCRYPT_ME*/
////////////////////////////////////////////////////////////////////////////////
//# Copyright (c) 2018 Secantec
//# No Permission to modify and distribute this program
//# even if this copyright message remains unaltered.
//#
//# Author: Secantec 27 April, 2018
//# $Id: $//#
//# Revision History
//#       MM      17  April, 2018    Initial release
//#
////////////////////////////////////////////////////////////////////////////////

 /*ENCRYPT_ME*/


//final:MYSEED:600500
//final:PARAM_m:6
//final:PARAM_t:5

// pRev[0]:1
// pRev[1]:0
// pRev[2]:0
// pRev[3]:0
// pRev[4]:0
// pRev[5]:1
// POLY perl :0x3
// pRev[0]:1
// pRev[1]:0
// pRev[2]:0
// pRev[3]:0
// pRev[4]:0
// pRev[5]:1
// POLY perl :0x3



/* verilator lint_off DECLFILENAME */
`ifndef SNTC_LIB_SVP_SV
`define SNTC_LIB_SVP_SV

`define NULL 0




//BEGIN:



(* keep_hierarchy = "yes" *) (* keep = "true" *) module calc_alpha_pow (
                  iInput,
                  num1,
                  calcAlphaPow
                  /* verilator lint_off UNUSED */
                  ,
                  clk,
                  clr,
                  rstn
                  /* verilator lint_on UNUSED */
                  );
        parameter  PARAM_POLY_WIDTH = 6;
        parameter  PARAM_w = 6;
        input  [3*6-1:0] iInput;
        input  [PARAM_POLY_WIDTH-1   :0] num1;
        output [PARAM_POLY_WIDTH-1   :0] calcAlphaPow;
                  /* verilator lint_off UNUSED */
        input clk;
        input rstn;
        input clr;
                  /* verilator lint_on UNUSED */





// 1'b1 + 1'b1 + 1'b1 + carry from previous loc
// 3'b100, so 2 extra bits as 1 bit belongs to 6-1

wire [3*6-1:0] iInput_int;
wire [6+1:0] iInput_mm0_W;
wire [6-1:0] iInputW;

assign iInput_int = {iInput}; //width matching

assign iInput_mm0_W =
               {2'b0, iInput_int[1*6-1:0*6]} +
               {2'b0, iInput_int[2*6-1:1*6]} +
               {2'b0, iInput_int[3*6-1:2*6]} ;

assign iInputW = iInput_mm0_W[6-1:0] +
                 {{(6-2){1'b0}}, iInput_mm0_W[6+1:6]};









             wire [PARAM_w-1:0] mult_z1_00000;
             wire [PARAM_w-1:0] mult_z1_00001;
             wire [PARAM_w-1:0] mult_z1_00002;
             wire [PARAM_w-1:0] mult_z1_00003;
             wire [PARAM_w-1:0] mult_z1_00004;
             wire [PARAM_w-1:0] mult_z1_00005;


             reg [PARAM_w-1:0] mult_a_00000;
             reg [PARAM_w-1:0] mult_a_00001;
             reg [PARAM_w-1:0] mult_a_00002;
             reg [PARAM_w-1:0] mult_a_00003;
             reg [PARAM_w-1:0] mult_a_00004;
             reg [PARAM_w-1:0] mult_a_00005;
             reg [PARAM_w-1:0] mult_a_00006;


always @(*)
begin
     begin
             mult_a_00000 =  num1;
     end
end
always @(*)
begin
     begin
             mult_a_00001 =
                                (iInputW[1-1] == 1'd1)  ?  mult_z1_00000 :
                                                            mult_a_00000 ;
     end
end
always @(*)
begin
     begin
             mult_a_00002 =
                                (iInputW[2-1] == 1'd1)  ?  mult_z1_00001 :
                                                            mult_a_00001 ;
     end
end
always @(*)
begin
     begin
             mult_a_00003 =
                                (iInputW[3-1] == 1'd1)  ?  mult_z1_00002 :
                                                            mult_a_00002 ;
     end
end
always @(*)
begin
     begin
             mult_a_00004 =
                                (iInputW[4-1] == 1'd1)  ?  mult_z1_00003 :
                                                            mult_a_00003 ;
     end
end
always @(*)
begin
     begin
             mult_a_00005 =
                                (iInputW[5-1] == 1'd1)  ?  mult_z1_00004 :
                                                            mult_a_00004 ;
     end
end
always @(*)
begin
     begin
             mult_a_00006 =
                                (iInputW[6-1] == 1'd1)  ?  mult_z1_00005 :
                                                            mult_a_00005 ;
     end
end


 PowcrcMult PowcrcMult_00000(
                   .prdct_z(mult_z1_00000),
                   .fact_a(mult_a_00000),
                   .fact_b(6'd2)
                  );

 PowcrcMult PowcrcMult_00001(
                   .prdct_z(mult_z1_00001),
                   .fact_a(mult_a_00001),
                   .fact_b(6'd4)
                  );

 PowcrcMult PowcrcMult_00002(
                   .prdct_z(mult_z1_00002),
                   .fact_a(mult_a_00002),
                   .fact_b(6'd16)
                  );

 PowcrcMult PowcrcMult_00003(
                   .prdct_z(mult_z1_00003),
                   .fact_a(mult_a_00003),
                   .fact_b(6'd12)
                  );

 PowcrcMult PowcrcMult_00004(
                   .prdct_z(mult_z1_00004),
                   .fact_a(mult_a_00004),
                   .fact_b(6'd19)
                  );

 PowcrcMult PowcrcMult_00005(
                   .prdct_z(mult_z1_00005),
                   .fact_a(mult_a_00005),
                   .fact_b(6'd9)
                  );


assign calcAlphaPow = mult_a_00006;

endmodule


(* keep_hierarchy = "yes" *) (* keep = "true" *) module PowcrcMult(
                   prdct_z,
                   fact_a,
                   fact_b
                  );


  parameter  PARAM_POLY_WIDTH = 6;
  parameter  PARAM_PRIMITIVE_POLY = 3;

    output [PARAM_POLY_WIDTH-1:0] prdct_z;
    input [PARAM_POLY_WIDTH-1:0] fact_a;
    input [PARAM_POLY_WIDTH-1:0] fact_b;

    wire [PARAM_POLY_WIDTH-1:0] out_prdct_z;
    wire [PARAM_POLY_WIDTH-1:0] in_fact_a;
    wire [PARAM_POLY_WIDTH-1:0] in_fact_b;
    assign  in_fact_a = fact_a;
    assign  in_fact_b = fact_b;
    assign  prdct_z = out_prdct_z;
assign out_prdct_z[ 0] = 
 ((in_fact_b[ 0] & ( 0  ^ in_fact_a[ 0] ))) ^ 
 ((in_fact_b[ 1] & ( 0  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 2] & ( 0  ^ in_fact_a[ 4] ))) ^ 
 ((in_fact_b[ 3] & ( 0  ^ in_fact_a[ 3] ))) ^ 
 ((in_fact_b[ 4] & ( 0  ^ in_fact_a[ 2] ))) ^ 
 ((in_fact_b[ 5] & ( 0  ^ in_fact_a[ 1] ))) ^ 
0;
assign out_prdct_z[ 1] = 
 ((in_fact_b[ 0] & ( 0  ^ in_fact_a[ 1] ))) ^ 
 ((in_fact_b[ 1] & ( 0  ^ in_fact_a[ 0]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 2] & ( 0  ^ in_fact_a[ 4]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 3] & ( 0  ^ in_fact_a[ 3]  ^ in_fact_a[ 4] ))) ^ 
 ((in_fact_b[ 4] & ( 0  ^ in_fact_a[ 2]  ^ in_fact_a[ 3] ))) ^ 
 ((in_fact_b[ 5] & ( 0  ^ in_fact_a[ 1]  ^ in_fact_a[ 2] ))) ^ 
0;
assign out_prdct_z[ 2] = 
 ((in_fact_b[ 0] & ( 0  ^ in_fact_a[ 2] ))) ^ 
 ((in_fact_b[ 1] & ( 0  ^ in_fact_a[ 1] ))) ^ 
 ((in_fact_b[ 2] & ( 0  ^ in_fact_a[ 0]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 3] & ( 0  ^ in_fact_a[ 4]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 4] & ( 0  ^ in_fact_a[ 3]  ^ in_fact_a[ 4] ))) ^ 
 ((in_fact_b[ 5] & ( 0  ^ in_fact_a[ 2]  ^ in_fact_a[ 3] ))) ^ 
0;
assign out_prdct_z[ 3] = 
 ((in_fact_b[ 0] & ( 0  ^ in_fact_a[ 3] ))) ^ 
 ((in_fact_b[ 1] & ( 0  ^ in_fact_a[ 2] ))) ^ 
 ((in_fact_b[ 2] & ( 0  ^ in_fact_a[ 1] ))) ^ 
 ((in_fact_b[ 3] & ( 0  ^ in_fact_a[ 0]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 4] & ( 0  ^ in_fact_a[ 4]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 5] & ( 0  ^ in_fact_a[ 3]  ^ in_fact_a[ 4] ))) ^ 
0;
assign out_prdct_z[ 4] = 
 ((in_fact_b[ 0] & ( 0  ^ in_fact_a[ 4] ))) ^ 
 ((in_fact_b[ 1] & ( 0  ^ in_fact_a[ 3] ))) ^ 
 ((in_fact_b[ 2] & ( 0  ^ in_fact_a[ 2] ))) ^ 
 ((in_fact_b[ 3] & ( 0  ^ in_fact_a[ 1] ))) ^ 
 ((in_fact_b[ 4] & ( 0  ^ in_fact_a[ 0]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 5] & ( 0  ^ in_fact_a[ 4]  ^ in_fact_a[ 5] ))) ^ 
0;
assign out_prdct_z[ 5] = 
 ((in_fact_b[ 0] & ( 0  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 1] & ( 0  ^ in_fact_a[ 4] ))) ^ 
 ((in_fact_b[ 2] & ( 0  ^ in_fact_a[ 3] ))) ^ 
 ((in_fact_b[ 3] & ( 0  ^ in_fact_a[ 2] ))) ^ 
 ((in_fact_b[ 4] & ( 0  ^ in_fact_a[ 1] ))) ^ 
 ((in_fact_b[ 5] & ( 0  ^ in_fact_a[ 0]  ^ in_fact_a[ 5] ))) ^ 
0;
endmodule
//END:


//BEGIN:

(* keep_hierarchy = "yes" *) (* keep = "true" *) module multiplier_16x16_00001 (fact_a,sum_y
/* verilator lint_off UNUSED */
,clk,rstn
/* verilator lint_on UNUSED */
);

/* verilator lint_off UNUSED */
input clk, rstn;
/* verilator lint_on UNUSED */

input[15:0] fact_a;
output[31:0] sum_y;
wire [15:0] fact_b;
assign fact_b = 16'd1;

reg[31:0] sum_y;
wire[31:0] y_d;


wire lo;
wire[2:0] cntl_0,cntl_1,cntl_2,cntl_3;
wire[3:0] cntl_4;
wire[18:0] a0,a1,a2,a3;
wire[18:0] a5,a6;
wire[19:0] a4,a8;
wire[21:0] a7;
reg[21:0] a7_reg;

reg[15:0] a_reg,b_reg;
reg[18:0] a0_reg,a1_reg,a2_reg,a3_reg;
/* verilator lint_off UNUSED */
reg[18:0] a2_reg1;
reg[18:0] a0_reg1;
reg[18:0] a0_reg2;
reg[18:0] a5_reg1;
/* verilator lint_on UNUSED */
reg[19:0] a4_reg;
reg[19:0] a4_reg1,a4_reg2;
reg[18:0] a5_reg,a6_reg;
assign  lo = 0;

/*
Fscaler_3_16 sc0 (.fact_a(fact_a),.cntl(cntl_0),.sum_y(a0));
Fscaler_3_16 sc1 (.fact_a(fact_a),.cntl(cntl_1),.sum_y(a1));
Fscaler_3_16 sc2 (.fact_a(fact_a),.cntl(cntl_2),.sum_y(a2));
Fscaler_3_16 sc3 (.fact_a(fact_a),.cntl(cntl_3),.sum_y(a3));
Fscaler_4_16 sc4 (.fact_a(fact_a),.cntl(cntl_4),.sum_y(a4));
Fadder_19 add0 (.fact_a({a0[18],a0[18],a0[18],a0[18:3]}),.fact_b(a1),
	.c_in(lo),.sum_y(a5));
Fadder_19 add1 (.fact_a({a2[18],a2[18],a2[18],a2[18:3]}),.fact_b(a3),
	.c_in(lo),.sum_y(a6));
Fadder_22 add2 (.fact_a({{6{a5[19]}},a5[19:3]}),
	.fact_b({a6,a2[2:0]}),.c_in(lo),.sum_y(a7));
Fadder_20 add3 (.fact_a({{2{a7[23]}},a7[23:6]}),
	.fact_b(a4),.c_in(lo),.sum_y(a8));

assign  cntl_0 = fact_b[2:0],
	cntl_1 = fact_b[5:3],
	cntl_2 = fact_b[8:6],
	cntl_3 = fact_b[11:9],
	cntl_4 = fact_b[15:12],
	sum_y = {a8,a7[5:0],a5[2:0],a0[2:0]};
*/
///** original code
/****
Fscaler_3_16 sc0 (.fact_a(fact_a),.cntl(cntl_0),.sum_y(a0));
Fscaler_3_16 sc1 (.fact_a(fact_a),.cntl(cntl_1),.sum_y(a1));
Fscaler_3_16 sc2 (.fact_a(fact_a),.cntl(cntl_2),.sum_y(a2));
Fscaler_3_16 sc3 (.fact_a(fact_a),.cntl(cntl_3),.sum_y(a3));
Fscaler_4_16 sc4 (.fact_a(fact_a),.cntl(cntl_4),.sum_y(a4));
Fadder_19 add0 (.fact_a({a0[18],a0[18],a0[18],a0[18:3]}),.fact_b(a1),
	.c_in(lo),.sum_y(a5));
Fadder_19 add1 (.fact_a({a2[18],a2[18],a2[18],a2[18:3]}),.fact_b(a3),
	.c_in(lo),.sum_y(a6));
Fadder_22 add2 (.fact_a({{6{a5[18]}},a5[18:3]}),
	.fact_b({a6,a2[2:0]}),.c_in(lo),.sum_y(a7));
Fadder_20 add3 (.fact_a({{4{a7[21]}},a7[21:6]}),
	.fact_b(a4),.c_in(lo),.sum_y(a8));

assign  cntl_0 = fact_b[2:0],
	cntl_1 = fact_b[5:3],
	cntl_2 = fact_b[8:6],
	cntl_3 = fact_b[11:9],
	cntl_4 = fact_b[15:12],
	sum_y = {a8,a7[5:0],a5[2:0],a0[2:0]};
****/
//***/
Frnyscaler_3_16 sc0 (.fact_a(a_reg),.cntl(cntl_0),.sum_y(a0));
Frnyscaler_3_16 sc1 (.fact_a(a_reg),.cntl(cntl_1),.sum_y(a1));
Frnyscaler_3_16 sc2 (.fact_a(a_reg),.cntl(cntl_2),.sum_y(a2));
Frnyscaler_3_16 sc3 (.fact_a(a_reg),.cntl(cntl_3),.sum_y(a3));
Frnyscaler_4_16 sc4 (.fact_a(a_reg),.cntl(cntl_4),.sum_y(a4));
always @(*)
begin
      a_reg     = fact_a;
      b_reg     = fact_b;
      a0_reg    = a0;
      a0_reg1   = a0_reg;
      a0_reg2   = a0_reg1;
      a1_reg    = a1;
      a2_reg    = a2;
      a2_reg1   = a2_reg;
      a3_reg    = a3;
      a4_reg    = a4;
      a4_reg1   = a4_reg;
      a4_reg2   = a4_reg1;
      a5_reg    = a5;
      a5_reg1   = a5_reg;
      a6_reg    = a6;
      a7_reg    = a7;
      sum_y     = y_d;
end
Frnyadder_19 add0 (.fact_a({a0_reg[18],a0_reg[18],a0_reg[18],a0_reg[18:3]}),.fact_b(a1_reg),
	.c_in(lo),.sum_y(a5));
Frnyadder_19 add1 (.fact_a({a2_reg[18],a2_reg[18],a2_reg[18],a2_reg[18:3]}),.fact_b(a3_reg),
	.c_in(lo),.sum_y(a6));
//Fadder_22 add2 (.fact_a({{6{a5_reg[18]}},a5_reg[18:3]}), .fact_b({a6_reg,a2_reg1[2:0]}),.c_in(lo),.sum_y(a7));
//Fadder_20 add3 (.fact_a({{4{a7_reg[21]}},a7_reg[21:6]}), .fact_b(a4_reg2),.c_in(lo),.sum_y(a8));
Frnyadder_22 add2 (.fact_a({{6{a5_reg[18]}},a5_reg[18:3]}), .fact_b({a6_reg,a2_reg1[2:0]}),.c_in(lo),.sum_y(a7));
Frnyadder_20 add3 (.fact_a({{4{a7_reg[21]}},a7_reg[21:6]}), .fact_b(a4_reg2),.c_in(lo),.sum_y(a8));

assign  cntl_0 = b_reg[2:0],
	cntl_1 = b_reg[5:3],
	cntl_2 = b_reg[8:6],
	cntl_3 = b_reg[11:9],
	cntl_4 = b_reg[15:12],
	y_d = {a8,a7_reg[5:0],a5_reg1[2:0],a0_reg2[2:0]};

endmodule


(* keep_hierarchy = "yes" *) (* keep = "true" *) module multiplier_16x16_00002 (fact_a,sum_y
/* verilator lint_off UNUSED */
,clk,rstn
/* verilator lint_on UNUSED */
);

/* verilator lint_off UNUSED */
input clk, rstn;
/* verilator lint_on UNUSED */

input[15:0] fact_a;
output[31:0] sum_y;
wire [15:0] fact_b;
assign fact_b = 16'd2;

reg[31:0] sum_y;
wire[31:0] y_d;


wire lo;
wire[2:0] cntl_0,cntl_1,cntl_2,cntl_3;
wire[3:0] cntl_4;
wire[18:0] a0,a1,a2,a3;
wire[18:0] a5,a6;
wire[19:0] a4,a8;
wire[21:0] a7;
reg[21:0] a7_reg;

reg[15:0] a_reg,b_reg;
reg[18:0] a0_reg,a1_reg,a2_reg,a3_reg;
/* verilator lint_off UNUSED */
reg[18:0] a2_reg1;
reg[18:0] a0_reg1;
reg[18:0] a0_reg2;
reg[18:0] a5_reg1;
/* verilator lint_on UNUSED */
reg[19:0] a4_reg;
reg[19:0] a4_reg1,a4_reg2;
reg[18:0] a5_reg,a6_reg;
assign  lo = 0;

/*
Fscaler_3_16 sc0 (.fact_a(fact_a),.cntl(cntl_0),.sum_y(a0));
Fscaler_3_16 sc1 (.fact_a(fact_a),.cntl(cntl_1),.sum_y(a1));
Fscaler_3_16 sc2 (.fact_a(fact_a),.cntl(cntl_2),.sum_y(a2));
Fscaler_3_16 sc3 (.fact_a(fact_a),.cntl(cntl_3),.sum_y(a3));
Fscaler_4_16 sc4 (.fact_a(fact_a),.cntl(cntl_4),.sum_y(a4));
Fadder_19 add0 (.fact_a({a0[18],a0[18],a0[18],a0[18:3]}),.fact_b(a1),
	.c_in(lo),.sum_y(a5));
Fadder_19 add1 (.fact_a({a2[18],a2[18],a2[18],a2[18:3]}),.fact_b(a3),
	.c_in(lo),.sum_y(a6));
Fadder_22 add2 (.fact_a({{6{a5[19]}},a5[19:3]}),
	.fact_b({a6,a2[2:0]}),.c_in(lo),.sum_y(a7));
Fadder_20 add3 (.fact_a({{2{a7[23]}},a7[23:6]}),
	.fact_b(a4),.c_in(lo),.sum_y(a8));

assign  cntl_0 = fact_b[2:0],
	cntl_1 = fact_b[5:3],
	cntl_2 = fact_b[8:6],
	cntl_3 = fact_b[11:9],
	cntl_4 = fact_b[15:12],
	sum_y = {a8,a7[5:0],a5[2:0],a0[2:0]};
*/
///** original code
/****
Fscaler_3_16 sc0 (.fact_a(fact_a),.cntl(cntl_0),.sum_y(a0));
Fscaler_3_16 sc1 (.fact_a(fact_a),.cntl(cntl_1),.sum_y(a1));
Fscaler_3_16 sc2 (.fact_a(fact_a),.cntl(cntl_2),.sum_y(a2));
Fscaler_3_16 sc3 (.fact_a(fact_a),.cntl(cntl_3),.sum_y(a3));
Fscaler_4_16 sc4 (.fact_a(fact_a),.cntl(cntl_4),.sum_y(a4));
Fadder_19 add0 (.fact_a({a0[18],a0[18],a0[18],a0[18:3]}),.fact_b(a1),
	.c_in(lo),.sum_y(a5));
Fadder_19 add1 (.fact_a({a2[18],a2[18],a2[18],a2[18:3]}),.fact_b(a3),
	.c_in(lo),.sum_y(a6));
Fadder_22 add2 (.fact_a({{6{a5[18]}},a5[18:3]}),
	.fact_b({a6,a2[2:0]}),.c_in(lo),.sum_y(a7));
Fadder_20 add3 (.fact_a({{4{a7[21]}},a7[21:6]}),
	.fact_b(a4),.c_in(lo),.sum_y(a8));

assign  cntl_0 = fact_b[2:0],
	cntl_1 = fact_b[5:3],
	cntl_2 = fact_b[8:6],
	cntl_3 = fact_b[11:9],
	cntl_4 = fact_b[15:12],
	sum_y = {a8,a7[5:0],a5[2:0],a0[2:0]};
****/
//***/
Frnyscaler_3_16 sc0 (.fact_a(a_reg),.cntl(cntl_0),.sum_y(a0));
Frnyscaler_3_16 sc1 (.fact_a(a_reg),.cntl(cntl_1),.sum_y(a1));
Frnyscaler_3_16 sc2 (.fact_a(a_reg),.cntl(cntl_2),.sum_y(a2));
Frnyscaler_3_16 sc3 (.fact_a(a_reg),.cntl(cntl_3),.sum_y(a3));
Frnyscaler_4_16 sc4 (.fact_a(a_reg),.cntl(cntl_4),.sum_y(a4));
always @(*)
begin
      a_reg     = fact_a;
      b_reg     = fact_b;
      a0_reg    = a0;
      a0_reg1   = a0_reg;
      a0_reg2   = a0_reg1;
      a1_reg    = a1;
      a2_reg    = a2;
      a2_reg1   = a2_reg;
      a3_reg    = a3;
      a4_reg    = a4;
      a4_reg1   = a4_reg;
      a4_reg2   = a4_reg1;
      a5_reg    = a5;
      a5_reg1   = a5_reg;
      a6_reg    = a6;
      a7_reg    = a7;
      sum_y     = y_d;
end
Frnyadder_19 add0 (.fact_a({a0_reg[18],a0_reg[18],a0_reg[18],a0_reg[18:3]}),.fact_b(a1_reg),
	.c_in(lo),.sum_y(a5));
Frnyadder_19 add1 (.fact_a({a2_reg[18],a2_reg[18],a2_reg[18],a2_reg[18:3]}),.fact_b(a3_reg),
	.c_in(lo),.sum_y(a6));
//Fadder_22 add2 (.fact_a({{6{a5_reg[18]}},a5_reg[18:3]}), .fact_b({a6_reg,a2_reg1[2:0]}),.c_in(lo),.sum_y(a7));
//Fadder_20 add3 (.fact_a({{4{a7_reg[21]}},a7_reg[21:6]}), .fact_b(a4_reg2),.c_in(lo),.sum_y(a8));
Frnyadder_22 add2 (.fact_a({{6{a5_reg[18]}},a5_reg[18:3]}), .fact_b({a6_reg,a2_reg1[2:0]}),.c_in(lo),.sum_y(a7));
Frnyadder_20 add3 (.fact_a({{4{a7_reg[21]}},a7_reg[21:6]}), .fact_b(a4_reg2),.c_in(lo),.sum_y(a8));

assign  cntl_0 = b_reg[2:0],
	cntl_1 = b_reg[5:3],
	cntl_2 = b_reg[8:6],
	cntl_3 = b_reg[11:9],
	cntl_4 = b_reg[15:12],
	y_d = {a8,a7_reg[5:0],a5_reg1[2:0],a0_reg2[2:0]};

endmodule


(* keep_hierarchy = "yes" *) (* keep = "true" *) module multiplier_16x16_00003 (fact_a,sum_y
/* verilator lint_off UNUSED */
,clk,rstn
/* verilator lint_on UNUSED */
);

/* verilator lint_off UNUSED */
input clk, rstn;
/* verilator lint_on UNUSED */

input[15:0] fact_a;
output[31:0] sum_y;
wire [15:0] fact_b;
assign fact_b = 16'd3;

reg[31:0] sum_y;
wire[31:0] y_d;


wire lo;
wire[2:0] cntl_0,cntl_1,cntl_2,cntl_3;
wire[3:0] cntl_4;
wire[18:0] a0,a1,a2,a3;
wire[18:0] a5,a6;
wire[19:0] a4,a8;
wire[21:0] a7;
reg[21:0] a7_reg;

reg[15:0] a_reg,b_reg;
reg[18:0] a0_reg,a1_reg,a2_reg,a3_reg;
/* verilator lint_off UNUSED */
reg[18:0] a2_reg1;
reg[18:0] a0_reg1;
reg[18:0] a0_reg2;
reg[18:0] a5_reg1;
/* verilator lint_on UNUSED */
reg[19:0] a4_reg;
reg[19:0] a4_reg1,a4_reg2;
reg[18:0] a5_reg,a6_reg;
assign  lo = 0;

/*
Fscaler_3_16 sc0 (.fact_a(fact_a),.cntl(cntl_0),.sum_y(a0));
Fscaler_3_16 sc1 (.fact_a(fact_a),.cntl(cntl_1),.sum_y(a1));
Fscaler_3_16 sc2 (.fact_a(fact_a),.cntl(cntl_2),.sum_y(a2));
Fscaler_3_16 sc3 (.fact_a(fact_a),.cntl(cntl_3),.sum_y(a3));
Fscaler_4_16 sc4 (.fact_a(fact_a),.cntl(cntl_4),.sum_y(a4));
Fadder_19 add0 (.fact_a({a0[18],a0[18],a0[18],a0[18:3]}),.fact_b(a1),
	.c_in(lo),.sum_y(a5));
Fadder_19 add1 (.fact_a({a2[18],a2[18],a2[18],a2[18:3]}),.fact_b(a3),
	.c_in(lo),.sum_y(a6));
Fadder_22 add2 (.fact_a({{6{a5[19]}},a5[19:3]}),
	.fact_b({a6,a2[2:0]}),.c_in(lo),.sum_y(a7));
Fadder_20 add3 (.fact_a({{2{a7[23]}},a7[23:6]}),
	.fact_b(a4),.c_in(lo),.sum_y(a8));

assign  cntl_0 = fact_b[2:0],
	cntl_1 = fact_b[5:3],
	cntl_2 = fact_b[8:6],
	cntl_3 = fact_b[11:9],
	cntl_4 = fact_b[15:12],
	sum_y = {a8,a7[5:0],a5[2:0],a0[2:0]};
*/
///** original code
/****
Fscaler_3_16 sc0 (.fact_a(fact_a),.cntl(cntl_0),.sum_y(a0));
Fscaler_3_16 sc1 (.fact_a(fact_a),.cntl(cntl_1),.sum_y(a1));
Fscaler_3_16 sc2 (.fact_a(fact_a),.cntl(cntl_2),.sum_y(a2));
Fscaler_3_16 sc3 (.fact_a(fact_a),.cntl(cntl_3),.sum_y(a3));
Fscaler_4_16 sc4 (.fact_a(fact_a),.cntl(cntl_4),.sum_y(a4));
Fadder_19 add0 (.fact_a({a0[18],a0[18],a0[18],a0[18:3]}),.fact_b(a1),
	.c_in(lo),.sum_y(a5));
Fadder_19 add1 (.fact_a({a2[18],a2[18],a2[18],a2[18:3]}),.fact_b(a3),
	.c_in(lo),.sum_y(a6));
Fadder_22 add2 (.fact_a({{6{a5[18]}},a5[18:3]}),
	.fact_b({a6,a2[2:0]}),.c_in(lo),.sum_y(a7));
Fadder_20 add3 (.fact_a({{4{a7[21]}},a7[21:6]}),
	.fact_b(a4),.c_in(lo),.sum_y(a8));

assign  cntl_0 = fact_b[2:0],
	cntl_1 = fact_b[5:3],
	cntl_2 = fact_b[8:6],
	cntl_3 = fact_b[11:9],
	cntl_4 = fact_b[15:12],
	sum_y = {a8,a7[5:0],a5[2:0],a0[2:0]};
****/
//***/
Frnyscaler_3_16 sc0 (.fact_a(a_reg),.cntl(cntl_0),.sum_y(a0));
Frnyscaler_3_16 sc1 (.fact_a(a_reg),.cntl(cntl_1),.sum_y(a1));
Frnyscaler_3_16 sc2 (.fact_a(a_reg),.cntl(cntl_2),.sum_y(a2));
Frnyscaler_3_16 sc3 (.fact_a(a_reg),.cntl(cntl_3),.sum_y(a3));
Frnyscaler_4_16 sc4 (.fact_a(a_reg),.cntl(cntl_4),.sum_y(a4));
always @(*)
begin
      a_reg     = fact_a;
      b_reg     = fact_b;
      a0_reg    = a0;
      a0_reg1   = a0_reg;
      a0_reg2   = a0_reg1;
      a1_reg    = a1;
      a2_reg    = a2;
      a2_reg1   = a2_reg;
      a3_reg    = a3;
      a4_reg    = a4;
      a4_reg1   = a4_reg;
      a4_reg2   = a4_reg1;
      a5_reg    = a5;
      a5_reg1   = a5_reg;
      a6_reg    = a6;
      a7_reg    = a7;
      sum_y     = y_d;
end
Frnyadder_19 add0 (.fact_a({a0_reg[18],a0_reg[18],a0_reg[18],a0_reg[18:3]}),.fact_b(a1_reg),
	.c_in(lo),.sum_y(a5));
Frnyadder_19 add1 (.fact_a({a2_reg[18],a2_reg[18],a2_reg[18],a2_reg[18:3]}),.fact_b(a3_reg),
	.c_in(lo),.sum_y(a6));
//Fadder_22 add2 (.fact_a({{6{a5_reg[18]}},a5_reg[18:3]}), .fact_b({a6_reg,a2_reg1[2:0]}),.c_in(lo),.sum_y(a7));
//Fadder_20 add3 (.fact_a({{4{a7_reg[21]}},a7_reg[21:6]}), .fact_b(a4_reg2),.c_in(lo),.sum_y(a8));
Frnyadder_22 add2 (.fact_a({{6{a5_reg[18]}},a5_reg[18:3]}), .fact_b({a6_reg,a2_reg1[2:0]}),.c_in(lo),.sum_y(a7));
Frnyadder_20 add3 (.fact_a({{4{a7_reg[21]}},a7_reg[21:6]}), .fact_b(a4_reg2),.c_in(lo),.sum_y(a8));

assign  cntl_0 = b_reg[2:0],
	cntl_1 = b_reg[5:3],
	cntl_2 = b_reg[8:6],
	cntl_3 = b_reg[11:9],
	cntl_4 = b_reg[15:12],
	y_d = {a8,a7_reg[5:0],a5_reg1[2:0],a0_reg2[2:0]};

endmodule


(* keep_hierarchy = "yes" *) (* keep = "true" *) module multiplier_16x16_00004 (fact_a,sum_y
/* verilator lint_off UNUSED */
,clk,rstn
/* verilator lint_on UNUSED */
);

/* verilator lint_off UNUSED */
input clk, rstn;
/* verilator lint_on UNUSED */

input[15:0] fact_a;
output[31:0] sum_y;
wire [15:0] fact_b;
assign fact_b = 16'd4;

reg[31:0] sum_y;
wire[31:0] y_d;


wire lo;
wire[2:0] cntl_0,cntl_1,cntl_2,cntl_3;
wire[3:0] cntl_4;
wire[18:0] a0,a1,a2,a3;
wire[18:0] a5,a6;
wire[19:0] a4,a8;
wire[21:0] a7;
reg[21:0] a7_reg;

reg[15:0] a_reg,b_reg;
reg[18:0] a0_reg,a1_reg,a2_reg,a3_reg;
/* verilator lint_off UNUSED */
reg[18:0] a2_reg1;
reg[18:0] a0_reg1;
reg[18:0] a0_reg2;
reg[18:0] a5_reg1;
/* verilator lint_on UNUSED */
reg[19:0] a4_reg;
reg[19:0] a4_reg1,a4_reg2;
reg[18:0] a5_reg,a6_reg;
assign  lo = 0;

/*
Fscaler_3_16 sc0 (.fact_a(fact_a),.cntl(cntl_0),.sum_y(a0));
Fscaler_3_16 sc1 (.fact_a(fact_a),.cntl(cntl_1),.sum_y(a1));
Fscaler_3_16 sc2 (.fact_a(fact_a),.cntl(cntl_2),.sum_y(a2));
Fscaler_3_16 sc3 (.fact_a(fact_a),.cntl(cntl_3),.sum_y(a3));
Fscaler_4_16 sc4 (.fact_a(fact_a),.cntl(cntl_4),.sum_y(a4));
Fadder_19 add0 (.fact_a({a0[18],a0[18],a0[18],a0[18:3]}),.fact_b(a1),
	.c_in(lo),.sum_y(a5));
Fadder_19 add1 (.fact_a({a2[18],a2[18],a2[18],a2[18:3]}),.fact_b(a3),
	.c_in(lo),.sum_y(a6));
Fadder_22 add2 (.fact_a({{6{a5[19]}},a5[19:3]}),
	.fact_b({a6,a2[2:0]}),.c_in(lo),.sum_y(a7));
Fadder_20 add3 (.fact_a({{2{a7[23]}},a7[23:6]}),
	.fact_b(a4),.c_in(lo),.sum_y(a8));

assign  cntl_0 = fact_b[2:0],
	cntl_1 = fact_b[5:3],
	cntl_2 = fact_b[8:6],
	cntl_3 = fact_b[11:9],
	cntl_4 = fact_b[15:12],
	sum_y = {a8,a7[5:0],a5[2:0],a0[2:0]};
*/
///** original code
/****
Fscaler_3_16 sc0 (.fact_a(fact_a),.cntl(cntl_0),.sum_y(a0));
Fscaler_3_16 sc1 (.fact_a(fact_a),.cntl(cntl_1),.sum_y(a1));
Fscaler_3_16 sc2 (.fact_a(fact_a),.cntl(cntl_2),.sum_y(a2));
Fscaler_3_16 sc3 (.fact_a(fact_a),.cntl(cntl_3),.sum_y(a3));
Fscaler_4_16 sc4 (.fact_a(fact_a),.cntl(cntl_4),.sum_y(a4));
Fadder_19 add0 (.fact_a({a0[18],a0[18],a0[18],a0[18:3]}),.fact_b(a1),
	.c_in(lo),.sum_y(a5));
Fadder_19 add1 (.fact_a({a2[18],a2[18],a2[18],a2[18:3]}),.fact_b(a3),
	.c_in(lo),.sum_y(a6));
Fadder_22 add2 (.fact_a({{6{a5[18]}},a5[18:3]}),
	.fact_b({a6,a2[2:0]}),.c_in(lo),.sum_y(a7));
Fadder_20 add3 (.fact_a({{4{a7[21]}},a7[21:6]}),
	.fact_b(a4),.c_in(lo),.sum_y(a8));

assign  cntl_0 = fact_b[2:0],
	cntl_1 = fact_b[5:3],
	cntl_2 = fact_b[8:6],
	cntl_3 = fact_b[11:9],
	cntl_4 = fact_b[15:12],
	sum_y = {a8,a7[5:0],a5[2:0],a0[2:0]};
****/
//***/
Frnyscaler_3_16 sc0 (.fact_a(a_reg),.cntl(cntl_0),.sum_y(a0));
Frnyscaler_3_16 sc1 (.fact_a(a_reg),.cntl(cntl_1),.sum_y(a1));
Frnyscaler_3_16 sc2 (.fact_a(a_reg),.cntl(cntl_2),.sum_y(a2));
Frnyscaler_3_16 sc3 (.fact_a(a_reg),.cntl(cntl_3),.sum_y(a3));
Frnyscaler_4_16 sc4 (.fact_a(a_reg),.cntl(cntl_4),.sum_y(a4));
always @(*)
begin
      a_reg     = fact_a;
      b_reg     = fact_b;
      a0_reg    = a0;
      a0_reg1   = a0_reg;
      a0_reg2   = a0_reg1;
      a1_reg    = a1;
      a2_reg    = a2;
      a2_reg1   = a2_reg;
      a3_reg    = a3;
      a4_reg    = a4;
      a4_reg1   = a4_reg;
      a4_reg2   = a4_reg1;
      a5_reg    = a5;
      a5_reg1   = a5_reg;
      a6_reg    = a6;
      a7_reg    = a7;
      sum_y     = y_d;
end
Frnyadder_19 add0 (.fact_a({a0_reg[18],a0_reg[18],a0_reg[18],a0_reg[18:3]}),.fact_b(a1_reg),
	.c_in(lo),.sum_y(a5));
Frnyadder_19 add1 (.fact_a({a2_reg[18],a2_reg[18],a2_reg[18],a2_reg[18:3]}),.fact_b(a3_reg),
	.c_in(lo),.sum_y(a6));
//Fadder_22 add2 (.fact_a({{6{a5_reg[18]}},a5_reg[18:3]}), .fact_b({a6_reg,a2_reg1[2:0]}),.c_in(lo),.sum_y(a7));
//Fadder_20 add3 (.fact_a({{4{a7_reg[21]}},a7_reg[21:6]}), .fact_b(a4_reg2),.c_in(lo),.sum_y(a8));
Frnyadder_22 add2 (.fact_a({{6{a5_reg[18]}},a5_reg[18:3]}), .fact_b({a6_reg,a2_reg1[2:0]}),.c_in(lo),.sum_y(a7));
Frnyadder_20 add3 (.fact_a({{4{a7_reg[21]}},a7_reg[21:6]}), .fact_b(a4_reg2),.c_in(lo),.sum_y(a8));

assign  cntl_0 = b_reg[2:0],
	cntl_1 = b_reg[5:3],
	cntl_2 = b_reg[8:6],
	cntl_3 = b_reg[11:9],
	cntl_4 = b_reg[15:12],
	y_d = {a8,a7_reg[5:0],a5_reg1[2:0],a0_reg2[2:0]};

endmodule


(* keep_hierarchy = "yes" *) (* keep = "true" *) module multiplier_16x16_00005 (fact_a,sum_y
/* verilator lint_off UNUSED */
,clk,rstn
/* verilator lint_on UNUSED */
);

/* verilator lint_off UNUSED */
input clk, rstn;
/* verilator lint_on UNUSED */

input[15:0] fact_a;
output[31:0] sum_y;
wire [15:0] fact_b;
assign fact_b = 16'd5;

reg[31:0] sum_y;
wire[31:0] y_d;


wire lo;
wire[2:0] cntl_0,cntl_1,cntl_2,cntl_3;
wire[3:0] cntl_4;
wire[18:0] a0,a1,a2,a3;
wire[18:0] a5,a6;
wire[19:0] a4,a8;
wire[21:0] a7;
reg[21:0] a7_reg;

reg[15:0] a_reg,b_reg;
reg[18:0] a0_reg,a1_reg,a2_reg,a3_reg;
/* verilator lint_off UNUSED */
reg[18:0] a2_reg1;
reg[18:0] a0_reg1;
reg[18:0] a0_reg2;
reg[18:0] a5_reg1;
/* verilator lint_on UNUSED */
reg[19:0] a4_reg;
reg[19:0] a4_reg1,a4_reg2;
reg[18:0] a5_reg,a6_reg;
assign  lo = 0;

/*
Fscaler_3_16 sc0 (.fact_a(fact_a),.cntl(cntl_0),.sum_y(a0));
Fscaler_3_16 sc1 (.fact_a(fact_a),.cntl(cntl_1),.sum_y(a1));
Fscaler_3_16 sc2 (.fact_a(fact_a),.cntl(cntl_2),.sum_y(a2));
Fscaler_3_16 sc3 (.fact_a(fact_a),.cntl(cntl_3),.sum_y(a3));
Fscaler_4_16 sc4 (.fact_a(fact_a),.cntl(cntl_4),.sum_y(a4));
Fadder_19 add0 (.fact_a({a0[18],a0[18],a0[18],a0[18:3]}),.fact_b(a1),
	.c_in(lo),.sum_y(a5));
Fadder_19 add1 (.fact_a({a2[18],a2[18],a2[18],a2[18:3]}),.fact_b(a3),
	.c_in(lo),.sum_y(a6));
Fadder_22 add2 (.fact_a({{6{a5[19]}},a5[19:3]}),
	.fact_b({a6,a2[2:0]}),.c_in(lo),.sum_y(a7));
Fadder_20 add3 (.fact_a({{2{a7[23]}},a7[23:6]}),
	.fact_b(a4),.c_in(lo),.sum_y(a8));

assign  cntl_0 = fact_b[2:0],
	cntl_1 = fact_b[5:3],
	cntl_2 = fact_b[8:6],
	cntl_3 = fact_b[11:9],
	cntl_4 = fact_b[15:12],
	sum_y = {a8,a7[5:0],a5[2:0],a0[2:0]};
*/
///** original code
/****
Fscaler_3_16 sc0 (.fact_a(fact_a),.cntl(cntl_0),.sum_y(a0));
Fscaler_3_16 sc1 (.fact_a(fact_a),.cntl(cntl_1),.sum_y(a1));
Fscaler_3_16 sc2 (.fact_a(fact_a),.cntl(cntl_2),.sum_y(a2));
Fscaler_3_16 sc3 (.fact_a(fact_a),.cntl(cntl_3),.sum_y(a3));
Fscaler_4_16 sc4 (.fact_a(fact_a),.cntl(cntl_4),.sum_y(a4));
Fadder_19 add0 (.fact_a({a0[18],a0[18],a0[18],a0[18:3]}),.fact_b(a1),
	.c_in(lo),.sum_y(a5));
Fadder_19 add1 (.fact_a({a2[18],a2[18],a2[18],a2[18:3]}),.fact_b(a3),
	.c_in(lo),.sum_y(a6));
Fadder_22 add2 (.fact_a({{6{a5[18]}},a5[18:3]}),
	.fact_b({a6,a2[2:0]}),.c_in(lo),.sum_y(a7));
Fadder_20 add3 (.fact_a({{4{a7[21]}},a7[21:6]}),
	.fact_b(a4),.c_in(lo),.sum_y(a8));

assign  cntl_0 = fact_b[2:0],
	cntl_1 = fact_b[5:3],
	cntl_2 = fact_b[8:6],
	cntl_3 = fact_b[11:9],
	cntl_4 = fact_b[15:12],
	sum_y = {a8,a7[5:0],a5[2:0],a0[2:0]};
****/
//***/
Frnyscaler_3_16 sc0 (.fact_a(a_reg),.cntl(cntl_0),.sum_y(a0));
Frnyscaler_3_16 sc1 (.fact_a(a_reg),.cntl(cntl_1),.sum_y(a1));
Frnyscaler_3_16 sc2 (.fact_a(a_reg),.cntl(cntl_2),.sum_y(a2));
Frnyscaler_3_16 sc3 (.fact_a(a_reg),.cntl(cntl_3),.sum_y(a3));
Frnyscaler_4_16 sc4 (.fact_a(a_reg),.cntl(cntl_4),.sum_y(a4));
always @(*)
begin
      a_reg     = fact_a;
      b_reg     = fact_b;
      a0_reg    = a0;
      a0_reg1   = a0_reg;
      a0_reg2   = a0_reg1;
      a1_reg    = a1;
      a2_reg    = a2;
      a2_reg1   = a2_reg;
      a3_reg    = a3;
      a4_reg    = a4;
      a4_reg1   = a4_reg;
      a4_reg2   = a4_reg1;
      a5_reg    = a5;
      a5_reg1   = a5_reg;
      a6_reg    = a6;
      a7_reg    = a7;
      sum_y     = y_d;
end
Frnyadder_19 add0 (.fact_a({a0_reg[18],a0_reg[18],a0_reg[18],a0_reg[18:3]}),.fact_b(a1_reg),
	.c_in(lo),.sum_y(a5));
Frnyadder_19 add1 (.fact_a({a2_reg[18],a2_reg[18],a2_reg[18],a2_reg[18:3]}),.fact_b(a3_reg),
	.c_in(lo),.sum_y(a6));
//Fadder_22 add2 (.fact_a({{6{a5_reg[18]}},a5_reg[18:3]}), .fact_b({a6_reg,a2_reg1[2:0]}),.c_in(lo),.sum_y(a7));
//Fadder_20 add3 (.fact_a({{4{a7_reg[21]}},a7_reg[21:6]}), .fact_b(a4_reg2),.c_in(lo),.sum_y(a8));
Frnyadder_22 add2 (.fact_a({{6{a5_reg[18]}},a5_reg[18:3]}), .fact_b({a6_reg,a2_reg1[2:0]}),.c_in(lo),.sum_y(a7));
Frnyadder_20 add3 (.fact_a({{4{a7_reg[21]}},a7_reg[21:6]}), .fact_b(a4_reg2),.c_in(lo),.sum_y(a8));

assign  cntl_0 = b_reg[2:0],
	cntl_1 = b_reg[5:3],
	cntl_2 = b_reg[8:6],
	cntl_3 = b_reg[11:9],
	cntl_4 = b_reg[15:12],
	y_d = {a8,a7_reg[5:0],a5_reg1[2:0],a0_reg2[2:0]};

endmodule





(* keep_hierarchy = "yes" *) (* keep = "true" *) module multiplier_16x16 (fact_a,fact_b,sum_y
/* verilator lint_off UNUSED */
,clk,rstn
/* verilator lint_on UNUSED */
);

/* verilator lint_off UNUSED */
input clk, rstn;
/* verilator lint_on UNUSED */

input[15:0] fact_a;
input wire [15:0] fact_b;
output[31:0] sum_y;

reg[31:0] sum_y;
wire[31:0] y_d;


wire lo;
wire[2:0] cntl_0,cntl_1,cntl_2,cntl_3;
wire[3:0] cntl_4;
wire[18:0] a0,a1,a2,a3;
wire[18:0] a5,a6;
wire[19:0] a4,a8;
wire[21:0] a7;
reg[21:0] a7_reg;

reg[15:0] a_reg,b_reg;
reg[18:0] a0_reg,a1_reg,a2_reg,a3_reg;
/* verilator lint_off UNUSED */
reg[18:0] a2_reg1;
reg[18:0] a0_reg1;
reg[18:0] a0_reg2;
reg[18:0] a5_reg1;
/* verilator lint_on UNUSED */
reg[19:0] a4_reg;
reg[19:0] a4_reg1,a4_reg2;
reg[18:0] a5_reg,a6_reg;
assign  lo = 0;

/*
Fscaler_3_16 sc0 (.fact_a(fact_a),.cntl(cntl_0),.sum_y(a0));
Fscaler_3_16 sc1 (.fact_a(fact_a),.cntl(cntl_1),.sum_y(a1));
Fscaler_3_16 sc2 (.fact_a(fact_a),.cntl(cntl_2),.sum_y(a2));
Fscaler_3_16 sc3 (.fact_a(fact_a),.cntl(cntl_3),.sum_y(a3));
Fscaler_4_16 sc4 (.fact_a(fact_a),.cntl(cntl_4),.sum_y(a4));
Fadder_19 add0 (.fact_a({a0[18],a0[18],a0[18],a0[18:3]}),.fact_b(a1),
	.c_in(lo),.sum_y(a5));
Fadder_19 add1 (.fact_a({a2[18],a2[18],a2[18],a2[18:3]}),.fact_b(a3),
	.c_in(lo),.sum_y(a6));
Fadder_22 add2 (.fact_a({{6{a5[19]}},a5[19:3]}),
	.fact_b({a6,a2[2:0]}),.c_in(lo),.sum_y(a7));
Fadder_20 add3 (.fact_a({{2{a7[23]}},a7[23:6]}),
	.fact_b(a4),.c_in(lo),.sum_y(a8));

assign  cntl_0 = fact_b[2:0],
	cntl_1 = fact_b[5:3],
	cntl_2 = fact_b[8:6],
	cntl_3 = fact_b[11:9],
	cntl_4 = fact_b[15:12],
	sum_y = {a8,a7[5:0],a5[2:0],a0[2:0]};
*/
///** original code
/****
Fscaler_3_16 sc0 (.fact_a(fact_a),.cntl(cntl_0),.sum_y(a0));
Fscaler_3_16 sc1 (.fact_a(fact_a),.cntl(cntl_1),.sum_y(a1));
Fscaler_3_16 sc2 (.fact_a(fact_a),.cntl(cntl_2),.sum_y(a2));
Fscaler_3_16 sc3 (.fact_a(fact_a),.cntl(cntl_3),.sum_y(a3));
Fscaler_4_16 sc4 (.fact_a(fact_a),.cntl(cntl_4),.sum_y(a4));
Fadder_19 add0 (.fact_a({a0[18],a0[18],a0[18],a0[18:3]}),.fact_b(a1),
	.c_in(lo),.sum_y(a5));
Fadder_19 add1 (.fact_a({a2[18],a2[18],a2[18],a2[18:3]}),.fact_b(a3),
	.c_in(lo),.sum_y(a6));
Fadder_22 add2 (.fact_a({{6{a5[18]}},a5[18:3]}),
	.fact_b({a6,a2[2:0]}),.c_in(lo),.sum_y(a7));
Fadder_20 add3 (.fact_a({{4{a7[21]}},a7[21:6]}),
	.fact_b(a4),.c_in(lo),.sum_y(a8));

assign  cntl_0 = fact_b[2:0],
	cntl_1 = fact_b[5:3],
	cntl_2 = fact_b[8:6],
	cntl_3 = fact_b[11:9],
	cntl_4 = fact_b[15:12],
	sum_y = {a8,a7[5:0],a5[2:0],a0[2:0]};
****/
//***/
Frnyscaler_3_16 sc0 (.fact_a(a_reg),.cntl(cntl_0),.sum_y(a0));
Frnyscaler_3_16 sc1 (.fact_a(a_reg),.cntl(cntl_1),.sum_y(a1));
Frnyscaler_3_16 sc2 (.fact_a(a_reg),.cntl(cntl_2),.sum_y(a2));
Frnyscaler_3_16 sc3 (.fact_a(a_reg),.cntl(cntl_3),.sum_y(a3));
Frnyscaler_4_16 sc4 (.fact_a(a_reg),.cntl(cntl_4),.sum_y(a4));
always @(*)
begin
      a_reg     = fact_a;
      b_reg     = fact_b;
      a0_reg    = a0;
      a0_reg1   = a0_reg;
      a0_reg2   = a0_reg1;
      a1_reg    = a1;
      a2_reg    = a2;
      a2_reg1   = a2_reg;
      a3_reg    = a3;
      a4_reg    = a4;
      a4_reg1   = a4_reg;
      a4_reg2   = a4_reg1;
      a5_reg    = a5;
      a5_reg1   = a5_reg;
      a6_reg    = a6;
      a7_reg    = a7;
      sum_y     = y_d;
end
Frnyadder_19 add0 (.fact_a({a0_reg[18],a0_reg[18],a0_reg[18],a0_reg[18:3]}),.fact_b(a1_reg),
	.c_in(lo),.sum_y(a5));
Frnyadder_19 add1 (.fact_a({a2_reg[18],a2_reg[18],a2_reg[18],a2_reg[18:3]}),.fact_b(a3_reg),
	.c_in(lo),.sum_y(a6));
//Fadder_22 add2 (.fact_a({{6{a5_reg[18]}},a5_reg[18:3]}), .fact_b({a6_reg,a2_reg1[2:0]}),.c_in(lo),.sum_y(a7));
//Fadder_20 add3 (.fact_a({{4{a7_reg[21]}},a7_reg[21:6]}), .fact_b(a4_reg2),.c_in(lo),.sum_y(a8));
Frnyadder_22 add2 (.fact_a({{6{a5_reg[18]}},a5_reg[18:3]}), .fact_b({a6_reg,a2_reg1[2:0]}),.c_in(lo),.sum_y(a7));
Frnyadder_20 add3 (.fact_a({{4{a7_reg[21]}},a7_reg[21:6]}), .fact_b(a4_reg2),.c_in(lo),.sum_y(a8));

assign  cntl_0 = b_reg[2:0],
	cntl_1 = b_reg[5:3],
	cntl_2 = b_reg[8:6],
	cntl_3 = b_reg[11:9],
	cntl_4 = b_reg[15:12],
	y_d = {a8,a7_reg[5:0],a5_reg1[2:0],a0_reg2[2:0]};

endmodule



















//END:









////////////////////////Forney////////////////





(* keep_hierarchy = "yes" *) (* keep = "true" *) module Frnyscaler_3_16(fact_a,cntl,sum_y);

input[15:0] fact_a;
input[2:0] cntl;
output[18:0] sum_y;

wire[17:0] a0;
wire[17:0] a1;
wire[17:0] a2;
wire[2:0]  fact_b = cntl;

wire [17:0] sum0;
wire [17:0] carry0;
/* verilator lint_off UNUSED */
wire [18:0] carry0_1;
/* verilator lint_on UNUSED */

assign a0 = fact_b[0] ? {2'b0,fact_a} : 18'b0;
assign a1 = fact_b[1] ? {1'b0,fact_a,1'b0} : 18'b0;
assign a2 = fact_b[2] ? {fact_a,2'b0} : 18'b0;



assign sum0 = a0 ^ a1 ^ a2;
assign carry0 = {a0 & a1} | {a1 & a2} | {a2 & a0};


assign carry0_1 = {carry0,1'b0};

assign sum_y = sum0 + carry0_1;
//assign sum_y = fact_a *cntl;


endmodule




(* keep_hierarchy = "yes" *) (* keep = "true" *) module Frnyscaler_4_16(fact_a,cntl,sum_y);

input[15:0] fact_a;
input[3:0] cntl;
output[19:0] sum_y;

wire[18:0] a0;
wire[18:0] a1;
wire[18:0] a2;
wire[18:0] a3;
wire[3:0]  fact_b = cntl;

wire [18:0] sum0;
wire [18:0] carry0;
/* verilator lint_off UNUSED */
wire [19:0] carry0_1;
/* verilator lint_on UNUSED */

wire [18:0] sum1;
wire [18:0] carry1;
wire [19:0] carry1_1;


assign a0 = fact_b[0] ? {3'b0,fact_a} : 19'b0;
assign a1 = fact_b[1] ? {2'b0,fact_a,1'b0} : 19'b0;
assign a2 = fact_b[2] ? {1'b0,fact_a,2'b0} : 19'b0;
assign a3 = fact_b[3] ? {fact_a,3'b0} : 19'b0;



assign sum0 = a0 ^ a1 ^ a2;
assign carry0 = {a0 & a1} | {a1 & a2} | {a2 & a0};


assign carry0_1 = {carry0,1'b0};



assign sum1 = sum0 ^ carry0_1[18:0] ^ a3;
assign carry1 = {sum0 & carry0_1[18:0]} | {carry0_1[18:0] & a3} | {a3 & sum0};


assign carry1_1 = {carry1,1'b0};




assign sum_y = sum1 + carry1_1;

//assign sum_y = fact_a* cntl;


endmodule





(* keep_hierarchy = "yes" *) (* keep = "true" *) module Frnyadder_19 (fact_a,fact_b,c_in,sum_y);

input[18:0] fact_a;
input[18:0] fact_b;
/* verilator lint_off UNUSED */
input c_in;
/* verilator lint_on UNUSED */
output[18:0] sum_y;









//assign sum0 = a0 ^ a1;
//assign carry0 = {a0 & a1};


//assign carry1 = {carry0,1'b0};

//assign sum_y = sum0 + carry1;
assign sum_y = fact_a + fact_b;



endmodule



(* keep_hierarchy = "yes" *) (* keep = "true" *) module Frnyadder_22 (fact_a,fact_b,c_in,sum_y);

input[21:0] fact_a;
input[21:0] fact_b;
/* verilator lint_off UNUSED */
input c_in;
/* verilator lint_on UNUSED */
output[21:0] sum_y;







//assign sum0 = a0 ^ a1;
//assign carry0 = {a0 & a1};


//assign carry1 = {carry0,1'b0};

//assign sum_y = sum0 + carry1;
assign sum_y = fact_a + fact_b;



endmodule




(* keep_hierarchy = "yes" *) (* keep = "true" *) module Frnyadder_20 (fact_a,fact_b,c_in,sum_y);

input[19:0] fact_a;
input[19:0] fact_b;
/* verilator lint_off UNUSED */
input c_in;
/* verilator lint_on UNUSED */
output[19:0] sum_y;






//assign sum0 = a0 ^ a1;
//assign carry0 = {a0 & a1};


//assign carry1 = {carry0,1'b0};

//assign sum_y = sum0 + carry1;
assign sum_y = fact_a + fact_b;



endmodule




(* keep_hierarchy = "yes" *) (* keep = "true" *) module multiplier_32x32 (fact_a,fact_b,sum_y
/* verilator lint_off UNUSED */
,clk,rstn
/* verilator lint_on UNUSED */
);

/* verilator lint_off UNUSED */
input clk, rstn;
/* verilator lint_on UNUSED */

input[31:0] fact_a,fact_b;
output[63:0] sum_y;
reg[63:0] sum_y;
wire[63:0] y_d;

wire[63:0] a1b1;
reg[63:0] a1b1_reg;
/* verilator lint_off UNUSED */
reg[63:0] a1b1_reg1;
/* verilator lint_on UNUSED */

/* verilator lint_off UNUSED */
wire[63:0] a1b0;
/* verilator lint_on UNUSED */



/* verilator lint_off UNDRIVEN */
/* verilator lint_off UNUSED */
wire[63:0] a0b1;
wire[63:0] a0b0;
/* verilator lint_on UNUSED */
/* verilator lint_on UNDRIVEN */



reg[63:0] a0b0_reg;

/* verilator lint_off UNUSED */
reg[63:0] a0b0_reg1;
/* verilator lint_on UNUSED */

/* verilator lint_off UNDRIVEN */
wire[63:0] a1b0a0b1;
/* verilator lint_on UNDRIVEN */

reg[63:0] a1b0a0b1_reg;

/* verilator lint_off UNUSED */
reg[63:0] a1b0a0b1_reg1;
/* verilator lint_on UNUSED */

/* verilator lint_off UNDRIVEN */
wire[63:0] a1b0a0b1a0b0;
/* verilator lint_on UNDRIVEN */



/* verilator lint_off UNUSED */
reg[63:0] a1b0a0b1a0b0_reg;
wire[63:0] a1b0a0b1a1b1;
wire[63:0] a1b0a0b1a1b1_final;
/* verilator lint_on UNUSED */



assign  a1b1[31:0] = 32'd0;

always @(*)
begin
      a1b0a0b1_reg       = a1b0a0b1;
      a1b0a0b1_reg1      = a1b0a0b1_reg;
      a1b0a0b1a0b0_reg   = a1b0a0b1a0b0;
      a1b1_reg           = a1b1;
      a1b1_reg1          = a1b1_reg;
      a0b0_reg           = a0b0;
      a0b0_reg1          = a0b0_reg;
      sum_y              = y_d;
end



FrnyRSEERmultiplier_16x16 multiplier_16x16_a0b0 (.fact_a(fact_a[15:0]),.fact_b(fact_b[15:0]),.sum_y(a0b0[31:0]),.clk(clk),.rstn(rstn));

FrnyRSEERmultiplier_16x16 multiplier_16x16_a1b0 (.fact_a(fact_a[31:16]),.fact_b(fact_b[15:0]),.sum_y(a1b0[47:16]),.clk(clk),.rstn(rstn));

FrnyRSEERmultiplier_16x16 multiplier_16x16_a0b1 (.fact_a(fact_a[15:0]),.fact_b(fact_b[31:16]),.sum_y(a0b1[47:16]),.clk(clk),.rstn(rstn));

FrnyRSEERmultiplier_16x16 multiplier_16x16_a1b1 (.fact_a(fact_a[31:16]),.fact_b(fact_b[31:16]),.sum_y(a1b1[63:32]),.clk(clk),.rstn(rstn));



FrnyRSEERadder_32 adder_32_U1(.fact_a(a1b0[47:16]),.fact_b(a0b1[47:16]), .sum_y(a1b0a0b1[48:16]));
FrnyRSEERadder_16 adder_16_U1(.fact_a(a0b0_reg[31:16]),.fact_b(a1b0a0b1_reg[31:16]), .sum_y(a1b0a0b1a0b0[32:16]));
FrnyRSEERadder_17 adder_17_U2(.fact_a(a1b1_reg1[48:32]),.fact_b(a1b0a0b1_reg1[48:32]), .carry(a1b0a0b1a0b0_reg[32]),.sum_y(a1b0a0b1a1b1[49:32]));

/* verilator lint_off WIDTH */
assign a1b0a0b1a1b1_final[63:49] = a1b1_reg1[63:49] + a1b0a0b1a1b1[49];
/* verilator lint_on WIDTH */

//assign y_d = {32'd0,a0b0[31:0]} + {16'd0,a1b0[47:16],16'd0} + {16'd0,a0b1[47:16],16'd0} + {a1b1[63:32],32'd0};

assign y_d = {a1b0a0b1a1b1_final[63:49],a1b0a0b1a1b1[48:32],a1b0a0b1a0b0_reg[31:16],a0b0_reg1[15:0]};

endmodule



(* keep_hierarchy = "yes" *) (* keep = "true" *) module FrnyRSEERadder_16(fact_a,fact_b,sum_y);

input[15:0] fact_a,fact_b;
output[16:0] sum_y;

assign sum_y = fact_a+fact_b;


endmodule


(* keep_hierarchy = "yes" *) (* keep = "true" *) module FrnyRSEERadder_17(fact_a,fact_b,carry,sum_y);

input[16:0] fact_a,fact_b;
input carry;
output[17:0] sum_y;

/* verilator lint_off WIDTH */
assign sum_y = fact_a+fact_b + carry;
/* verilator lint_on WIDTH */


endmodule





(* keep_hierarchy = "yes" *) (* keep = "true" *) module FrnyRSEERadder_32(fact_a,fact_b,sum_y);

input[31:0] fact_a,fact_b;
output[32:0] sum_y;

assign sum_y = fact_a+fact_b;


endmodule





//(* keep_hierarchy = "yes" *) (* keep = "true" *) module RSEEERSynPowcrcMult(
//                   prdct_z,
//                   fact_a,
//                   fact_b
//                  );
//
//
//  parameter  PARAM_POLY_WIDTH = 6;
//  parameter  PARAM_PRIMITIVE_POLY = 3;
//    output [PARAM_POLY_WIDTH-1:0] prdct_z;
//    input [PARAM_POLY_WIDTH-1:0] fact_a;
//    input [PARAM_POLY_WIDTH-1:0] fact_b;
//    wire [PARAM_POLY_WIDTH-1:0] out_prdct_z;
//    wire [PARAM_POLY_WIDTH-1:0] in_fact_a;
//    wire [PARAM_POLY_WIDTH-1:0] in_fact_b;
//    assign  in_fact_a = fact_a;
//    assign  in_fact_b = fact_b;
//    assign  prdct_z = out_prdct_z;
// endmodule








(* keep_hierarchy = "yes" *) (* keep = "true" *) module FrnyRSEERmultiplier_16x16 (fact_a,fact_b,sum_y
/* verilator lint_off UNUSED */
,clk,rstn
/* verilator lint_on UNUSED */
);

/* verilator lint_off UNUSED */
input clk, rstn;
/* verilator lint_on UNUSED */

input[15:0] fact_a,fact_b;
output[31:0] sum_y;
reg[31:0] sum_y;
wire[31:0] y_d;

wire lo;
wire[2:0] cntl_0,cntl_1,cntl_2,cntl_3;
wire[3:0] cntl_4;
wire[18:0] a0,a1,a2,a3;
wire[18:0] a5,a6;
wire[19:0] a4,a8;
wire[21:0] a7;
reg[21:0] a7_reg;

reg[15:0] a_reg,b_reg;
reg[18:0] a0_reg,a1_reg,a2_reg,a3_reg;
/* verilator lint_off UNUSED */
reg[18:0] a2_reg1;
reg[18:0] a0_reg1;
reg[18:0] a0_reg2;
reg[18:0] a5_reg1;
/* verilator lint_on UNUSED */
reg[19:0] a4_reg;
reg[19:0] a4_reg1,a4_reg2;
reg[18:0] a5_reg,a6_reg;
assign  lo = 0;

/*
scaler_3_16 sc0 (.fact_a(fact_a),.cntl(cntl_0),.sum_y(a0));
scaler_3_16 sc1 (.fact_a(fact_a),.cntl(cntl_1),.sum_y(a1));
scaler_3_16 sc2 (.fact_a(fact_a),.cntl(cntl_2),.sum_y(a2));
scaler_3_16 sc3 (.fact_a(fact_a),.cntl(cntl_3),.sum_y(a3));
scaler_4_16 sc4 (.fact_a(fact_a),.cntl(cntl_4),.sum_y(a4));
adder_19 add0 (.fact_a({a0[18],a0[18],a0[18],a0[18:3]}),.fact_b(a1),
	.c_in(lo),.sum_y(a5));
adder_19 add1 (.fact_a({a2[18],a2[18],a2[18],a2[18:3]}),.fact_b(a3),
	.c_in(lo),.sum_y(a6));
adder_22 add2 (.fact_a({{6{a5[19]}},a5[19:3]}),
	.fact_b({a6,a2[2:0]}),.c_in(lo),.sum_y(a7));
adder_20 add3 (.fact_a({{2{a7[23]}},a7[23:6]}),
	.fact_b(a4),.c_in(lo),.sum_y(a8));

assign  cntl_0 = fact_b[2:0],
	cntl_1 = fact_b[5:3],
	cntl_2 = fact_b[8:6],
	cntl_3 = fact_b[11:9],
	cntl_4 = fact_b[15:12],
	sum_y = {a8,a7[5:0],a5[2:0],a0[2:0]};
*/
///** original code
/****
scaler_3_16 sc0 (.fact_a(fact_a),.cntl(cntl_0),.sum_y(a0));
scaler_3_16 sc1 (.fact_a(fact_a),.cntl(cntl_1),.sum_y(a1));
scaler_3_16 sc2 (.fact_a(fact_a),.cntl(cntl_2),.sum_y(a2));
scaler_3_16 sc3 (.fact_a(fact_a),.cntl(cntl_3),.sum_y(a3));
scaler_4_16 sc4 (.fact_a(fact_a),.cntl(cntl_4),.sum_y(a4));
adder_19 add0 (.fact_a({a0[18],a0[18],a0[18],a0[18:3]}),.fact_b(a1),
	.c_in(lo),.sum_y(a5));
adder_19 add1 (.fact_a({a2[18],a2[18],a2[18],a2[18:3]}),.fact_b(a3),
	.c_in(lo),.sum_y(a6));
adder_22 add2 (.fact_a({{6{a5[18]}},a5[18:3]}),
	.fact_b({a6,a2[2:0]}),.c_in(lo),.sum_y(a7));
adder_20 add3 (.fact_a({{4{a7[21]}},a7[21:6]}),
	.fact_b(a4),.c_in(lo),.sum_y(a8));

assign  cntl_0 = fact_b[2:0],
	cntl_1 = fact_b[5:3],
	cntl_2 = fact_b[8:6],
	cntl_3 = fact_b[11:9],
	cntl_4 = fact_b[15:12],
	sum_y = {a8,a7[5:0],a5[2:0],a0[2:0]};
****/
//***/
FrnyRSEERscaler_3_16 sc0 (.fact_a(a_reg),.cntl(cntl_0),.sum_y(a0));
FrnyRSEERscaler_3_16 sc1 (.fact_a(a_reg),.cntl(cntl_1),.sum_y(a1));
FrnyRSEERscaler_3_16 sc2 (.fact_a(a_reg),.cntl(cntl_2),.sum_y(a2));
FrnyRSEERscaler_3_16 sc3 (.fact_a(a_reg),.cntl(cntl_3),.sum_y(a3));
FrnyRSEERscaler_4_16 sc4 (.fact_a(a_reg),.cntl(cntl_4),.sum_y(a4));
always @(*)
begin
      a_reg       = fact_a;
      b_reg       = fact_b;
      a0_reg      = a0;
      a0_reg1     = a0_reg;
      a0_reg2     = a0_reg1;
      a1_reg      = a1;
      a2_reg      = a2;
      a2_reg1     = a2_reg;
      a3_reg      = a3;
      a4_reg      = a4;
      a4_reg1     = a4_reg;
      a4_reg2     = a4_reg1;
      a5_reg      = a5;
      a5_reg1     = a5_reg;
      a6_reg      = a6;
      a7_reg      = a7;
      sum_y       = y_d;
end
FrnyRSEERadder_19 add0 (.fact_a({a0_reg[18],a0_reg[18],a0_reg[18],a0_reg[18:3]}),.fact_b(a1_reg),
	.c_in(lo),.sum_y(a5));
FrnyRSEERadder_19 add1 (.fact_a({a2_reg[18],a2_reg[18],a2_reg[18],a2_reg[18:3]}),.fact_b(a3_reg),
	.c_in(lo),.sum_y(a6));
//FRSEERadder_22 add2 (.fact_a({{6{a5_reg[18]}},a5_reg[18:3]}), .fact_b({a6_reg,a2_reg1[2:0]}),.c_in(lo),.sum_y(a7));
//FRSEERadder_20 add3 (.fact_a({{4{a7_reg[21]}},a7_reg[21:6]}), .fact_b(a4_reg2),.c_in(lo),.sum_y(a8));
FrnyRSEERadder_22 add2 (.fact_a({{6{a5_reg[18]}},a5_reg[18:3]}), .fact_b({a6_reg,a2_reg1[2:0]}),.c_in(lo),.sum_y(a7));
FrnyRSEERadder_20 add3 (.fact_a({{4{a7_reg[21]}},a7_reg[21:6]}), .fact_b(a4_reg2),.c_in(lo),.sum_y(a8));

assign  cntl_0 = b_reg[2:0],
	cntl_1 = b_reg[5:3],
	cntl_2 = b_reg[8:6],
	cntl_3 = b_reg[11:9],
	cntl_4 = b_reg[15:12],
	y_d = {a8,a7_reg[5:0],a5_reg1[2:0],a0_reg2[2:0]};

endmodule


 (* keep_hierarchy = "yes" *) (* keep = "true" *) module FrnyRSEERscaler_3_16(fact_a,cntl,sum_y);

 input[15:0] fact_a;
 input[2:0] cntl;
 output[18:0] sum_y;

 wire[17:0] a0;
 wire[17:0] a1;
 wire[17:0] a2;
 wire[2:0]  fact_b = cntl;

 wire [17:0] sum0;
 wire [17:0] carry0;
/* verilator lint_off UNUSED */
 wire [18:0] carry0_1;
/* verilator lint_on UNUSED */

 assign a0 = fact_b[0] ? {2'b0,fact_a} : 18'b0;
 assign a1 = fact_b[1] ? {1'b0,fact_a,1'b0} : 18'b0;
 assign a2 = fact_b[2] ? {fact_a,2'b0} : 18'b0;



 assign sum0 = a0 ^ a1 ^ a2;
 assign carry0 = {a0 & a1} | {a1 & a2} | {a2 & a0};


 assign carry0_1 = {carry0,1'b0};

 assign sum_y = sum0 + carry0_1;
 //assign sum_y = fact_a *cntl;


 endmodule




 (* keep_hierarchy = "yes" *) (* keep = "true" *) module FrnyRSEERscaler_4_16(fact_a,cntl,sum_y);

 input[15:0] fact_a;
 input[3:0] cntl;
 output[19:0] sum_y;

 wire[18:0] a0;
 wire[18:0] a1;
 wire[18:0] a2;
 wire[18:0] a3;
 wire[3:0]  fact_b = cntl;

 wire [18:0] sum0;
 wire [18:0] carry0;
/* verilator lint_off UNUSED */
 wire [19:0] carry0_1;
/* verilator lint_on UNUSED */

 wire [18:0] sum1;
 wire [18:0] carry1;
 wire [19:0] carry1_1;


 assign a0 = fact_b[0] ? {3'b0,fact_a} : 19'b0;
 assign a1 = fact_b[1] ? {2'b0,fact_a,1'b0} : 19'b0;
 assign a2 = fact_b[2] ? {1'b0,fact_a,2'b0} : 19'b0;
 assign a3 = fact_b[3] ? {fact_a,3'b0} : 19'b0;



 assign sum0 = a0 ^ a1 ^ a2;
 assign carry0 = {a0 & a1} | {a1 & a2} | {a2 & a0};


 assign carry0_1 = {carry0,1'b0};



 assign sum1 = sum0 ^ carry0_1[18:0] ^ a3;
 assign carry1 = {sum0 & carry0_1[18:0]} | {carry0_1[18:0] & a3} | {a3 & sum0};


 assign carry1_1 = {carry1,1'b0};




 assign sum_y = sum1 + carry1_1;

 //assign sum_y = fact_a* cntl;


 endmodule





 (* keep_hierarchy = "yes" *) (* keep = "true" *) module FrnyRSEERadder_19 (fact_a,fact_b,c_in,sum_y);

 input[18:0] fact_a;
 input[18:0] fact_b;
/* verilator lint_off UNUSED */
 input c_in;
/* verilator lint_on UNUSED */
 output[18:0] sum_y;







 //assign sum0 = a0 ^ a1;
 //assign carry0 = {a0 & a1};


 //assign carry1 = {carry0,1'b0};

 //assign sum_y = sum0 + carry1;
 assign sum_y = fact_a + fact_b;



 endmodule



 (* keep_hierarchy = "yes" *) (* keep = "true" *) module FrnyRSEERadder_22 (fact_a,fact_b,c_in,sum_y);

 input[21:0] fact_a;
 input[21:0] fact_b;
/* verilator lint_off UNUSED */
 input c_in;
/* verilator lint_on UNUSED */
 output[21:0] sum_y;






 //assign sum0 = a0 ^ a1;
 //assign carry0 = {a0 & a1};


 //assign carry1 = {carry0,1'b0};

 //assign sum_y = sum0 + carry1;
 assign sum_y = fact_a + fact_b;



 endmodule




 (* keep_hierarchy = "yes" *) (* keep = "true" *) module FrnyRSEERadder_20 (fact_a,fact_b,c_in,sum_y);

 input[19:0] fact_a;
 input[19:0] fact_b;
/* verilator lint_off UNUSED */
 input c_in;
/* verilator lint_on UNUSED */
 output[19:0] sum_y;







 //assign sum0 = a0 ^ a1;
 //assign carry0 = {a0 & a1};


 //assign carry1 = {carry0,1'b0};

 //assign sum_y = sum0 + carry1;
 assign sum_y = fact_a + fact_b;



 endmodule

(* keep_hierarchy = "yes" *) (* keep = "true" *) module FrnycrcMult_00000(
                   prdct_z,
                   fact_a
                  );


  parameter  PARAM_POLY_WIDTH = 6;
  parameter  PARAM_PRIMITIVE_POLY = 3;
    output [PARAM_POLY_WIDTH-1:0] prdct_z;
    input [PARAM_POLY_WIDTH-1:0] fact_a;
    wire [PARAM_POLY_WIDTH-1:0] fact_b = 6'd2;
    wire [PARAM_POLY_WIDTH-1:0] out_prdct_z;
    wire [PARAM_POLY_WIDTH-1:0] in_fact_a;
    wire [PARAM_POLY_WIDTH-1:0] in_fact_b;
    assign  in_fact_a = fact_a;
    assign  in_fact_b = fact_b;
    assign  prdct_z = out_prdct_z;
assign out_prdct_z[ 0] = 
 ((in_fact_b[ 0] & ( 0  ^ in_fact_a[ 0] ))) ^ 
 ((in_fact_b[ 1] & ( 0  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 2] & ( 0  ^ in_fact_a[ 4] ))) ^ 
 ((in_fact_b[ 3] & ( 0  ^ in_fact_a[ 3] ))) ^ 
 ((in_fact_b[ 4] & ( 0  ^ in_fact_a[ 2] ))) ^ 
 ((in_fact_b[ 5] & ( 0  ^ in_fact_a[ 1] ))) ^ 
0;
assign out_prdct_z[ 1] = 
 ((in_fact_b[ 0] & ( 0  ^ in_fact_a[ 1] ))) ^ 
 ((in_fact_b[ 1] & ( 0  ^ in_fact_a[ 0]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 2] & ( 0  ^ in_fact_a[ 4]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 3] & ( 0  ^ in_fact_a[ 3]  ^ in_fact_a[ 4] ))) ^ 
 ((in_fact_b[ 4] & ( 0  ^ in_fact_a[ 2]  ^ in_fact_a[ 3] ))) ^ 
 ((in_fact_b[ 5] & ( 0  ^ in_fact_a[ 1]  ^ in_fact_a[ 2] ))) ^ 
0;
assign out_prdct_z[ 2] = 
 ((in_fact_b[ 0] & ( 0  ^ in_fact_a[ 2] ))) ^ 
 ((in_fact_b[ 1] & ( 0  ^ in_fact_a[ 1] ))) ^ 
 ((in_fact_b[ 2] & ( 0  ^ in_fact_a[ 0]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 3] & ( 0  ^ in_fact_a[ 4]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 4] & ( 0  ^ in_fact_a[ 3]  ^ in_fact_a[ 4] ))) ^ 
 ((in_fact_b[ 5] & ( 0  ^ in_fact_a[ 2]  ^ in_fact_a[ 3] ))) ^ 
0;
assign out_prdct_z[ 3] = 
 ((in_fact_b[ 0] & ( 0  ^ in_fact_a[ 3] ))) ^ 
 ((in_fact_b[ 1] & ( 0  ^ in_fact_a[ 2] ))) ^ 
 ((in_fact_b[ 2] & ( 0  ^ in_fact_a[ 1] ))) ^ 
 ((in_fact_b[ 3] & ( 0  ^ in_fact_a[ 0]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 4] & ( 0  ^ in_fact_a[ 4]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 5] & ( 0  ^ in_fact_a[ 3]  ^ in_fact_a[ 4] ))) ^ 
0;
assign out_prdct_z[ 4] = 
 ((in_fact_b[ 0] & ( 0  ^ in_fact_a[ 4] ))) ^ 
 ((in_fact_b[ 1] & ( 0  ^ in_fact_a[ 3] ))) ^ 
 ((in_fact_b[ 2] & ( 0  ^ in_fact_a[ 2] ))) ^ 
 ((in_fact_b[ 3] & ( 0  ^ in_fact_a[ 1] ))) ^ 
 ((in_fact_b[ 4] & ( 0  ^ in_fact_a[ 0]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 5] & ( 0  ^ in_fact_a[ 4]  ^ in_fact_a[ 5] ))) ^ 
0;
assign out_prdct_z[ 5] = 
 ((in_fact_b[ 0] & ( 0  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 1] & ( 0  ^ in_fact_a[ 4] ))) ^ 
 ((in_fact_b[ 2] & ( 0  ^ in_fact_a[ 3] ))) ^ 
 ((in_fact_b[ 3] & ( 0  ^ in_fact_a[ 2] ))) ^ 
 ((in_fact_b[ 4] & ( 0  ^ in_fact_a[ 1] ))) ^ 
 ((in_fact_b[ 5] & ( 0  ^ in_fact_a[ 0]  ^ in_fact_a[ 5] ))) ^ 
0;
endmodule
(* keep_hierarchy = "yes" *) (* keep = "true" *) module FrnycrcMult_00001(
                   prdct_z,
                   fact_a
                  );


  parameter  PARAM_POLY_WIDTH = 6;
  parameter  PARAM_PRIMITIVE_POLY = 3;
    output [PARAM_POLY_WIDTH-1:0] prdct_z;
    input [PARAM_POLY_WIDTH-1:0] fact_a;
    wire [PARAM_POLY_WIDTH-1:0] fact_b = 6'd4;
    wire [PARAM_POLY_WIDTH-1:0] out_prdct_z;
    wire [PARAM_POLY_WIDTH-1:0] in_fact_a;
    wire [PARAM_POLY_WIDTH-1:0] in_fact_b;
    assign  in_fact_a = fact_a;
    assign  in_fact_b = fact_b;
    assign  prdct_z = out_prdct_z;
assign out_prdct_z[ 0] = 
 ((in_fact_b[ 0] & ( 0  ^ in_fact_a[ 0] ))) ^ 
 ((in_fact_b[ 1] & ( 0  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 2] & ( 0  ^ in_fact_a[ 4] ))) ^ 
 ((in_fact_b[ 3] & ( 0  ^ in_fact_a[ 3] ))) ^ 
 ((in_fact_b[ 4] & ( 0  ^ in_fact_a[ 2] ))) ^ 
 ((in_fact_b[ 5] & ( 0  ^ in_fact_a[ 1] ))) ^ 
0;
assign out_prdct_z[ 1] = 
 ((in_fact_b[ 0] & ( 0  ^ in_fact_a[ 1] ))) ^ 
 ((in_fact_b[ 1] & ( 0  ^ in_fact_a[ 0]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 2] & ( 0  ^ in_fact_a[ 4]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 3] & ( 0  ^ in_fact_a[ 3]  ^ in_fact_a[ 4] ))) ^ 
 ((in_fact_b[ 4] & ( 0  ^ in_fact_a[ 2]  ^ in_fact_a[ 3] ))) ^ 
 ((in_fact_b[ 5] & ( 0  ^ in_fact_a[ 1]  ^ in_fact_a[ 2] ))) ^ 
0;
assign out_prdct_z[ 2] = 
 ((in_fact_b[ 0] & ( 0  ^ in_fact_a[ 2] ))) ^ 
 ((in_fact_b[ 1] & ( 0  ^ in_fact_a[ 1] ))) ^ 
 ((in_fact_b[ 2] & ( 0  ^ in_fact_a[ 0]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 3] & ( 0  ^ in_fact_a[ 4]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 4] & ( 0  ^ in_fact_a[ 3]  ^ in_fact_a[ 4] ))) ^ 
 ((in_fact_b[ 5] & ( 0  ^ in_fact_a[ 2]  ^ in_fact_a[ 3] ))) ^ 
0;
assign out_prdct_z[ 3] = 
 ((in_fact_b[ 0] & ( 0  ^ in_fact_a[ 3] ))) ^ 
 ((in_fact_b[ 1] & ( 0  ^ in_fact_a[ 2] ))) ^ 
 ((in_fact_b[ 2] & ( 0  ^ in_fact_a[ 1] ))) ^ 
 ((in_fact_b[ 3] & ( 0  ^ in_fact_a[ 0]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 4] & ( 0  ^ in_fact_a[ 4]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 5] & ( 0  ^ in_fact_a[ 3]  ^ in_fact_a[ 4] ))) ^ 
0;
assign out_prdct_z[ 4] = 
 ((in_fact_b[ 0] & ( 0  ^ in_fact_a[ 4] ))) ^ 
 ((in_fact_b[ 1] & ( 0  ^ in_fact_a[ 3] ))) ^ 
 ((in_fact_b[ 2] & ( 0  ^ in_fact_a[ 2] ))) ^ 
 ((in_fact_b[ 3] & ( 0  ^ in_fact_a[ 1] ))) ^ 
 ((in_fact_b[ 4] & ( 0  ^ in_fact_a[ 0]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 5] & ( 0  ^ in_fact_a[ 4]  ^ in_fact_a[ 5] ))) ^ 
0;
assign out_prdct_z[ 5] = 
 ((in_fact_b[ 0] & ( 0  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 1] & ( 0  ^ in_fact_a[ 4] ))) ^ 
 ((in_fact_b[ 2] & ( 0  ^ in_fact_a[ 3] ))) ^ 
 ((in_fact_b[ 3] & ( 0  ^ in_fact_a[ 2] ))) ^ 
 ((in_fact_b[ 4] & ( 0  ^ in_fact_a[ 1] ))) ^ 
 ((in_fact_b[ 5] & ( 0  ^ in_fact_a[ 0]  ^ in_fact_a[ 5] ))) ^ 
0;
endmodule
(* keep_hierarchy = "yes" *) (* keep = "true" *) module FrnycrcMult_00002(
                   prdct_z,
                   fact_a
                  );


  parameter  PARAM_POLY_WIDTH = 6;
  parameter  PARAM_PRIMITIVE_POLY = 3;
    output [PARAM_POLY_WIDTH-1:0] prdct_z;
    input [PARAM_POLY_WIDTH-1:0] fact_a;
    wire [PARAM_POLY_WIDTH-1:0] fact_b = 6'd16;
    wire [PARAM_POLY_WIDTH-1:0] out_prdct_z;
    wire [PARAM_POLY_WIDTH-1:0] in_fact_a;
    wire [PARAM_POLY_WIDTH-1:0] in_fact_b;
    assign  in_fact_a = fact_a;
    assign  in_fact_b = fact_b;
    assign  prdct_z = out_prdct_z;
assign out_prdct_z[ 0] = 
 ((in_fact_b[ 0] & ( 0  ^ in_fact_a[ 0] ))) ^ 
 ((in_fact_b[ 1] & ( 0  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 2] & ( 0  ^ in_fact_a[ 4] ))) ^ 
 ((in_fact_b[ 3] & ( 0  ^ in_fact_a[ 3] ))) ^ 
 ((in_fact_b[ 4] & ( 0  ^ in_fact_a[ 2] ))) ^ 
 ((in_fact_b[ 5] & ( 0  ^ in_fact_a[ 1] ))) ^ 
0;
assign out_prdct_z[ 1] = 
 ((in_fact_b[ 0] & ( 0  ^ in_fact_a[ 1] ))) ^ 
 ((in_fact_b[ 1] & ( 0  ^ in_fact_a[ 0]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 2] & ( 0  ^ in_fact_a[ 4]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 3] & ( 0  ^ in_fact_a[ 3]  ^ in_fact_a[ 4] ))) ^ 
 ((in_fact_b[ 4] & ( 0  ^ in_fact_a[ 2]  ^ in_fact_a[ 3] ))) ^ 
 ((in_fact_b[ 5] & ( 0  ^ in_fact_a[ 1]  ^ in_fact_a[ 2] ))) ^ 
0;
assign out_prdct_z[ 2] = 
 ((in_fact_b[ 0] & ( 0  ^ in_fact_a[ 2] ))) ^ 
 ((in_fact_b[ 1] & ( 0  ^ in_fact_a[ 1] ))) ^ 
 ((in_fact_b[ 2] & ( 0  ^ in_fact_a[ 0]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 3] & ( 0  ^ in_fact_a[ 4]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 4] & ( 0  ^ in_fact_a[ 3]  ^ in_fact_a[ 4] ))) ^ 
 ((in_fact_b[ 5] & ( 0  ^ in_fact_a[ 2]  ^ in_fact_a[ 3] ))) ^ 
0;
assign out_prdct_z[ 3] = 
 ((in_fact_b[ 0] & ( 0  ^ in_fact_a[ 3] ))) ^ 
 ((in_fact_b[ 1] & ( 0  ^ in_fact_a[ 2] ))) ^ 
 ((in_fact_b[ 2] & ( 0  ^ in_fact_a[ 1] ))) ^ 
 ((in_fact_b[ 3] & ( 0  ^ in_fact_a[ 0]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 4] & ( 0  ^ in_fact_a[ 4]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 5] & ( 0  ^ in_fact_a[ 3]  ^ in_fact_a[ 4] ))) ^ 
0;
assign out_prdct_z[ 4] = 
 ((in_fact_b[ 0] & ( 0  ^ in_fact_a[ 4] ))) ^ 
 ((in_fact_b[ 1] & ( 0  ^ in_fact_a[ 3] ))) ^ 
 ((in_fact_b[ 2] & ( 0  ^ in_fact_a[ 2] ))) ^ 
 ((in_fact_b[ 3] & ( 0  ^ in_fact_a[ 1] ))) ^ 
 ((in_fact_b[ 4] & ( 0  ^ in_fact_a[ 0]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 5] & ( 0  ^ in_fact_a[ 4]  ^ in_fact_a[ 5] ))) ^ 
0;
assign out_prdct_z[ 5] = 
 ((in_fact_b[ 0] & ( 0  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 1] & ( 0  ^ in_fact_a[ 4] ))) ^ 
 ((in_fact_b[ 2] & ( 0  ^ in_fact_a[ 3] ))) ^ 
 ((in_fact_b[ 3] & ( 0  ^ in_fact_a[ 2] ))) ^ 
 ((in_fact_b[ 4] & ( 0  ^ in_fact_a[ 1] ))) ^ 
 ((in_fact_b[ 5] & ( 0  ^ in_fact_a[ 0]  ^ in_fact_a[ 5] ))) ^ 
0;
endmodule
(* keep_hierarchy = "yes" *) (* keep = "true" *) module FrnycrcMult_00003(
                   prdct_z,
                   fact_a
                  );


  parameter  PARAM_POLY_WIDTH = 6;
  parameter  PARAM_PRIMITIVE_POLY = 3;
    output [PARAM_POLY_WIDTH-1:0] prdct_z;
    input [PARAM_POLY_WIDTH-1:0] fact_a;
    wire [PARAM_POLY_WIDTH-1:0] fact_b = 6'd12;
    wire [PARAM_POLY_WIDTH-1:0] out_prdct_z;
    wire [PARAM_POLY_WIDTH-1:0] in_fact_a;
    wire [PARAM_POLY_WIDTH-1:0] in_fact_b;
    assign  in_fact_a = fact_a;
    assign  in_fact_b = fact_b;
    assign  prdct_z = out_prdct_z;
assign out_prdct_z[ 0] = 
 ((in_fact_b[ 0] & ( 0  ^ in_fact_a[ 0] ))) ^ 
 ((in_fact_b[ 1] & ( 0  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 2] & ( 0  ^ in_fact_a[ 4] ))) ^ 
 ((in_fact_b[ 3] & ( 0  ^ in_fact_a[ 3] ))) ^ 
 ((in_fact_b[ 4] & ( 0  ^ in_fact_a[ 2] ))) ^ 
 ((in_fact_b[ 5] & ( 0  ^ in_fact_a[ 1] ))) ^ 
0;
assign out_prdct_z[ 1] = 
 ((in_fact_b[ 0] & ( 0  ^ in_fact_a[ 1] ))) ^ 
 ((in_fact_b[ 1] & ( 0  ^ in_fact_a[ 0]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 2] & ( 0  ^ in_fact_a[ 4]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 3] & ( 0  ^ in_fact_a[ 3]  ^ in_fact_a[ 4] ))) ^ 
 ((in_fact_b[ 4] & ( 0  ^ in_fact_a[ 2]  ^ in_fact_a[ 3] ))) ^ 
 ((in_fact_b[ 5] & ( 0  ^ in_fact_a[ 1]  ^ in_fact_a[ 2] ))) ^ 
0;
assign out_prdct_z[ 2] = 
 ((in_fact_b[ 0] & ( 0  ^ in_fact_a[ 2] ))) ^ 
 ((in_fact_b[ 1] & ( 0  ^ in_fact_a[ 1] ))) ^ 
 ((in_fact_b[ 2] & ( 0  ^ in_fact_a[ 0]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 3] & ( 0  ^ in_fact_a[ 4]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 4] & ( 0  ^ in_fact_a[ 3]  ^ in_fact_a[ 4] ))) ^ 
 ((in_fact_b[ 5] & ( 0  ^ in_fact_a[ 2]  ^ in_fact_a[ 3] ))) ^ 
0;
assign out_prdct_z[ 3] = 
 ((in_fact_b[ 0] & ( 0  ^ in_fact_a[ 3] ))) ^ 
 ((in_fact_b[ 1] & ( 0  ^ in_fact_a[ 2] ))) ^ 
 ((in_fact_b[ 2] & ( 0  ^ in_fact_a[ 1] ))) ^ 
 ((in_fact_b[ 3] & ( 0  ^ in_fact_a[ 0]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 4] & ( 0  ^ in_fact_a[ 4]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 5] & ( 0  ^ in_fact_a[ 3]  ^ in_fact_a[ 4] ))) ^ 
0;
assign out_prdct_z[ 4] = 
 ((in_fact_b[ 0] & ( 0  ^ in_fact_a[ 4] ))) ^ 
 ((in_fact_b[ 1] & ( 0  ^ in_fact_a[ 3] ))) ^ 
 ((in_fact_b[ 2] & ( 0  ^ in_fact_a[ 2] ))) ^ 
 ((in_fact_b[ 3] & ( 0  ^ in_fact_a[ 1] ))) ^ 
 ((in_fact_b[ 4] & ( 0  ^ in_fact_a[ 0]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 5] & ( 0  ^ in_fact_a[ 4]  ^ in_fact_a[ 5] ))) ^ 
0;
assign out_prdct_z[ 5] = 
 ((in_fact_b[ 0] & ( 0  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 1] & ( 0  ^ in_fact_a[ 4] ))) ^ 
 ((in_fact_b[ 2] & ( 0  ^ in_fact_a[ 3] ))) ^ 
 ((in_fact_b[ 3] & ( 0  ^ in_fact_a[ 2] ))) ^ 
 ((in_fact_b[ 4] & ( 0  ^ in_fact_a[ 1] ))) ^ 
 ((in_fact_b[ 5] & ( 0  ^ in_fact_a[ 0]  ^ in_fact_a[ 5] ))) ^ 
0;
endmodule
(* keep_hierarchy = "yes" *) (* keep = "true" *) module FrnycrcMult_00004(
                   prdct_z,
                   fact_a
                  );


  parameter  PARAM_POLY_WIDTH = 6;
  parameter  PARAM_PRIMITIVE_POLY = 3;
    output [PARAM_POLY_WIDTH-1:0] prdct_z;
    input [PARAM_POLY_WIDTH-1:0] fact_a;
    wire [PARAM_POLY_WIDTH-1:0] fact_b = 6'd19;
    wire [PARAM_POLY_WIDTH-1:0] out_prdct_z;
    wire [PARAM_POLY_WIDTH-1:0] in_fact_a;
    wire [PARAM_POLY_WIDTH-1:0] in_fact_b;
    assign  in_fact_a = fact_a;
    assign  in_fact_b = fact_b;
    assign  prdct_z = out_prdct_z;
assign out_prdct_z[ 0] = 
 ((in_fact_b[ 0] & ( 0  ^ in_fact_a[ 0] ))) ^ 
 ((in_fact_b[ 1] & ( 0  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 2] & ( 0  ^ in_fact_a[ 4] ))) ^ 
 ((in_fact_b[ 3] & ( 0  ^ in_fact_a[ 3] ))) ^ 
 ((in_fact_b[ 4] & ( 0  ^ in_fact_a[ 2] ))) ^ 
 ((in_fact_b[ 5] & ( 0  ^ in_fact_a[ 1] ))) ^ 
0;
assign out_prdct_z[ 1] = 
 ((in_fact_b[ 0] & ( 0  ^ in_fact_a[ 1] ))) ^ 
 ((in_fact_b[ 1] & ( 0  ^ in_fact_a[ 0]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 2] & ( 0  ^ in_fact_a[ 4]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 3] & ( 0  ^ in_fact_a[ 3]  ^ in_fact_a[ 4] ))) ^ 
 ((in_fact_b[ 4] & ( 0  ^ in_fact_a[ 2]  ^ in_fact_a[ 3] ))) ^ 
 ((in_fact_b[ 5] & ( 0  ^ in_fact_a[ 1]  ^ in_fact_a[ 2] ))) ^ 
0;
assign out_prdct_z[ 2] = 
 ((in_fact_b[ 0] & ( 0  ^ in_fact_a[ 2] ))) ^ 
 ((in_fact_b[ 1] & ( 0  ^ in_fact_a[ 1] ))) ^ 
 ((in_fact_b[ 2] & ( 0  ^ in_fact_a[ 0]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 3] & ( 0  ^ in_fact_a[ 4]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 4] & ( 0  ^ in_fact_a[ 3]  ^ in_fact_a[ 4] ))) ^ 
 ((in_fact_b[ 5] & ( 0  ^ in_fact_a[ 2]  ^ in_fact_a[ 3] ))) ^ 
0;
assign out_prdct_z[ 3] = 
 ((in_fact_b[ 0] & ( 0  ^ in_fact_a[ 3] ))) ^ 
 ((in_fact_b[ 1] & ( 0  ^ in_fact_a[ 2] ))) ^ 
 ((in_fact_b[ 2] & ( 0  ^ in_fact_a[ 1] ))) ^ 
 ((in_fact_b[ 3] & ( 0  ^ in_fact_a[ 0]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 4] & ( 0  ^ in_fact_a[ 4]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 5] & ( 0  ^ in_fact_a[ 3]  ^ in_fact_a[ 4] ))) ^ 
0;
assign out_prdct_z[ 4] = 
 ((in_fact_b[ 0] & ( 0  ^ in_fact_a[ 4] ))) ^ 
 ((in_fact_b[ 1] & ( 0  ^ in_fact_a[ 3] ))) ^ 
 ((in_fact_b[ 2] & ( 0  ^ in_fact_a[ 2] ))) ^ 
 ((in_fact_b[ 3] & ( 0  ^ in_fact_a[ 1] ))) ^ 
 ((in_fact_b[ 4] & ( 0  ^ in_fact_a[ 0]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 5] & ( 0  ^ in_fact_a[ 4]  ^ in_fact_a[ 5] ))) ^ 
0;
assign out_prdct_z[ 5] = 
 ((in_fact_b[ 0] & ( 0  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 1] & ( 0  ^ in_fact_a[ 4] ))) ^ 
 ((in_fact_b[ 2] & ( 0  ^ in_fact_a[ 3] ))) ^ 
 ((in_fact_b[ 3] & ( 0  ^ in_fact_a[ 2] ))) ^ 
 ((in_fact_b[ 4] & ( 0  ^ in_fact_a[ 1] ))) ^ 
 ((in_fact_b[ 5] & ( 0  ^ in_fact_a[ 0]  ^ in_fact_a[ 5] ))) ^ 
0;
endmodule
(* keep_hierarchy = "yes" *) (* keep = "true" *) module FrnycrcMult_00005(
                   prdct_z,
                   fact_a
                  );


  parameter  PARAM_POLY_WIDTH = 6;
  parameter  PARAM_PRIMITIVE_POLY = 3;
    output [PARAM_POLY_WIDTH-1:0] prdct_z;
    input [PARAM_POLY_WIDTH-1:0] fact_a;
    wire [PARAM_POLY_WIDTH-1:0] fact_b = 6'd9;
    wire [PARAM_POLY_WIDTH-1:0] out_prdct_z;
    wire [PARAM_POLY_WIDTH-1:0] in_fact_a;
    wire [PARAM_POLY_WIDTH-1:0] in_fact_b;
    assign  in_fact_a = fact_a;
    assign  in_fact_b = fact_b;
    assign  prdct_z = out_prdct_z;
assign out_prdct_z[ 0] = 
 ((in_fact_b[ 0] & ( 0  ^ in_fact_a[ 0] ))) ^ 
 ((in_fact_b[ 1] & ( 0  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 2] & ( 0  ^ in_fact_a[ 4] ))) ^ 
 ((in_fact_b[ 3] & ( 0  ^ in_fact_a[ 3] ))) ^ 
 ((in_fact_b[ 4] & ( 0  ^ in_fact_a[ 2] ))) ^ 
 ((in_fact_b[ 5] & ( 0  ^ in_fact_a[ 1] ))) ^ 
0;
assign out_prdct_z[ 1] = 
 ((in_fact_b[ 0] & ( 0  ^ in_fact_a[ 1] ))) ^ 
 ((in_fact_b[ 1] & ( 0  ^ in_fact_a[ 0]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 2] & ( 0  ^ in_fact_a[ 4]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 3] & ( 0  ^ in_fact_a[ 3]  ^ in_fact_a[ 4] ))) ^ 
 ((in_fact_b[ 4] & ( 0  ^ in_fact_a[ 2]  ^ in_fact_a[ 3] ))) ^ 
 ((in_fact_b[ 5] & ( 0  ^ in_fact_a[ 1]  ^ in_fact_a[ 2] ))) ^ 
0;
assign out_prdct_z[ 2] = 
 ((in_fact_b[ 0] & ( 0  ^ in_fact_a[ 2] ))) ^ 
 ((in_fact_b[ 1] & ( 0  ^ in_fact_a[ 1] ))) ^ 
 ((in_fact_b[ 2] & ( 0  ^ in_fact_a[ 0]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 3] & ( 0  ^ in_fact_a[ 4]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 4] & ( 0  ^ in_fact_a[ 3]  ^ in_fact_a[ 4] ))) ^ 
 ((in_fact_b[ 5] & ( 0  ^ in_fact_a[ 2]  ^ in_fact_a[ 3] ))) ^ 
0;
assign out_prdct_z[ 3] = 
 ((in_fact_b[ 0] & ( 0  ^ in_fact_a[ 3] ))) ^ 
 ((in_fact_b[ 1] & ( 0  ^ in_fact_a[ 2] ))) ^ 
 ((in_fact_b[ 2] & ( 0  ^ in_fact_a[ 1] ))) ^ 
 ((in_fact_b[ 3] & ( 0  ^ in_fact_a[ 0]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 4] & ( 0  ^ in_fact_a[ 4]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 5] & ( 0  ^ in_fact_a[ 3]  ^ in_fact_a[ 4] ))) ^ 
0;
assign out_prdct_z[ 4] = 
 ((in_fact_b[ 0] & ( 0  ^ in_fact_a[ 4] ))) ^ 
 ((in_fact_b[ 1] & ( 0  ^ in_fact_a[ 3] ))) ^ 
 ((in_fact_b[ 2] & ( 0  ^ in_fact_a[ 2] ))) ^ 
 ((in_fact_b[ 3] & ( 0  ^ in_fact_a[ 1] ))) ^ 
 ((in_fact_b[ 4] & ( 0  ^ in_fact_a[ 0]  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 5] & ( 0  ^ in_fact_a[ 4]  ^ in_fact_a[ 5] ))) ^ 
0;
assign out_prdct_z[ 5] = 
 ((in_fact_b[ 0] & ( 0  ^ in_fact_a[ 5] ))) ^ 
 ((in_fact_b[ 1] & ( 0  ^ in_fact_a[ 4] ))) ^ 
 ((in_fact_b[ 2] & ( 0  ^ in_fact_a[ 3] ))) ^ 
 ((in_fact_b[ 3] & ( 0  ^ in_fact_a[ 2] ))) ^ 
 ((in_fact_b[ 4] & ( 0  ^ in_fact_a[ 1] ))) ^ 
 ((in_fact_b[ 5] & ( 0  ^ in_fact_a[ 0]  ^ in_fact_a[ 5] ))) ^ 
0;
endmodule


(* keep_hierarchy = "yes" *) (* keep = "true" *) module rec_6(
                   dataIn,
                   reciprocal
/* verilator lint_off UNUSED */
                   ,loadClr,
                   valid,
                   calc,
                   clr,
                   rstn,
                   clk
/* verilator lint_on UNUSED */
                  );



  parameter PARAM_POLY_WIDTH =          6;
  parameter [PARAM_POLY_WIDTH-1:0] PARAM_CRC_POLY = 3;
  parameter PARAM_CRC_WIDTH =           PARAM_POLY_WIDTH;
  parameter PARAM_CRC_WIDTH_PLUS_1 =    PARAM_CRC_WIDTH+1;
  parameter PARAM_CNT_W = $clog2(2*PARAM_CRC_WIDTH) +1;
  parameter POLY_W = PARAM_POLY_WIDTH;
  parameter CRC_WIDTH = PARAM_POLY_WIDTH;



    input [PARAM_POLY_WIDTH-1:0] dataIn;
    output [PARAM_CRC_WIDTH-1:0] reciprocal;
/* verilator lint_off UNUSED */
    input loadClr;
    output wire valid;
    input calc;
    input rstn;
    input clr;
    input clk;
/* verilator lint_on UNUSED */


    assign valid = 1'b1;



    wire [PARAM_CRC_WIDTH-1:0] reciprocal;

    wire [PARAM_CRC_WIDTH:0] S_x_0;
    wire [PARAM_CRC_WIDTH:0] V_x_0;
    wire [PARAM_CRC_WIDTH:0] R_x_0;
    wire [PARAM_CRC_WIDTH:0] U_x_0;
    wire [PARAM_CNT_W-1:0] d_0;
    reg [PARAM_CRC_WIDTH:0] S_x_1;
    reg [PARAM_CRC_WIDTH:0] V_x_1;
    reg [PARAM_CRC_WIDTH:0] R_x_1;
    reg [PARAM_CRC_WIDTH:0] U_x_1;
    reg [PARAM_CNT_W-1:0] d_1;
    reg [PARAM_CRC_WIDTH:0] S_x_2;
    reg [PARAM_CRC_WIDTH:0] V_x_2;
    reg [PARAM_CRC_WIDTH:0] R_x_2;
    reg [PARAM_CRC_WIDTH:0] U_x_2;
    reg [PARAM_CNT_W-1:0] d_2;
    reg [PARAM_CRC_WIDTH:0] S_x_3;
    reg [PARAM_CRC_WIDTH:0] V_x_3;
    reg [PARAM_CRC_WIDTH:0] R_x_3;
    reg [PARAM_CRC_WIDTH:0] U_x_3;
    reg [PARAM_CNT_W-1:0] d_3;
    reg [PARAM_CRC_WIDTH:0] S_x_4;
    reg [PARAM_CRC_WIDTH:0] V_x_4;
    reg [PARAM_CRC_WIDTH:0] R_x_4;
    reg [PARAM_CRC_WIDTH:0] U_x_4;
    reg [PARAM_CNT_W-1:0] d_4;
    reg [PARAM_CRC_WIDTH:0] S_x_5;
    reg [PARAM_CRC_WIDTH:0] V_x_5;
    reg [PARAM_CRC_WIDTH:0] R_x_5;
    reg [PARAM_CRC_WIDTH:0] U_x_5;
    reg [PARAM_CNT_W-1:0] d_5;
    reg [PARAM_CRC_WIDTH:0] S_x_6;
    reg [PARAM_CRC_WIDTH:0] V_x_6;
    reg [PARAM_CRC_WIDTH:0] R_x_6;
    reg [PARAM_CRC_WIDTH:0] U_x_6;
    reg [PARAM_CNT_W-1:0] d_6;
    reg [PARAM_CRC_WIDTH:0] S_x_7;
    reg [PARAM_CRC_WIDTH:0] V_x_7;
    reg [PARAM_CRC_WIDTH:0] R_x_7;
    reg [PARAM_CRC_WIDTH:0] U_x_7;
    reg [PARAM_CNT_W-1:0] d_7;
    reg [PARAM_CRC_WIDTH:0] S_x_8;
    reg [PARAM_CRC_WIDTH:0] V_x_8;
    reg [PARAM_CRC_WIDTH:0] R_x_8;
    reg [PARAM_CRC_WIDTH:0] U_x_8;
    reg [PARAM_CNT_W-1:0] d_8;
    reg [PARAM_CRC_WIDTH:0] S_x_9;
    reg [PARAM_CRC_WIDTH:0] V_x_9;
    reg [PARAM_CRC_WIDTH:0] R_x_9;
    reg [PARAM_CRC_WIDTH:0] U_x_9;
    reg [PARAM_CNT_W-1:0] d_9;
    reg [PARAM_CRC_WIDTH:0] S_x_10;
    reg [PARAM_CRC_WIDTH:0] V_x_10;
    reg [PARAM_CRC_WIDTH:0] R_x_10;
    reg [PARAM_CRC_WIDTH:0] U_x_10;
    reg [PARAM_CNT_W-1:0] d_10;
    reg [PARAM_CRC_WIDTH:0] S_x_11;
    reg [PARAM_CRC_WIDTH:0] V_x_11;
    reg [PARAM_CRC_WIDTH:0] R_x_11;
    reg [PARAM_CRC_WIDTH:0] U_x_11;
    reg [PARAM_CNT_W-1:0] d_11;
    /* verilator lint_off UNUSED */
    reg [PARAM_CRC_WIDTH:0] U_x_12;
    /* verilator lint_on UNUSED */
    assign reciprocal = U_x_12[CRC_WIDTH-1:0];
     assign S_x_0 = {1'b1, PARAM_CRC_POLY};
     assign V_x_0 = {(PARAM_CRC_WIDTH_PLUS_1){1'b0}};
     assign R_x_0 = {1'b0,dataIn};
     assign U_x_0[0] = 1'b1;
     assign U_x_0[CRC_WIDTH:1] = {(PARAM_CRC_WIDTH){1'b0}};
     assign d_0   = {PARAM_CNT_W{1'b0}};



   always@(*)
   begin

      if (R_x_0 [POLY_W] == 1'b0) begin
          U_x_1 = (U_x_0 <<1) ;
          R_x_1 = (R_x_0 <<1) ;
          d_1   = d_0 + 1'b1;
          S_x_1 = S_x_0;
          V_x_1 = V_x_0;
      end else begin
             if (d_0 == {PARAM_CNT_W{1'b0}}) begin
                V_x_1 = U_x_0;
             end else begin
                if (S_x_0[POLY_W] == 1'b1) begin
                     V_x_1 = (V_x_0 ^ U_x_0);
                end else begin
                     V_x_1 = V_x_0;
                end
             end


             if (d_0 == {PARAM_CNT_W{1'b0}}) begin
                S_x_1 = R_x_0;
             end else begin
                if (S_x_0[POLY_W] == 1) begin
                    S_x_1 = ((S_x_0 ^ R_x_0) <<1) ;
                end else begin
                    S_x_1 = (S_x_0 <<1) ;
                end
             end

          if (d_0 =={PARAM_CNT_W{1'b0}}) begin
             if (S_x_0[POLY_W] == 1'b1) begin
                R_x_1 = ((S_x_0 ^ R_x_0) <<1) ;
             end else begin
                R_x_1 = (S_x_0 <<1) ;
             end
             if (S_x_0[POLY_W] == 1'b1) begin
                  U_x_1 = ((V_x_0 ^ U_x_0) <<1) ;
             end else begin
                  U_x_1 = (V_x_0 <<1) ;
             end
             d_1 = {{(PARAM_CNT_W-1){1'b0}}, 1'b1};
          end else begin
             U_x_1 = U_x_0 >>1;
             R_x_1 = R_x_0;
             d_1 = d_0 - 1'b1;
          end
      end

   end

   always@(*)
   begin

      if (R_x_1 [POLY_W] == 1'b0) begin
          U_x_2 = (U_x_1 <<1) ;
          R_x_2 = (R_x_1 <<1) ;
          d_2   = d_1 + 1'b1;
          S_x_2 = S_x_1;
          V_x_2 = V_x_1;
      end else begin
             if (d_1 == {PARAM_CNT_W{1'b0}}) begin
                V_x_2 = U_x_1;
             end else begin
                if (S_x_1[POLY_W] == 1'b1) begin
                     V_x_2 = (V_x_1 ^ U_x_1);
                end else begin
                     V_x_2 = V_x_1;
                end
             end


             if (d_1 == {PARAM_CNT_W{1'b0}}) begin
                S_x_2 = R_x_1;
             end else begin
                if (S_x_1[POLY_W] == 1) begin
                    S_x_2 = ((S_x_1 ^ R_x_1) <<1) ;
                end else begin
                    S_x_2 = (S_x_1 <<1) ;
                end
             end

          if (d_1 =={PARAM_CNT_W{1'b0}}) begin
             if (S_x_1[POLY_W] == 1'b1) begin
                R_x_2 = ((S_x_1 ^ R_x_1) <<1) ;
             end else begin
                R_x_2 = (S_x_1 <<1) ;
             end
             if (S_x_1[POLY_W] == 1'b1) begin
                  U_x_2 = ((V_x_1 ^ U_x_1) <<1) ;
             end else begin
                  U_x_2 = (V_x_1 <<1) ;
             end
             d_2 = {{(PARAM_CNT_W-1){1'b0}}, 1'b1};
          end else begin
             U_x_2 = U_x_1 >>1;
             R_x_2 = R_x_1;
             d_2 = d_1 - 1'b1;
          end
      end

   end

   always@(*)
   begin

      if (R_x_2 [POLY_W] == 1'b0) begin
          U_x_3 = (U_x_2 <<1) ;
          R_x_3 = (R_x_2 <<1) ;
          d_3   = d_2 + 1'b1;
          S_x_3 = S_x_2;
          V_x_3 = V_x_2;
      end else begin
             if (d_2 == {PARAM_CNT_W{1'b0}}) begin
                V_x_3 = U_x_2;
             end else begin
                if (S_x_2[POLY_W] == 1'b1) begin
                     V_x_3 = (V_x_2 ^ U_x_2);
                end else begin
                     V_x_3 = V_x_2;
                end
             end


             if (d_2 == {PARAM_CNT_W{1'b0}}) begin
                S_x_3 = R_x_2;
             end else begin
                if (S_x_2[POLY_W] == 1) begin
                    S_x_3 = ((S_x_2 ^ R_x_2) <<1) ;
                end else begin
                    S_x_3 = (S_x_2 <<1) ;
                end
             end

          if (d_2 =={PARAM_CNT_W{1'b0}}) begin
             if (S_x_2[POLY_W] == 1'b1) begin
                R_x_3 = ((S_x_2 ^ R_x_2) <<1) ;
             end else begin
                R_x_3 = (S_x_2 <<1) ;
             end
             if (S_x_2[POLY_W] == 1'b1) begin
                  U_x_3 = ((V_x_2 ^ U_x_2) <<1) ;
             end else begin
                  U_x_3 = (V_x_2 <<1) ;
             end
             d_3 = {{(PARAM_CNT_W-1){1'b0}}, 1'b1};
          end else begin
             U_x_3 = U_x_2 >>1;
             R_x_3 = R_x_2;
             d_3 = d_2 - 1'b1;
          end
      end

   end

   always@(*)
   begin

      if (R_x_3 [POLY_W] == 1'b0) begin
          U_x_4 = (U_x_3 <<1) ;
          R_x_4 = (R_x_3 <<1) ;
          d_4   = d_3 + 1'b1;
          S_x_4 = S_x_3;
          V_x_4 = V_x_3;
      end else begin
             if (d_3 == {PARAM_CNT_W{1'b0}}) begin
                V_x_4 = U_x_3;
             end else begin
                if (S_x_3[POLY_W] == 1'b1) begin
                     V_x_4 = (V_x_3 ^ U_x_3);
                end else begin
                     V_x_4 = V_x_3;
                end
             end


             if (d_3 == {PARAM_CNT_W{1'b0}}) begin
                S_x_4 = R_x_3;
             end else begin
                if (S_x_3[POLY_W] == 1) begin
                    S_x_4 = ((S_x_3 ^ R_x_3) <<1) ;
                end else begin
                    S_x_4 = (S_x_3 <<1) ;
                end
             end

          if (d_3 =={PARAM_CNT_W{1'b0}}) begin
             if (S_x_3[POLY_W] == 1'b1) begin
                R_x_4 = ((S_x_3 ^ R_x_3) <<1) ;
             end else begin
                R_x_4 = (S_x_3 <<1) ;
             end
             if (S_x_3[POLY_W] == 1'b1) begin
                  U_x_4 = ((V_x_3 ^ U_x_3) <<1) ;
             end else begin
                  U_x_4 = (V_x_3 <<1) ;
             end
             d_4 = {{(PARAM_CNT_W-1){1'b0}}, 1'b1};
          end else begin
             U_x_4 = U_x_3 >>1;
             R_x_4 = R_x_3;
             d_4 = d_3 - 1'b1;
          end
      end

   end

   always@(*)
   begin

      if (R_x_4 [POLY_W] == 1'b0) begin
          U_x_5 = (U_x_4 <<1) ;
          R_x_5 = (R_x_4 <<1) ;
          d_5   = d_4 + 1'b1;
          S_x_5 = S_x_4;
          V_x_5 = V_x_4;
      end else begin
             if (d_4 == {PARAM_CNT_W{1'b0}}) begin
                V_x_5 = U_x_4;
             end else begin
                if (S_x_4[POLY_W] == 1'b1) begin
                     V_x_5 = (V_x_4 ^ U_x_4);
                end else begin
                     V_x_5 = V_x_4;
                end
             end


             if (d_4 == {PARAM_CNT_W{1'b0}}) begin
                S_x_5 = R_x_4;
             end else begin
                if (S_x_4[POLY_W] == 1) begin
                    S_x_5 = ((S_x_4 ^ R_x_4) <<1) ;
                end else begin
                    S_x_5 = (S_x_4 <<1) ;
                end
             end

          if (d_4 =={PARAM_CNT_W{1'b0}}) begin
             if (S_x_4[POLY_W] == 1'b1) begin
                R_x_5 = ((S_x_4 ^ R_x_4) <<1) ;
             end else begin
                R_x_5 = (S_x_4 <<1) ;
             end
             if (S_x_4[POLY_W] == 1'b1) begin
                  U_x_5 = ((V_x_4 ^ U_x_4) <<1) ;
             end else begin
                  U_x_5 = (V_x_4 <<1) ;
             end
             d_5 = {{(PARAM_CNT_W-1){1'b0}}, 1'b1};
          end else begin
             U_x_5 = U_x_4 >>1;
             R_x_5 = R_x_4;
             d_5 = d_4 - 1'b1;
          end
      end

   end

   always@(*)
   begin

      if (R_x_5 [POLY_W] == 1'b0) begin
          U_x_6 = (U_x_5 <<1) ;
          R_x_6 = (R_x_5 <<1) ;
          d_6   = d_5 + 1'b1;
          S_x_6 = S_x_5;
          V_x_6 = V_x_5;
      end else begin
             if (d_5 == {PARAM_CNT_W{1'b0}}) begin
                V_x_6 = U_x_5;
             end else begin
                if (S_x_5[POLY_W] == 1'b1) begin
                     V_x_6 = (V_x_5 ^ U_x_5);
                end else begin
                     V_x_6 = V_x_5;
                end
             end


             if (d_5 == {PARAM_CNT_W{1'b0}}) begin
                S_x_6 = R_x_5;
             end else begin
                if (S_x_5[POLY_W] == 1) begin
                    S_x_6 = ((S_x_5 ^ R_x_5) <<1) ;
                end else begin
                    S_x_6 = (S_x_5 <<1) ;
                end
             end

          if (d_5 =={PARAM_CNT_W{1'b0}}) begin
             if (S_x_5[POLY_W] == 1'b1) begin
                R_x_6 = ((S_x_5 ^ R_x_5) <<1) ;
             end else begin
                R_x_6 = (S_x_5 <<1) ;
             end
             if (S_x_5[POLY_W] == 1'b1) begin
                  U_x_6 = ((V_x_5 ^ U_x_5) <<1) ;
             end else begin
                  U_x_6 = (V_x_5 <<1) ;
             end
             d_6 = {{(PARAM_CNT_W-1){1'b0}}, 1'b1};
          end else begin
             U_x_6 = U_x_5 >>1;
             R_x_6 = R_x_5;
             d_6 = d_5 - 1'b1;
          end
      end

   end

   always@(*)
   begin

      if (R_x_6 [POLY_W] == 1'b0) begin
          U_x_7 = (U_x_6 <<1) ;
          R_x_7 = (R_x_6 <<1) ;
          d_7   = d_6 + 1'b1;
          S_x_7 = S_x_6;
          V_x_7 = V_x_6;
      end else begin
             if (d_6 == {PARAM_CNT_W{1'b0}}) begin
                V_x_7 = U_x_6;
             end else begin
                if (S_x_6[POLY_W] == 1'b1) begin
                     V_x_7 = (V_x_6 ^ U_x_6);
                end else begin
                     V_x_7 = V_x_6;
                end
             end


             if (d_6 == {PARAM_CNT_W{1'b0}}) begin
                S_x_7 = R_x_6;
             end else begin
                if (S_x_6[POLY_W] == 1) begin
                    S_x_7 = ((S_x_6 ^ R_x_6) <<1) ;
                end else begin
                    S_x_7 = (S_x_6 <<1) ;
                end
             end

          if (d_6 =={PARAM_CNT_W{1'b0}}) begin
             if (S_x_6[POLY_W] == 1'b1) begin
                R_x_7 = ((S_x_6 ^ R_x_6) <<1) ;
             end else begin
                R_x_7 = (S_x_6 <<1) ;
             end
             if (S_x_6[POLY_W] == 1'b1) begin
                  U_x_7 = ((V_x_6 ^ U_x_6) <<1) ;
             end else begin
                  U_x_7 = (V_x_6 <<1) ;
             end
             d_7 = {{(PARAM_CNT_W-1){1'b0}}, 1'b1};
          end else begin
             U_x_7 = U_x_6 >>1;
             R_x_7 = R_x_6;
             d_7 = d_6 - 1'b1;
          end
      end

   end

   always@(*)
   begin

      if (R_x_7 [POLY_W] == 1'b0) begin
          U_x_8 = (U_x_7 <<1) ;
          R_x_8 = (R_x_7 <<1) ;
          d_8   = d_7 + 1'b1;
          S_x_8 = S_x_7;
          V_x_8 = V_x_7;
      end else begin
             if (d_7 == {PARAM_CNT_W{1'b0}}) begin
                V_x_8 = U_x_7;
             end else begin
                if (S_x_7[POLY_W] == 1'b1) begin
                     V_x_8 = (V_x_7 ^ U_x_7);
                end else begin
                     V_x_8 = V_x_7;
                end
             end


             if (d_7 == {PARAM_CNT_W{1'b0}}) begin
                S_x_8 = R_x_7;
             end else begin
                if (S_x_7[POLY_W] == 1) begin
                    S_x_8 = ((S_x_7 ^ R_x_7) <<1) ;
                end else begin
                    S_x_8 = (S_x_7 <<1) ;
                end
             end

          if (d_7 =={PARAM_CNT_W{1'b0}}) begin
             if (S_x_7[POLY_W] == 1'b1) begin
                R_x_8 = ((S_x_7 ^ R_x_7) <<1) ;
             end else begin
                R_x_8 = (S_x_7 <<1) ;
             end
             if (S_x_7[POLY_W] == 1'b1) begin
                  U_x_8 = ((V_x_7 ^ U_x_7) <<1) ;
             end else begin
                  U_x_8 = (V_x_7 <<1) ;
             end
             d_8 = {{(PARAM_CNT_W-1){1'b0}}, 1'b1};
          end else begin
             U_x_8 = U_x_7 >>1;
             R_x_8 = R_x_7;
             d_8 = d_7 - 1'b1;
          end
      end

   end

   always@(*)
   begin

      if (R_x_8 [POLY_W] == 1'b0) begin
          U_x_9 = (U_x_8 <<1) ;
          R_x_9 = (R_x_8 <<1) ;
          d_9   = d_8 + 1'b1;
          S_x_9 = S_x_8;
          V_x_9 = V_x_8;
      end else begin
             if (d_8 == {PARAM_CNT_W{1'b0}}) begin
                V_x_9 = U_x_8;
             end else begin
                if (S_x_8[POLY_W] == 1'b1) begin
                     V_x_9 = (V_x_8 ^ U_x_8);
                end else begin
                     V_x_9 = V_x_8;
                end
             end


             if (d_8 == {PARAM_CNT_W{1'b0}}) begin
                S_x_9 = R_x_8;
             end else begin
                if (S_x_8[POLY_W] == 1) begin
                    S_x_9 = ((S_x_8 ^ R_x_8) <<1) ;
                end else begin
                    S_x_9 = (S_x_8 <<1) ;
                end
             end

          if (d_8 =={PARAM_CNT_W{1'b0}}) begin
             if (S_x_8[POLY_W] == 1'b1) begin
                R_x_9 = ((S_x_8 ^ R_x_8) <<1) ;
             end else begin
                R_x_9 = (S_x_8 <<1) ;
             end
             if (S_x_8[POLY_W] == 1'b1) begin
                  U_x_9 = ((V_x_8 ^ U_x_8) <<1) ;
             end else begin
                  U_x_9 = (V_x_8 <<1) ;
             end
             d_9 = {{(PARAM_CNT_W-1){1'b0}}, 1'b1};
          end else begin
             U_x_9 = U_x_8 >>1;
             R_x_9 = R_x_8;
             d_9 = d_8 - 1'b1;
          end
      end

   end

   always@(*)
   begin

      if (R_x_9 [POLY_W] == 1'b0) begin
          U_x_10 = (U_x_9 <<1) ;
          R_x_10 = (R_x_9 <<1) ;
          d_10   = d_9 + 1'b1;
          S_x_10 = S_x_9;
          V_x_10 = V_x_9;
      end else begin
             if (d_9 == {PARAM_CNT_W{1'b0}}) begin
                V_x_10 = U_x_9;
             end else begin
                if (S_x_9[POLY_W] == 1'b1) begin
                     V_x_10 = (V_x_9 ^ U_x_9);
                end else begin
                     V_x_10 = V_x_9;
                end
             end


             if (d_9 == {PARAM_CNT_W{1'b0}}) begin
                S_x_10 = R_x_9;
             end else begin
                if (S_x_9[POLY_W] == 1) begin
                    S_x_10 = ((S_x_9 ^ R_x_9) <<1) ;
                end else begin
                    S_x_10 = (S_x_9 <<1) ;
                end
             end

          if (d_9 =={PARAM_CNT_W{1'b0}}) begin
             if (S_x_9[POLY_W] == 1'b1) begin
                R_x_10 = ((S_x_9 ^ R_x_9) <<1) ;
             end else begin
                R_x_10 = (S_x_9 <<1) ;
             end
             if (S_x_9[POLY_W] == 1'b1) begin
                  U_x_10 = ((V_x_9 ^ U_x_9) <<1) ;
             end else begin
                  U_x_10 = (V_x_9 <<1) ;
             end
             d_10 = {{(PARAM_CNT_W-1){1'b0}}, 1'b1};
          end else begin
             U_x_10 = U_x_9 >>1;
             R_x_10 = R_x_9;
             d_10 = d_9 - 1'b1;
          end
      end

   end

   always@(*)
   begin

      if (R_x_10 [POLY_W] == 1'b0) begin
          U_x_11 = (U_x_10 <<1) ;
          R_x_11 = (R_x_10 <<1) ;
          d_11   = d_10 + 1'b1;
          S_x_11 = S_x_10;
          V_x_11 = V_x_10;
      end else begin
             if (d_10 == {PARAM_CNT_W{1'b0}}) begin
                V_x_11 = U_x_10;
             end else begin
                if (S_x_10[POLY_W] == 1'b1) begin
                     V_x_11 = (V_x_10 ^ U_x_10);
                end else begin
                     V_x_11 = V_x_10;
                end
             end


             if (d_10 == {PARAM_CNT_W{1'b0}}) begin
                S_x_11 = R_x_10;
             end else begin
                if (S_x_10[POLY_W] == 1) begin
                    S_x_11 = ((S_x_10 ^ R_x_10) <<1) ;
                end else begin
                    S_x_11 = (S_x_10 <<1) ;
                end
             end

          if (d_10 =={PARAM_CNT_W{1'b0}}) begin
             if (S_x_10[POLY_W] == 1'b1) begin
                R_x_11 = ((S_x_10 ^ R_x_10) <<1) ;
             end else begin
                R_x_11 = (S_x_10 <<1) ;
             end
             if (S_x_10[POLY_W] == 1'b1) begin
                  U_x_11 = ((V_x_10 ^ U_x_10) <<1) ;
             end else begin
                  U_x_11 = (V_x_10 <<1) ;
             end
             d_11 = {{(PARAM_CNT_W-1){1'b0}}, 1'b1};
          end else begin
             U_x_11 = U_x_10 >>1;
             R_x_11 = R_x_10;
             d_11 = d_10 - 1'b1;
          end
      end

   end

   always@(*)
   begin

      if (R_x_11 [POLY_W] == 1'b0) begin
          U_x_12 = (U_x_11 <<1) ;
      end else begin

          if (d_11 =={PARAM_CNT_W{1'b0}}) begin
             if (S_x_11[POLY_W] == 1'b1) begin
                  U_x_12 = ((V_x_11 ^ U_x_11) <<1) ;
             end else begin
                  U_x_12 = (V_x_11 <<1) ;
             end
          end else begin
             U_x_12 = U_x_11 >>1;
          end
      end

   end

endmodule




`endif //SNTC_LIB_SVP_SV
