//#;; DO NOT EDIT THIS FILE
/*ENCRYPT_ME*/
////////////////////////////////////////////////////////////////////////////////
//# Copyright (c) 2018 Secantec
//# No Permission to modify and distribute this program
//# even if this copyright message remains unaltered.
//#
//# Author: Secantec 27 April, 2018
//# $Id: $//#
//# Revision History
//#       MM      17  April, 2018    Initial release
//#
////////////////////////////////////////////////////////////////////////////////

 /*ENCRYPT_ME*/


//final:MYSEED:600500
//final:PARAM_m:6
//final:PARAM_t:5

// pRev[0]:1
// pRev[1]:0
// pRev[2]:0
// pRev[3]:0
// pRev[4]:0
// pRev[5]:1
// POLY perl :0x3
// pRev[0]:1
// pRev[1]:0
// pRev[2]:0
// pRev[3]:0
// pRev[4]:0
// pRev[5]:1
// POLY perl :0x3

//  PARAM_length 63
//  1



always_comb
begin
                  clk_en_reg_00000 =
                                 (second_cur_err_cnt_00000_00062 == 6'd1) ||
                                 (second_cur_err_cnt_00001_00000 == 6'd1) ||
                                 (second_cur_err_cnt_00002_00001 == 6'd1) ||
                                 (second_cur_err_cnt_00003_00002 == 6'd1) ||
                                 (second_cur_err_cnt_00004_00003 == 6'd1) ||
                                 (second_cur_err_cnt_00005_00004 == 6'd1) ||
                                 (second_cur_err_cnt_00006_00005 == 6'd1) ||
                                 (second_cur_err_cnt_00007_00006 == 6'd1) ||
                                 (second_cur_err_cnt_00008_00007 == 6'd1) ||
                                 (second_cur_err_cnt_00009_00008 == 6'd1) ||
                                 (second_cur_err_cnt_00010_00009 == 6'd1) ||
                                 (second_cur_err_cnt_00011_00010 == 6'd1) ||
                                 (second_cur_err_cnt_00012_00011 == 6'd1) ||
                                 (second_cur_err_cnt_00013_00012 == 6'd1) ||
                                 (second_cur_err_cnt_00014_00013 == 6'd1) ||
                                 (second_cur_err_cnt_00015_00014 == 6'd1) ||
                                 (second_cur_err_cnt_00016_00015 == 6'd1) ||
                                 (second_cur_err_cnt_00017_00016 == 6'd1) ||
                                 (second_cur_err_cnt_00018_00017 == 6'd1) ||
                                 (second_cur_err_cnt_00019_00018 == 6'd1) ||
                                 (second_cur_err_cnt_00020_00019 == 6'd1) ||
                                 (second_cur_err_cnt_00021_00020 == 6'd1) ||
                                 (second_cur_err_cnt_00022_00021 == 6'd1) ||
                                 (second_cur_err_cnt_00023_00022 == 6'd1) ||
                                 (second_cur_err_cnt_00024_00023 == 6'd1) ||
                                 (second_cur_err_cnt_00025_00024 == 6'd1) ||
                                 (second_cur_err_cnt_00026_00025 == 6'd1) ||
                                 (second_cur_err_cnt_00027_00026 == 6'd1) ||
                                 (second_cur_err_cnt_00028_00027 == 6'd1) ||
                                 (second_cur_err_cnt_00029_00028 == 6'd1) ||
                                 (second_cur_err_cnt_00030_00029 == 6'd1) ||
                                 (second_cur_err_cnt_00031_00030 == 6'd1) ||
                                 (second_cur_err_cnt_00032_00031 == 6'd1) ||
                                 (second_cur_err_cnt_00033_00032 == 6'd1) ||
                                 (second_cur_err_cnt_00034_00033 == 6'd1) ||
                                 (second_cur_err_cnt_00035_00034 == 6'd1) ||
                                 (second_cur_err_cnt_00036_00035 == 6'd1) ||
                                 (second_cur_err_cnt_00037_00036 == 6'd1) ||
                                 (second_cur_err_cnt_00038_00037 == 6'd1) ||
                                 (second_cur_err_cnt_00039_00038 == 6'd1) ||
                                 (second_cur_err_cnt_00040_00039 == 6'd1) ||
                                 (second_cur_err_cnt_00041_00040 == 6'd1) ||
                                 (second_cur_err_cnt_00042_00041 == 6'd1) ||
                                 (second_cur_err_cnt_00043_00042 == 6'd1) ||
                                 (second_cur_err_cnt_00044_00043 == 6'd1) ||
                                 (second_cur_err_cnt_00045_00044 == 6'd1) ||
                                 (second_cur_err_cnt_00046_00045 == 6'd1) ||
                                 (second_cur_err_cnt_00047_00046 == 6'd1) ||
                                 (second_cur_err_cnt_00048_00047 == 6'd1) ||
                                 (second_cur_err_cnt_00049_00048 == 6'd1) ||
                                 (second_cur_err_cnt_00050_00049 == 6'd1) ||
                                 (second_cur_err_cnt_00051_00050 == 6'd1) ||
                                 (second_cur_err_cnt_00052_00051 == 6'd1) ||
                                 (second_cur_err_cnt_00053_00052 == 6'd1) ||
                                 (second_cur_err_cnt_00054_00053 == 6'd1) ||
                                 (second_cur_err_cnt_00055_00054 == 6'd1) ||
                                 (second_cur_err_cnt_00056_00055 == 6'd1) ||
                                 (second_cur_err_cnt_00057_00056 == 6'd1) ||
                                 (second_cur_err_cnt_00058_00057 == 6'd1) ||
                                 (second_cur_err_cnt_00059_00058 == 6'd1) ||
                                 (second_cur_err_cnt_00060_00059 == 6'd1) ||
                                 (second_cur_err_cnt_00061_00060 == 6'd1) ||
                                 (second_cur_err_cnt_00062_00061 == 6'd1) ||
                         0;
                  clk_en_reg_00001 =
                                 (second_cur_err_cnt_00001_00000 == 6'd2) ||
                                 (second_cur_err_cnt_00002_00001 == 6'd2) ||
                                 (second_cur_err_cnt_00003_00002 == 6'd2) ||
                                 (second_cur_err_cnt_00004_00003 == 6'd2) ||
                                 (second_cur_err_cnt_00005_00004 == 6'd2) ||
                                 (second_cur_err_cnt_00006_00005 == 6'd2) ||
                                 (second_cur_err_cnt_00007_00006 == 6'd2) ||
                                 (second_cur_err_cnt_00008_00007 == 6'd2) ||
                                 (second_cur_err_cnt_00009_00008 == 6'd2) ||
                                 (second_cur_err_cnt_00010_00009 == 6'd2) ||
                                 (second_cur_err_cnt_00011_00010 == 6'd2) ||
                                 (second_cur_err_cnt_00012_00011 == 6'd2) ||
                                 (second_cur_err_cnt_00013_00012 == 6'd2) ||
                                 (second_cur_err_cnt_00014_00013 == 6'd2) ||
                                 (second_cur_err_cnt_00015_00014 == 6'd2) ||
                                 (second_cur_err_cnt_00016_00015 == 6'd2) ||
                                 (second_cur_err_cnt_00017_00016 == 6'd2) ||
                                 (second_cur_err_cnt_00018_00017 == 6'd2) ||
                                 (second_cur_err_cnt_00019_00018 == 6'd2) ||
                                 (second_cur_err_cnt_00020_00019 == 6'd2) ||
                                 (second_cur_err_cnt_00021_00020 == 6'd2) ||
                                 (second_cur_err_cnt_00022_00021 == 6'd2) ||
                                 (second_cur_err_cnt_00023_00022 == 6'd2) ||
                                 (second_cur_err_cnt_00024_00023 == 6'd2) ||
                                 (second_cur_err_cnt_00025_00024 == 6'd2) ||
                                 (second_cur_err_cnt_00026_00025 == 6'd2) ||
                                 (second_cur_err_cnt_00027_00026 == 6'd2) ||
                                 (second_cur_err_cnt_00028_00027 == 6'd2) ||
                                 (second_cur_err_cnt_00029_00028 == 6'd2) ||
                                 (second_cur_err_cnt_00030_00029 == 6'd2) ||
                                 (second_cur_err_cnt_00031_00030 == 6'd2) ||
                                 (second_cur_err_cnt_00032_00031 == 6'd2) ||
                                 (second_cur_err_cnt_00033_00032 == 6'd2) ||
                                 (second_cur_err_cnt_00034_00033 == 6'd2) ||
                                 (second_cur_err_cnt_00035_00034 == 6'd2) ||
                                 (second_cur_err_cnt_00036_00035 == 6'd2) ||
                                 (second_cur_err_cnt_00037_00036 == 6'd2) ||
                                 (second_cur_err_cnt_00038_00037 == 6'd2) ||
                                 (second_cur_err_cnt_00039_00038 == 6'd2) ||
                                 (second_cur_err_cnt_00040_00039 == 6'd2) ||
                                 (second_cur_err_cnt_00041_00040 == 6'd2) ||
                                 (second_cur_err_cnt_00042_00041 == 6'd2) ||
                                 (second_cur_err_cnt_00043_00042 == 6'd2) ||
                                 (second_cur_err_cnt_00044_00043 == 6'd2) ||
                                 (second_cur_err_cnt_00045_00044 == 6'd2) ||
                                 (second_cur_err_cnt_00046_00045 == 6'd2) ||
                                 (second_cur_err_cnt_00047_00046 == 6'd2) ||
                                 (second_cur_err_cnt_00048_00047 == 6'd2) ||
                                 (second_cur_err_cnt_00049_00048 == 6'd2) ||
                                 (second_cur_err_cnt_00050_00049 == 6'd2) ||
                                 (second_cur_err_cnt_00051_00050 == 6'd2) ||
                                 (second_cur_err_cnt_00052_00051 == 6'd2) ||
                                 (second_cur_err_cnt_00053_00052 == 6'd2) ||
                                 (second_cur_err_cnt_00054_00053 == 6'd2) ||
                                 (second_cur_err_cnt_00055_00054 == 6'd2) ||
                                 (second_cur_err_cnt_00056_00055 == 6'd2) ||
                                 (second_cur_err_cnt_00057_00056 == 6'd2) ||
                                 (second_cur_err_cnt_00058_00057 == 6'd2) ||
                                 (second_cur_err_cnt_00059_00058 == 6'd2) ||
                                 (second_cur_err_cnt_00060_00059 == 6'd2) ||
                                 (second_cur_err_cnt_00061_00060 == 6'd2) ||
                                 (second_cur_err_cnt_00062_00061 == 6'd2) ||
                         0;
                  clk_en_reg_00002 =
                                 (second_cur_err_cnt_00002_00001 == 6'd3) ||
                                 (second_cur_err_cnt_00003_00002 == 6'd3) ||
                                 (second_cur_err_cnt_00004_00003 == 6'd3) ||
                                 (second_cur_err_cnt_00005_00004 == 6'd3) ||
                                 (second_cur_err_cnt_00006_00005 == 6'd3) ||
                                 (second_cur_err_cnt_00007_00006 == 6'd3) ||
                                 (second_cur_err_cnt_00008_00007 == 6'd3) ||
                                 (second_cur_err_cnt_00009_00008 == 6'd3) ||
                                 (second_cur_err_cnt_00010_00009 == 6'd3) ||
                                 (second_cur_err_cnt_00011_00010 == 6'd3) ||
                                 (second_cur_err_cnt_00012_00011 == 6'd3) ||
                                 (second_cur_err_cnt_00013_00012 == 6'd3) ||
                                 (second_cur_err_cnt_00014_00013 == 6'd3) ||
                                 (second_cur_err_cnt_00015_00014 == 6'd3) ||
                                 (second_cur_err_cnt_00016_00015 == 6'd3) ||
                                 (second_cur_err_cnt_00017_00016 == 6'd3) ||
                                 (second_cur_err_cnt_00018_00017 == 6'd3) ||
                                 (second_cur_err_cnt_00019_00018 == 6'd3) ||
                                 (second_cur_err_cnt_00020_00019 == 6'd3) ||
                                 (second_cur_err_cnt_00021_00020 == 6'd3) ||
                                 (second_cur_err_cnt_00022_00021 == 6'd3) ||
                                 (second_cur_err_cnt_00023_00022 == 6'd3) ||
                                 (second_cur_err_cnt_00024_00023 == 6'd3) ||
                                 (second_cur_err_cnt_00025_00024 == 6'd3) ||
                                 (second_cur_err_cnt_00026_00025 == 6'd3) ||
                                 (second_cur_err_cnt_00027_00026 == 6'd3) ||
                                 (second_cur_err_cnt_00028_00027 == 6'd3) ||
                                 (second_cur_err_cnt_00029_00028 == 6'd3) ||
                                 (second_cur_err_cnt_00030_00029 == 6'd3) ||
                                 (second_cur_err_cnt_00031_00030 == 6'd3) ||
                                 (second_cur_err_cnt_00032_00031 == 6'd3) ||
                                 (second_cur_err_cnt_00033_00032 == 6'd3) ||
                                 (second_cur_err_cnt_00034_00033 == 6'd3) ||
                                 (second_cur_err_cnt_00035_00034 == 6'd3) ||
                                 (second_cur_err_cnt_00036_00035 == 6'd3) ||
                                 (second_cur_err_cnt_00037_00036 == 6'd3) ||
                                 (second_cur_err_cnt_00038_00037 == 6'd3) ||
                                 (second_cur_err_cnt_00039_00038 == 6'd3) ||
                                 (second_cur_err_cnt_00040_00039 == 6'd3) ||
                                 (second_cur_err_cnt_00041_00040 == 6'd3) ||
                                 (second_cur_err_cnt_00042_00041 == 6'd3) ||
                                 (second_cur_err_cnt_00043_00042 == 6'd3) ||
                                 (second_cur_err_cnt_00044_00043 == 6'd3) ||
                                 (second_cur_err_cnt_00045_00044 == 6'd3) ||
                                 (second_cur_err_cnt_00046_00045 == 6'd3) ||
                                 (second_cur_err_cnt_00047_00046 == 6'd3) ||
                                 (second_cur_err_cnt_00048_00047 == 6'd3) ||
                                 (second_cur_err_cnt_00049_00048 == 6'd3) ||
                                 (second_cur_err_cnt_00050_00049 == 6'd3) ||
                                 (second_cur_err_cnt_00051_00050 == 6'd3) ||
                                 (second_cur_err_cnt_00052_00051 == 6'd3) ||
                                 (second_cur_err_cnt_00053_00052 == 6'd3) ||
                                 (second_cur_err_cnt_00054_00053 == 6'd3) ||
                                 (second_cur_err_cnt_00055_00054 == 6'd3) ||
                                 (second_cur_err_cnt_00056_00055 == 6'd3) ||
                                 (second_cur_err_cnt_00057_00056 == 6'd3) ||
                                 (second_cur_err_cnt_00058_00057 == 6'd3) ||
                                 (second_cur_err_cnt_00059_00058 == 6'd3) ||
                                 (second_cur_err_cnt_00060_00059 == 6'd3) ||
                                 (second_cur_err_cnt_00061_00060 == 6'd3) ||
                                 (second_cur_err_cnt_00062_00061 == 6'd3) ||
                         0;
                  clk_en_reg_00003 =
                                 (second_cur_err_cnt_00003_00002 == 6'd4) ||
                                 (second_cur_err_cnt_00004_00003 == 6'd4) ||
                                 (second_cur_err_cnt_00005_00004 == 6'd4) ||
                                 (second_cur_err_cnt_00006_00005 == 6'd4) ||
                                 (second_cur_err_cnt_00007_00006 == 6'd4) ||
                                 (second_cur_err_cnt_00008_00007 == 6'd4) ||
                                 (second_cur_err_cnt_00009_00008 == 6'd4) ||
                                 (second_cur_err_cnt_00010_00009 == 6'd4) ||
                                 (second_cur_err_cnt_00011_00010 == 6'd4) ||
                                 (second_cur_err_cnt_00012_00011 == 6'd4) ||
                                 (second_cur_err_cnt_00013_00012 == 6'd4) ||
                                 (second_cur_err_cnt_00014_00013 == 6'd4) ||
                                 (second_cur_err_cnt_00015_00014 == 6'd4) ||
                                 (second_cur_err_cnt_00016_00015 == 6'd4) ||
                                 (second_cur_err_cnt_00017_00016 == 6'd4) ||
                                 (second_cur_err_cnt_00018_00017 == 6'd4) ||
                                 (second_cur_err_cnt_00019_00018 == 6'd4) ||
                                 (second_cur_err_cnt_00020_00019 == 6'd4) ||
                                 (second_cur_err_cnt_00021_00020 == 6'd4) ||
                                 (second_cur_err_cnt_00022_00021 == 6'd4) ||
                                 (second_cur_err_cnt_00023_00022 == 6'd4) ||
                                 (second_cur_err_cnt_00024_00023 == 6'd4) ||
                                 (second_cur_err_cnt_00025_00024 == 6'd4) ||
                                 (second_cur_err_cnt_00026_00025 == 6'd4) ||
                                 (second_cur_err_cnt_00027_00026 == 6'd4) ||
                                 (second_cur_err_cnt_00028_00027 == 6'd4) ||
                                 (second_cur_err_cnt_00029_00028 == 6'd4) ||
                                 (second_cur_err_cnt_00030_00029 == 6'd4) ||
                                 (second_cur_err_cnt_00031_00030 == 6'd4) ||
                                 (second_cur_err_cnt_00032_00031 == 6'd4) ||
                                 (second_cur_err_cnt_00033_00032 == 6'd4) ||
                                 (second_cur_err_cnt_00034_00033 == 6'd4) ||
                                 (second_cur_err_cnt_00035_00034 == 6'd4) ||
                                 (second_cur_err_cnt_00036_00035 == 6'd4) ||
                                 (second_cur_err_cnt_00037_00036 == 6'd4) ||
                                 (second_cur_err_cnt_00038_00037 == 6'd4) ||
                                 (second_cur_err_cnt_00039_00038 == 6'd4) ||
                                 (second_cur_err_cnt_00040_00039 == 6'd4) ||
                                 (second_cur_err_cnt_00041_00040 == 6'd4) ||
                                 (second_cur_err_cnt_00042_00041 == 6'd4) ||
                                 (second_cur_err_cnt_00043_00042 == 6'd4) ||
                                 (second_cur_err_cnt_00044_00043 == 6'd4) ||
                                 (second_cur_err_cnt_00045_00044 == 6'd4) ||
                                 (second_cur_err_cnt_00046_00045 == 6'd4) ||
                                 (second_cur_err_cnt_00047_00046 == 6'd4) ||
                                 (second_cur_err_cnt_00048_00047 == 6'd4) ||
                                 (second_cur_err_cnt_00049_00048 == 6'd4) ||
                                 (second_cur_err_cnt_00050_00049 == 6'd4) ||
                                 (second_cur_err_cnt_00051_00050 == 6'd4) ||
                                 (second_cur_err_cnt_00052_00051 == 6'd4) ||
                                 (second_cur_err_cnt_00053_00052 == 6'd4) ||
                                 (second_cur_err_cnt_00054_00053 == 6'd4) ||
                                 (second_cur_err_cnt_00055_00054 == 6'd4) ||
                                 (second_cur_err_cnt_00056_00055 == 6'd4) ||
                                 (second_cur_err_cnt_00057_00056 == 6'd4) ||
                                 (second_cur_err_cnt_00058_00057 == 6'd4) ||
                                 (second_cur_err_cnt_00059_00058 == 6'd4) ||
                                 (second_cur_err_cnt_00060_00059 == 6'd4) ||
                                 (second_cur_err_cnt_00061_00060 == 6'd4) ||
                                 (second_cur_err_cnt_00062_00061 == 6'd4) ||
                         0;
                  clk_en_reg_00004 =
                                 (second_cur_err_cnt_00004_00003 == 6'd5) ||
                                 (second_cur_err_cnt_00005_00004 == 6'd5) ||
                                 (second_cur_err_cnt_00006_00005 == 6'd5) ||
                                 (second_cur_err_cnt_00007_00006 == 6'd5) ||
                                 (second_cur_err_cnt_00008_00007 == 6'd5) ||
                                 (second_cur_err_cnt_00009_00008 == 6'd5) ||
                                 (second_cur_err_cnt_00010_00009 == 6'd5) ||
                                 (second_cur_err_cnt_00011_00010 == 6'd5) ||
                                 (second_cur_err_cnt_00012_00011 == 6'd5) ||
                                 (second_cur_err_cnt_00013_00012 == 6'd5) ||
                                 (second_cur_err_cnt_00014_00013 == 6'd5) ||
                                 (second_cur_err_cnt_00015_00014 == 6'd5) ||
                                 (second_cur_err_cnt_00016_00015 == 6'd5) ||
                                 (second_cur_err_cnt_00017_00016 == 6'd5) ||
                                 (second_cur_err_cnt_00018_00017 == 6'd5) ||
                                 (second_cur_err_cnt_00019_00018 == 6'd5) ||
                                 (second_cur_err_cnt_00020_00019 == 6'd5) ||
                                 (second_cur_err_cnt_00021_00020 == 6'd5) ||
                                 (second_cur_err_cnt_00022_00021 == 6'd5) ||
                                 (second_cur_err_cnt_00023_00022 == 6'd5) ||
                                 (second_cur_err_cnt_00024_00023 == 6'd5) ||
                                 (second_cur_err_cnt_00025_00024 == 6'd5) ||
                                 (second_cur_err_cnt_00026_00025 == 6'd5) ||
                                 (second_cur_err_cnt_00027_00026 == 6'd5) ||
                                 (second_cur_err_cnt_00028_00027 == 6'd5) ||
                                 (second_cur_err_cnt_00029_00028 == 6'd5) ||
                                 (second_cur_err_cnt_00030_00029 == 6'd5) ||
                                 (second_cur_err_cnt_00031_00030 == 6'd5) ||
                                 (second_cur_err_cnt_00032_00031 == 6'd5) ||
                                 (second_cur_err_cnt_00033_00032 == 6'd5) ||
                                 (second_cur_err_cnt_00034_00033 == 6'd5) ||
                                 (second_cur_err_cnt_00035_00034 == 6'd5) ||
                                 (second_cur_err_cnt_00036_00035 == 6'd5) ||
                                 (second_cur_err_cnt_00037_00036 == 6'd5) ||
                                 (second_cur_err_cnt_00038_00037 == 6'd5) ||
                                 (second_cur_err_cnt_00039_00038 == 6'd5) ||
                                 (second_cur_err_cnt_00040_00039 == 6'd5) ||
                                 (second_cur_err_cnt_00041_00040 == 6'd5) ||
                                 (second_cur_err_cnt_00042_00041 == 6'd5) ||
                                 (second_cur_err_cnt_00043_00042 == 6'd5) ||
                                 (second_cur_err_cnt_00044_00043 == 6'd5) ||
                                 (second_cur_err_cnt_00045_00044 == 6'd5) ||
                                 (second_cur_err_cnt_00046_00045 == 6'd5) ||
                                 (second_cur_err_cnt_00047_00046 == 6'd5) ||
                                 (second_cur_err_cnt_00048_00047 == 6'd5) ||
                                 (second_cur_err_cnt_00049_00048 == 6'd5) ||
                                 (second_cur_err_cnt_00050_00049 == 6'd5) ||
                                 (second_cur_err_cnt_00051_00050 == 6'd5) ||
                                 (second_cur_err_cnt_00052_00051 == 6'd5) ||
                                 (second_cur_err_cnt_00053_00052 == 6'd5) ||
                                 (second_cur_err_cnt_00054_00053 == 6'd5) ||
                                 (second_cur_err_cnt_00055_00054 == 6'd5) ||
                                 (second_cur_err_cnt_00056_00055 == 6'd5) ||
                                 (second_cur_err_cnt_00057_00056 == 6'd5) ||
                                 (second_cur_err_cnt_00058_00057 == 6'd5) ||
                                 (second_cur_err_cnt_00059_00058 == 6'd5) ||
                                 (second_cur_err_cnt_00060_00059 == 6'd5) ||
                                 (second_cur_err_cnt_00061_00060 == 6'd5) ||
                                 (second_cur_err_cnt_00062_00061 == 6'd5) ||
                         0;

end
//END:



// CCCC primitive_P(x) = 1100001// CCCC 
// CCCC Pass Enter code length:59 (31 < length <= 63): 
